plugins {
    id 'fabric-loom' version "${loom_version}"
}

base { archivesName = project.archives_base_name }

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
    maven { url = 'https://maven.nucleoid.xyz/' }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    compileOnly 'net.luckperms:api:5.5'
    modCompileOnly 'eu.pb4:placeholder-api:2.4.2+1.21'
    implementation project(':core')
    include project(':core')
    implementation 'org.snakeyaml:snakeyaml-engine:2.9'
    include 'org.snakeyaml:snakeyaml-engine:2.9'
}

processResources {
    inputs.property 'version', project.mod_version
    from(project(':core').sourceSets.main.resources)
    filesMatching('fabric.mod.json') { expand version: project.mod_version }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    withSourcesJar()
}
