package vn.worldcomesalive.qa;
import vn.worldcomesalive.server.*;
import vn.worldcomesalive.generation.v2.*;
import vn.worldcomesalive.model.LivingWorld.*;
import net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents;
import net.minecraft.client.*;
import net.minecraft.client.gui.screen.*;
import net.minecraft.client.util.ScreenshotRecorder;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.math.*;
import net.minecraft.text.Text;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
/** Fresh natural exploration of the production V2 engine; camera movement never edits generated blocks. */
public final class GenerationV2Run {
    private static final org.slf4j.Logger LOG=org.slf4j.LoggerFactory.getLogger("wca-v2-qa");
    private int boot,step,attempt,photo;private long next,deadline;private boolean started;private CompletableFuture<Void> task;private volatile Throwable failure;private volatile Settlement town;private Path output;private boolean surveyOnly=Boolean.getBoolean("worldcomesalive.qa.surveyOnly");private long seed=Long.getLong("worldcomesalive.qa.seed",414212L);private List<View> views=new ArrayList<>();
    private record View(String name,Pos point,float yaw,float pitch){}
    public void initialize(){ClientTickEvents.END_CLIENT_TICK.register(this::tick);}
    private void tick(MinecraftClient c){long now=System.currentTimeMillis();if(now<next)return;next=now+250;try{if(failure!=null)throw new AssertionError("Server verification failed",failure);if(task!=null){if(!task.isDone())return;task.join();task=null;}if(c.player==null){if(started&&c.currentScreen!=null){for(var child:c.currentScreen.children())if(child instanceof net.minecraft.client.gui.widget.ButtonWidget button&&button.getMessage().getString().contains("I know what")){button.onPress();return;}}if(!started&&c.currentScreen instanceof TitleScreen&&++boot>20){started=true;output=c.runDirectory.toPath().toAbsolutePath().getParent().resolve("qa/v2/seed-"+seed);Files.createDirectories(output);String name="wca-v2-"+seed;if(Files.exists(c.runDirectory.toPath().resolve("saves/"+name+"/level.dat")))c.createIntegratedServerLoader().start(name,()->c.setScreen(new TitleScreen()));else{var rules=new net.minecraft.world.GameRules();rules.get(net.minecraft.world.GameRules.DO_MOB_SPAWNING).set(false,null);var info=new net.minecraft.world.level.LevelInfo("WCA Generation V2 "+seed,net.minecraft.world.GameMode.CREATIVE,false,net.minecraft.world.Difficulty.NORMAL,true,rules,net.minecraft.resource.DataConfiguration.SAFE_MODE);c.createIntegratedServerLoader().createAndStart(name,info,new net.minecraft.world.gen.GeneratorOptions(seed,true,false),r->r.get(net.minecraft.registry.RegistryKeys.WORLD_PRESET).getOrThrow(net.minecraft.world.gen.WorldPresets.DEFAULT).createDimensionsRegistryHolder(),new TitleScreen());}}return;}
        switch(step){case 0->{c.setScreen(null);c.options.getGuiScale().setValue(2);c.options.getViewDistance().setValue(14);c.options.getSimulationDistance().setValue(8);c.options.getMaxFps().setValue(40);c.options.hudHidden=true;c.onResolutionChanged();step=1;deadline=now+900000;}
        case 1->{run(c,p->{var sim=WorldSimulation.active();town=sim.state.settlements.values().stream().filter(s->s.ready&&s.generationVersion==2).findFirst().orElse(null);if(town!=null)return;if(sim.generationPending())return;int cell=sim.data.regionChunks;int rx=attempt%5-2,rz=attempt/5-2;var site=WorldSimulation.candidate(sim.world.getSeed(),rx,rz,cell);attempt++;sim.world.getChunk(site.x,site.z);int y=sim.world.getTopY(net.minecraft.world.Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,site.getCenterX(),site.getCenterZ());p.teleport(sim.world,site.getCenterX(),y+18,site.getCenterZ(),0,20);p.getAbilities().flying=true;p.sendAbilitiesUpdate();LOG.info("WCA_V2_QA_SURVEY seed={} site={} noManualPlacement=true",seed,site);});step=2;next=now+4000;}
        case 2->{if(town==null){if(now>deadline)throw new AssertionError("No valid production V2 settlement found");step=1;return;}run(c,p->{var sim=WorldSimulation.active();if(town.residents.size()!=town.generationPlan.program.populationTarget())throw new AssertionError("Population differs from accepted program");if(town.fields.isEmpty()||town.fields.values().stream().noneMatch(f->f.width>20&&!f.workers.isEmpty()))throw new AssertionError("Agriculture was not registered/assigned");if(sim.state.rooms.values().stream().noneMatch(r->r.settlement.equals(town.id)))throw new AssertionError("No generated lodging rooms");sim.save();Path ids=output.resolve("expected-identities.json");try{if(Files.exists(ids)){Set<UUID> expected=new HashSet<>(Arrays.asList(WorldStore.JSON.fromJson(Files.readString(ids),UUID[].class)));if(!expected.equals(new HashSet<>(town.residents)))throw new AssertionError("V2 identities changed on reload");LOG.info("WCA_V2_QA_PERSISTENCE_VERIFIED seed={} identities={} rooms={} fields={}",seed,town.residents.size(),sim.state.rooms.size(),town.fields.size());Files.writeString(output.resolve("persistence.json"),"{\"actualRestart\":true,\"identitiesPreserved\":true}");}else Files.writeString(ids,WorldStore.JSON.toJson(town.residents));Files.writeString(output.resolve("generation-record.json"),WorldStore.JSON.toJson(town));}catch(Exception e){throw new RuntimeException(e);}prepareViews(sim);});step=3;next=now+3000;}
        case 3->{if(photo>=views.size()){step=5;next=now+1000;return;}View view=views.get(photo);c.player.setYaw(view.yaw);c.player.setPitch(view.pitch);run(c,p->p.teleport(WorldSimulation.active().world,view.point.x(),view.point.y(),view.point.z(),view.yaw,view.pitch));step=4;next=now+(photo==0?16000:5000);}
        case 4->{View view=views.get(photo);c.player.setYaw(view.yaw);c.player.setPitch(view.pitch);shot(c,view.name);LOG.info("WCA_V2_QA_VIEW seed={} view={} renderer={}",seed,view.name,c.worldRenderer.getChunksDebugString());photo++;step=3;next=now+1000;}
        case 5->{run(c,p->{var sim=WorldSimulation.active();sim.save();try{Files.writeString(output.resolve("runtime-evidence.json"),WorldStore.JSON.toJson(Map.of("seed",seed,"center",town.center,"archetype",town.archetype,"program",town.generationPlan.program,"npcCount",town.residents.size(),"fields",town.fields.size(),"rooms",sim.state.rooms.size(),"meanTickMs",sim.server.getAverageTickTime(),"manualPlacement",false,"visualAcceptance","requires human image review")));}catch(Exception e){throw new RuntimeException(e);}LOG.info("WCA_V2_QA_CAPTURE_COMPLETE seed={} settlement={} archetype={} population={}",seed,town.center,town.archetype,town.residents.size());});step=6;next=now+2000;}
        case 6->{c.scheduleStop();step=999;}}
    }catch(Throwable error){LOG.error("WCA_V2_QA_FAILED step="+step,error);if(c.player!=null&&output!=null)shot(c,"failure-step-"+step);c.scheduleStop();step=999;}}
    private void prepareViews(WorldSimulation sim){var plan=town.generationPlan;Pos center=town.center;views.add(new View("aerial-"+town.archetype,new Pos(center.x(),center.y()+235,center.z()+40),180,82));var core=plan.district("core").center();if(surveyOnly){for(var b:plan.buildings)if(b.program().equals("crowned_inn")){var def=GenerationCatalog.active.buildings.get(b.program());var p=b.local(def.width()/2.0,def.depth()+10);views.add(new View("tavern-exterior",new Pos(p.x(),b.foundation()+5,p.z()),180+b.rotation()*90,12));}return;}views.add(new View("village-center",new Pos(core.x()+18,center.y()+5,core.z()+18),135,10));var field=plan.fields.stream().filter(f->f.kind().equals("CROP")).findFirst().orElseThrow();var rect=field.boundary();views.add(new View("agricultural-belt",new Pos(rect.center().x(),sim.world.getTopY(net.minecraft.world.Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,(int)rect.center().x(),rect.maxZ())+12,rect.maxZ()+18),180,22));for(var b:plan.buildings){var def=GenerationCatalog.active.buildings.get(b.program());if(def.type().equals("cottage")||def.type().equals("tavern")||def.type().equals("forge")||def.type().equals("barn")||def.type().equals("trading_post")){var p=b.local(def.width()/2.0,def.depth()+13);views.add(new View("exterior-"+b.program()+"-"+b.id(),new Pos(p.x(),b.foundation()+5,p.z()),180+b.rotation()*90,12));}if(def.type().equals("cottage")||def.type().equals("tavern")||def.type().equals("forge")){for(var room:b.rooms()){var r=room.bounds();var p=b.local(r.maxX()-1.3,r.maxZ()-.8);views.add(new View("interior-"+b.program()+"-"+room.type()+"-"+room.id(),new Pos(p.x(),b.foundation()+1.2+room.floor()*def.storey(),p.z()),135+b.rotation()*90,15));}}}if(plan.dungeon!=null){var dungeon=plan.dungeon;var entry=dungeon.chambers.stream().filter(r->r.id().equals("entrance")).findFirst().orElseThrow();views.add(new View("dungeon-entrance",new Pos(entry.bounds().center().x(),dungeon.surface+4,entry.bounds().maxZ()+10),180,12));for(var room:dungeon.chambers)if(room.level()>0)views.add(new View("dungeon-zone-"+room.zone()+"-"+room.id(),new Pos(room.bounds().maxX()-1.3,dungeon.surface-room.level()*8+1.2,room.bounds().maxZ()-1.3),135,12));}}
    private void run(MinecraftClient c,java.util.function.Consumer<ServerPlayerEntity> action){task=new CompletableFuture<>();c.getServer().execute(()->{try{action.accept(c.getServer().getPlayerManager().getPlayer(c.player.getUuid()));task.complete(null);}catch(Throwable e){failure=e;task.completeExceptionally(e);}});}
    private void shot(MinecraftClient c,String name){c.getToastManager().clear();ScreenshotRecorder.saveScreenshot(c.runDirectory,name+".png",c.getFramebuffer(),ignored->{try{Files.copy(c.runDirectory.toPath().resolve("screenshots/"+name+".png"),output.resolve(name+".png"),StandardCopyOption.REPLACE_EXISTING);}catch(Exception e){LOG.error("Screenshot copy failed",e);}});}
}
