package io.github.aristheg201.svhub.engine;

/** Stable event protocol shared by auto-battler and defense content. */
public enum BattleEvent {
    ON_GAME_START, ON_STAGE_START, ON_ROUND_START, ON_PREP_START, ON_COMBAT_START, ON_COMBAT_END,
    ON_ATTACK_START, ON_ATTACK, ON_BASIC_HIT, ON_CRIT, ON_CAST_START, ON_CAST, ON_CAST_END,
    ON_DAMAGE, ON_DAMAGE_TAKEN, ON_HEAL, ON_SHIELD, ON_SHIELD_BREAK,
    ON_TARGET_ACQUIRED, ON_TARGET_CHANGED, ON_MOVE, ON_DASH, ON_KILL, ON_ASSIST, ON_DEATH, ON_REVIVE,
    ON_SUMMON, ON_TRANSFORM, ON_STATUS_APPLIED, ON_STATUS_REMOVED, ON_MANA_GAIN, ON_MANA_FULL,
    ON_ITEM_EQUIPPED, ON_ITEM_REMOVED, ON_UNIT_BOUGHT, ON_UNIT_SOLD, ON_UNIT_STAR_UP,
    ON_SHOP_REFRESH, ON_XP_PURCHASE, ON_LEVEL_UP, ON_TRAIT_ACTIVATED, ON_TRAIT_THRESHOLD_CHANGED,
    ON_BENCH_ENTER, ON_BOARD_ENTER, ON_BOARD_EXIT, ON_TICK,
    ON_WAVE_START, ON_WAVE_END, ON_LEAK, ON_HP_THRESHOLD, ON_BOSS_PHASE, ON_ENRAGE
}
