package vn.worldcomesalive.server;
import vn.worldcomesalive.model.LivingWorld.*;
import vn.worldcomesalive.world.CitizenEntity;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.item.*;
import net.minecraft.registry.Registries;
import net.minecraft.util.Identifier;
import net.minecraft.text.Text;
import java.util.*;

/** All eligibility, distance, session, money, item and outcome checks happen on the server. */
public final class Interactions {
    private record Session(UUID npc,long token,long revision,long expires,long lastAction,Pos anchor,String context) {}
    private final WorldSimulation simulation;
    private final Map<UUID,Session> sessions=new HashMap<>();
    public Interactions(WorldSimulation simulation){this.simulation=simulation;}
    public static boolean valid(UUID requested,UUID sessionNpc,long suppliedToken,long token,long revision,long expected,long clock,long expires,double distance,boolean sameWorld){return requested.equals(sessionNpc)&&suppliedToken==token&&revision==expected&&clock<expires&&distance<=7&&sameWorld;}
    public void open(ServerPlayerEntity player,CitizenEntity entity){Npc n=simulation.npc(entity.getUuid());if(n==null||player.squaredDistanceTo(entity)>49)return;Session session=new Session(n.id,new java.security.SecureRandom().nextLong(),0,simulation.state.clock+1200,-100,null,"npc");sessions.put(player.getUuid(),session);n.interactionUntil=simulation.state.clock+400;send(player,n,session,"talk","");}
    public void handle(ServerPlayerEntity player,InteractionPackets.Input request){
        Npc n=simulation.npc(request.npc());Session old=sessions.get(player.getUuid());if(n==null||old==null)return;
        var w=simulation.state;double distance=new Pos(player.getX(),player.getY(),player.getZ()).distance(old.anchor==null?n.location:old.anchor);
        if(!valid(request.npc(),old.npc,request.token(),old.token,request.revision(),old.revision,w.clock,old.expires,distance,player.getServerWorld()==simulation.world)||w.clock-old.lastAction<5)return;
        if(request.action().equals("close")){n.interactionUntil=w.clock;sessions.remove(player.getUuid());return;}
        List<String> options;if(old.context.equals("npc"))options=options(n,player);else{options=new ArrayList<>(List.of("close","requests","bounties","journal","settlement","talk"));if(old.context.equals("shop")){options.add("shop_sell");for(var row:shopMenu(n,player,false))options.add("shop_buy:"+row.id());}if(old.context.equals("shop_sell")){options.add("shop");for(var row:shopMenu(n,player,true))options.add("shop_sell:"+row.id());}if(old.context.equals("trade"))for(var row:personalTradeMenu(n))options.add("trade_buy:"+row.id());}options.addAll(simulation.civilization.actions(n,player.getUuid(),old.context.equals("board"),old.context.equals("journal")));if(old.context.equals("board")||old.context.equals("bounties"))options.addAll(simulation.civilization.bountyActions(n));if(!options.contains(request.action()))return;
        String nextContext=request.action().equals("journal")?"journal":request.action().equals("bounties")?"bounties":request.action().equals("shop")?"shop":request.action().equals("shop_sell")?"shop_sell":request.action().equals("trade")?"trade":request.action().equals("talk")?(old.anchor==null?"npc":"board"):old.context;Session current=new Session(n.id,old.token,old.revision+1,w.clock+1200,w.clock,old.anchor,nextContext);sessions.put(player.getUuid(),current);n.interactionUntil=w.clock+400;
        var relation=n.relationship(player.getUuid());PlayerLife life=w.players.computeIfAbsent(player.getUuid(),id->new PlayerLife());Settlement s=w.settlements.get(n.settlement);String response="",topic=request.action();
        if(request.action().startsWith("order:")||request.action().startsWith("treat:")){boolean treat=request.action().startsWith("treat:");String id=request.action().substring(request.action().indexOf(':')+1);response=simulation.domestic.order(player,n,id,treat);topic=treat?"drinks":"menu";}
        if(request.action().startsWith("rent:")||request.action().startsWith("renew:")||request.action().startsWith("checkout:")||request.action().equals("recover")){response=simulation.lodging.action(player,n,request.action());topic="lodging";if(request.action().equals("recover"))return;}
        if(request.action().startsWith("details:")||request.action().startsWith("accept:")||request.action().startsWith("fulfill:")){response=simulation.civilization.contractAction(player,n,request.action());topic=old.context.equals("journal")?"journal":"requests";}
        if(request.action().startsWith("bounty:")){response=simulation.civilization.bountyAction(n,request.action());topic="bounties";}
        if(request.action().equals("restrain")){response=simulation.civilization.restrain(player,n);topic="talk";}
        if(request.action().startsWith("shop_buy:")){String id=request.action().substring("shop_buy:".length());Building shop=s.buildings.get(n.workplace);if(shop==null){response="This NPC is not currently operating a shop.";topic="shop";}else{int stock=shop.stock.getOrDefault(id,0);long price=shopPrice(n,player,id,false);var item=Registries.ITEM.get(Identifier.of(id));if(stock<=0)response="Sold out.";else if(life.money<price)response="You need "+price+" crowns.";else{life.money-=price;shop.money+=price;shop.stock.put(id,stock-1);ItemStack stack=new ItemStack(item);if(!player.getInventory().insertStack(stack))player.dropItem(stack,false);w.transact(player.getUuidAsString(),shop.id,id,1,price,"shop purchase");response="Purchased "+id.replace("minecraft:","").replace("_"," ")+" for "+price+" crowns.";}topic="shop";}}
        if(request.action().startsWith("shop_sell:")){String id=request.action().substring("shop_sell:".length());Building shop=s.buildings.get(n.workplace);long offer=shopPrice(n,player,id,true);var item=Registries.ITEM.get(Identifier.of(id));int slot=-1;for(int i=0;i<player.getInventory().size();i++)if(player.getInventory().getStack(i).isOf(item)){slot=i;break;}if(shop==null||slot<0)response="You are not carrying that item.";else if(shop.money<offer)response="The merchant cannot afford that purchase.";else{player.getInventory().getStack(slot).decrement(1);shop.stock.merge(id,1,Integer::sum);shop.money-=offer;life.money+=offer;w.transact(shop.id,player.getUuidAsString(),id,1,offer,"shop purchase from player");response="Sold "+id.replace("minecraft:","").replace("_"," ")+" for "+offer+" crowns.";}topic="shop_sell";}
        if(request.action().startsWith("trade_buy:")){String id=request.action().substring("trade_buy:".length());int have=n.inventory.getOrDefault(id,0);long price=Math.max(1,shopPrice(n,player,id,false)+Math.round(n.trait("greed")*2));var item=Registries.ITEM.get(Identifier.of(id));if(have<=0)response="I no longer have that.";else if(life.money<price)response="I would want "+price+" crowns for it.";else{life.money-=price;n.money+=price;n.inventory.put(id,have-1);ItemStack stack=new ItemStack(item);if(!player.getInventory().insertStack(stack))player.dropItem(stack,false);w.transact(player.getUuidAsString(),n.id.toString(),id,1,price,"direct NPC trade");relation.respect+=.2;response="Deal. "+price+" crowns.";}topic="trade";}
        switch(request.action()){
            case "greet","talk"->{if(w.clock-relation.lastInteraction>=1200){relation.friendship+=.7+n.trait("kindness");relation.trust+=.2;relation.familiarity++;relation.lastInteraction=w.clock;w.remember(n,new Memory("friendly_greeting",player.getUuid(),s.id,w.clock,.2,.3,1,"witnessed"));}life.skills.merge("speech",.001,Double::sum);}
            case "gift"->{ItemStack held=player.getMainHandStack();if(held.isEmpty()){response="Hold a gift in your main hand.";break;}String item=net.minecraft.registry.Registries.ITEM.getId(held.getItem()).toString();Set<String> tags=new HashSet<>();var domestic=vn.worldcomesalive.domestic.DomesticContent.active.good(item);if(domestic!=null)tags.addAll(domestic.tags());if(held.contains(net.minecraft.component.DataComponentTypes.FOOD))tags.add("food");if(item.contains("flower")||held.isIn(net.minecraft.registry.tag.ItemTags.FLOWERS))tags.add("flower");if(held.isIn(net.minecraft.registry.tag.ItemTags.PICKAXES)||held.isIn(net.minecraft.registry.tag.ItemTags.AXES))tags.add("tool");if(item.contains("cobblemon"))tags.add("pokemon");double value=SocialRules.gift(n,player.getUuid(),item,tags,w,simulation.data);if(value>0){held.decrement(1);response="Thank you. I will remember this gift. Friendship +"+String.format(java.util.Locale.ROOT,"%.1f",value);}else response="I appreciate the thought, but I cannot accept this gift.";}
            case "shop"->{topic="shop";response="Browse current stock. Prices and quantities are backed by this business inventory.";}
            case "shop_sell"->{topic="shop_sell";response="These are items this merchant can currently purchase from you.";}
            case "trade"->{topic="trade";response="This is a direct personal trade, separate from the shop business.";}
            case "deposit"->{ItemStack held=player.getMainHandStack();if(!held.isOf(Items.EMERALD))response="Hold an emerald to exchange it for 10 crowns.";else{held.decrement(1);life.money+=10;w.transact("exchange",player.getUuidAsString(),"minecraft:emerald",1,10,"currency exchange");response="An emerald for 10 crowns.";}}
            case "invite"->{if(n.activity.equals("working"))response="After my shift. I have people depending on me.";else{relation.friendship+=1;n.goal="social";n.plan=new ArrayList<>(List.of("visit_tavern","converse"));n.actionUntil=0;response="Let us meet at the tavern.";}}
            case "flirt"->{if(relation.trust<15||relation.friendship<25||n.trait("sociability")<.25||w.clock-relation.lastInteraction<1200)response="I am not ready for that. Friendship takes time.";else{relation.attraction+=2;relation.lastInteraction=w.clock;relation.stage=relation.attraction>20?"dating":"friend";response="I would enjoy getting to know you better.";}}
            case "propose"->{if(relation.stage.equals("dating")&&relation.trust>=65&&relation.attraction>=60&&relation.familiarity>=70&&life.spouse==null){relation.stage="married";life.spouse=n.id;life.property.add(n.home);relation.loyalty+=30;response="Yes. We can share a home and a life together.";w.remember(n,new Memory("married",player.getUuid(),n.home,w.clock,1,1,1,"witnessed"));}else response="A lifelong commitment needs more time and trust.";}
            case "help"->{ItemStack held=player.getMainHandStack();if(!held.isOf(Items.WHEAT))response="Bring wheat for the bakery. Supply helps our whole village.";else{held.decrement(1);Building bakery=s.service("bakery");if(bakery!=null)bakery.stock.merge("minecraft:wheat",1,Integer::sum);relation.trust+=2;relation.respect+=2;w.remember(n,new Memory("helped",player.getUuid(),s.id,w.clock,.85,.5,1,"witnessed"));life.skills.merge("farming",.005,Double::sum);response="Thank you for helping keep the bakery supplied.";}}
            case "share_meal"->{ItemStack held=player.getMainHandStack();String id=net.minecraft.registry.Registries.ITEM.getId(held.getItem()).toString();var food=vn.worldcomesalive.domestic.DomesticContent.active.good(id);if(food==null||food.nutrition()==0||food.category().equals("drink"))response="Bring a cooked meal to share.";else if(w.clock-relation.lastInteraction<1200||n.preferences.getOrDefault(id,.5)<.1)response="Another time, perhaps.";else{held.decrement(1);s.households.get(n.household).supplies.merge(id,1,Integer::sum);relation.friendship+=1.5;relation.trust+=1;relation.lastInteraction=w.clock;w.remember(n,new Memory("shared_meal",player.getUuid(),n.home,w.clock,.7,.5,1,"witnessed"));response="Thank you. We can enjoy this together at home.";}}
            case "settlement"->{topic="management";response=simulation.civilization.status(n);}
            case "requests"->{response=simulation.civilization.requestText(n);}
            case "journal"->{response="Your accepted contracts. Information reflects what the requester actually knows.";}
            case "bounties"->{response=simulation.civilization.bountyText(n);}
            case "menu","drinks"->{response="Our kitchen and cellar supply this menu. Prices and available portions are shown below.";}
            case "cards"->{if(!SocialRules.acceptsCards(n,player.getUuid(),w.clock,0)){response="Not now. I have responsibilities to attend to.";break;}try{vn.svarcade.tcg.fabric.TcgMod.challengeLivingNpc(player,n.id,n.name,n.decks.get("casual"),simulation.domestic.cardSkill(n),won->{relation.respect+=won?2:1;relation.rivalry+=n.trait("aggression");n.skills.merge("cards",.003,Double::sum);n.activity="socializing";n.actionUntil=0;n.plan.clear();n.version++;w.remember(n,new Memory(won?"lost_card_duel":"won_card_duel",player.getUuid(),s.id,w.clock,.8,won?-.2:.4,1,"witnessed"));});n.activity="playing Card Worlds";n.travel=null;n.version++;sessions.remove(player.getUuid());return;}catch(RuntimeException failure){response=failure.getMessage();}}
            case "rent"->{topic="lodging";response="Choose an available room. A night includes a private bed, furniture and secure storage.";}
            case "buy_home"->{Building home=s.buildings.get(n.home);if(life.money<300)response="A deed to this cottage costs 300 crowns.";else if(!home.owner.startsWith("player:")){life.money-=300;n.money+=300;home.owner="player:"+player.getUuid();life.property.add(home.id);w.transact(player.getUuidAsString(),n.id.toString(),home.id,1,300,"property deed");response="The deed is yours. Please respect the household living here.";}else response="This property is already privately owned.";}
            case "threaten"->{crime(player,n,"robbery",25);response="Guards! Leave us in peace!";}
        }
        relation.clamp();n.version++;w.revision++;send(player,n,current,topic,response);
    }
    private List<String> options(Npc n,ServerPlayerEntity player){List<String> actions=new ArrayList<>(List.of("greet","talk","ask","gift","help","invite","share_meal","requests","settlement","journal"));if(n.age>=18&&n.relationship(player.getUuid()).fear<30)actions.add("flirt");if(n.relationship(player.getUuid()).stage.equals("dating"))actions.add("propose");if(!n.workplace.isBlank()&&Set.of("baker","innkeeper","farmer","merchant","blacksmith").contains(n.profession)){actions.add("shop");actions.add("trade");actions.add("deposit");}Building tavern=simulation.state.settlements.get(n.settlement).service("tavern");if(tavern!=null&&(n.profession.equals("innkeeper")||tavern.contains(n.location))){actions.add("menu");actions.add("drinks");for(var row:menu(n,player)){actions.add("order:"+row.id());if(row.category().equals("Drink"))actions.add("treat:"+row.id());}}if(n.profession.equals("innkeeper")){actions.add("rent");actions.addAll(simulation.lodging.actions(n,player.getUuid()));}if(n.profession.equals("resident")&&n.age>=18)actions.add("buy_home");if(!n.decks.isEmpty())actions.add("cards");if(n.age>=18)actions.add("threaten");if(vn.worldcomesalive.civilization.BountySystem.activeForTarget(simulation.state,n.id).isPresent())actions.add("restrain");actions.addAll(simulation.civilization.actions(n,player.getUuid(),false,false));return actions;}
    private List<InteractionPackets.MenuRow> menu(Npc n,ServerPlayerEntity player){Building tavern=simulation.state.settlements.get(n.settlement).service("tavern");if(tavern==null)return List.of();return tavern.stock.entrySet().stream().filter(e->e.getValue()>0&&vn.worldcomesalive.domestic.DomesticContent.active.good(e.getKey())!=null).filter(e->{var g=vn.worldcomesalive.domestic.DomesticContent.active.good(e.getKey());return g.category().equals("drink")||g.nutrition()>0;}).map(e->{var c=vn.worldcomesalive.domestic.DomesticContent.active;var g=c.good(e.getKey());return new InteractionPackets.MenuRow(e.getKey(),g.name(),g.category().equals("drink")?"Drink":g.value()>=10?"Specials":"Food",c.price(e.getKey(),tavern.region,n.relationship(player.getUuid()).trust),e.getValue());}).sorted(Comparator.comparing(InteractionPackets.MenuRow::category).thenComparing(InteractionPackets.MenuRow::name)).toList();}
    private void send(ServerPlayerEntity p,Npc n,Session session,String topic,String response){var w=simulation.state;Settlement s=w.settlements.get(n.settlement);var r=n.relationship(p.getUuid());PlayerLife life=w.players.computeIfAbsent(p.getUuid(),id->new PlayerLife());List<String> eligible=session.context.equals("npc")?options(n,p):new ArrayList<String>(List.of("requests","bounties","journal","settlement","talk"));eligible.addAll(simulation.civilization.actions(n,p.getUuid(),session.context.equals("board"),session.context.equals("journal")));if(session.context.equals("board")||session.context.equals("bounties"))eligible.addAll(simulation.civilization.bountyActions(n));String text=response.isBlank()?SocialRules.dialogue(n,p.getUuid(),p.getName().getString(),topic,s,w,simulation.data,simulation.world.isRaining()):response;var view=new InteractionPackets.View(n.id,session.token,session.revision,n.name,n.profession,s.name,n.activity,n.emotion,text,eligible,r.friendship,r.trust,r.respect,r.stage,life.money,n.pokemon.isEmpty()?"":n.pokemon.getFirst().species+" · "+n.pokemon.getFirst().role,"Household "+s.households.get(n.household).name+" · "+s.buildings.get(n.home).type,simulation.status(),Set.of("requests","journal").contains(topic)?simulation.civilization.contracts(n,p.getUuid(),session.context.equals("board"),topic.equals("journal")):topic.equals("bounties")?simulation.civilization.bounties(n):topic.equals("lodging")?simulation.lodging.menu(n,p.getUuid()):topic.equals("shop")?shopMenu(n,p,false):topic.equals("shop_sell")?shopMenu(n,p,true):topic.equals("trade")?personalTradeMenu(n):menu(n,p),Set.of("management","requests","journal","bounties","shop","shop_sell","trade").contains(topic)?topic:topic.equals("lodging")?"lodging":topic.equals("menu")?"menu":topic.equals("drinks")?"drinks":"dialogue");if(ServerPlayNetworking.canSend(p,InteractionPackets.Snapshot.ID))ServerPlayNetworking.send(p,new InteractionPackets.Snapshot(WorldStore.JSON.toJson(view)));else p.sendMessage(Text.literal(text),false);}
    private long shopPrice(Npc n,ServerPlayerEntity player,String id,boolean selling){var good=vn.worldcomesalive.domestic.DomesticContent.active.good(id);long base=good==null?4:Math.max(1,good.value());double trust=n.relationship(player.getUuid()).trust;double modifier=selling?.55:1.0;modifier*=1.0-Math.max(-.15,Math.min(.15,trust/500.0));return Math.max(1,Math.round(base*modifier));}
    private List<InteractionPackets.MenuRow> shopMenu(Npc n,ServerPlayerEntity player,boolean selling){Settlement s=simulation.state.settlements.get(n.settlement);Building shop=s==null?null:s.buildings.get(n.workplace);if(shop==null)return List.of();if(!selling)return shop.stock.entrySet().stream().filter(e->e.getValue()>0).map(e->new InteractionPackets.MenuRow(e.getKey(),e.getKey().replace("minecraft:","").replace("worldcomesalive:","").replace("_"," "),"BUY",shopPrice(n,player,e.getKey(),false),e.getValue())).sorted(Comparator.comparing(InteractionPackets.MenuRow::name)).toList();Map<String,Integer> counts=new LinkedHashMap<>();for(int i=0;i<player.getInventory().size();i++){ItemStack stack=player.getInventory().getStack(i);if(stack.isEmpty())continue;String id=Registries.ITEM.getId(stack.getItem()).toString();counts.merge(id,stack.getCount(),Integer::sum);}return counts.entrySet().stream().filter(e->shop.money>=shopPrice(n,player,e.getKey(),true)).map(e->new InteractionPackets.MenuRow(e.getKey(),e.getKey().replace("minecraft:","").replace("worldcomesalive:","").replace("_"," "),"SELL",shopPrice(n,player,e.getKey(),true),e.getValue())).sorted(Comparator.comparing(InteractionPackets.MenuRow::name)).toList();}
    private List<InteractionPackets.MenuRow> personalTradeMenu(Npc n){return n.inventory.entrySet().stream().filter(e->e.getValue()>0&&!e.getKey().startsWith("pantry_")).map(e->new InteractionPackets.MenuRow(e.getKey(),e.getKey().replace("minecraft:","").replace("worldcomesalive:","").replace("_"," "),"NPC OFFER",Math.max(1,e.getValue()),e.getValue())).toList();}
    public void openBoard(ServerPlayerEntity player,net.minecraft.util.math.BlockPos pos){var s=simulation.state.settlements.values().stream().filter(v->v.ready&&v.center.distance(new Pos(pos.getX(),pos.getY(),pos.getZ()))<100).min(Comparator.comparingDouble(v->v.center.distance(new Pos(pos.getX(),pos.getY(),pos.getZ())))).orElse(null);if(s==null)return;Npc n=s.residents.stream().map(simulation::npc).filter(a->a.profession.equals("baker")).findFirst().orElse(simulation.npc(s.residents.getFirst()));var session=new Session(n.id,new java.security.SecureRandom().nextLong(),0,simulation.state.clock+1200,-100,new Pos(pos.getX()+.5,pos.getY()+.5,pos.getZ()+.5),"board");sessions.put(player.getUuid(),session);send(player,n,session,"requests","Public requests backed by actual local shortages. Speak to the named requester to deliver supplies.");}
    public void crime(ServerPlayerEntity actor,Npc victim,String type,long bounty){var w=simulation.state;Settlement s=w.settlements.get(victim.settlement);Set<UUID> witnesses=new HashSet<>();for(CitizenEntity e:simulation.visible())if(e.distanceTo(actor)<24&&e.getVisibilityCache().canSee(actor)){Npc witness=simulation.npc(e.getUuid());witnesses.add(witness.id);simulation.interrupt(witness,type.equals("assault")?"assault":"crime",actor.getUuid());w.remember(witness,new Memory(type,actor.getUuid(),s.id,w.clock,.95,-.8,1,"witnessed"));witness.relationship(actor.getUuid()).trust-=20;}
        if(!witnesses.isEmpty()){var life=w.players.computeIfAbsent(actor.getUuid(),id->new PlayerLife());life.bounty.merge(s.faction,bounty,Long::sum);actor.sendMessage(Text.literal("The "+s.faction.replace('_',' ')+" watch has received a report: "+type+". Bounty "+life.bounty.get(s.faction)+" crowns."),false);}
    }
    public void disconnect(UUID player){sessions.remove(player);}
}
