package io.github.aristheg201.svarcade.native.game

import kotlin.test.*

class TowerDefenseDefinitionTest {
 @Test fun bundledMapTowersEnemiesExplicitWavesAndBossesAreExternalized(){val d=TowerDefenseDefinitions.bundled;assertEquals(20,d.width);assertEquals(12,d.height);assertTrue(d.path.size>=60);assertTrue(d.buildZones.size>=80);assertEquals(6,d.towers.size);assertEquals(4,d.enemies.size);assertEquals(20,d.waves.size);assertTrue(d.waves[4].groups.any{it.enemy in d.bosses.map(TdBossDefinition::id)});assertTrue(d.bosses.isNotEmpty())}
 @Test fun nonDefaultDefinitionControlsGeometryUpgradesTimingDamageAndRecovery(){
  val tower=TdTowerDefinition(id="odd",name="Odd",species="cobblemon:ditto",element="Arcane",cost=3,damage=7,range=9.0,cooldown=1,moveId="transform",targetMode="strongest",targetFilters=setOf("boss","ground"),effects=listOf(io.github.aristheg201.svarcade.engine.EffectDefinition.amount("damage","current_target",7.0)),upgrades=listOf(TdUpgradeLevel(1),TdUpgradeLevel(2,17,3.0,4.0,1)))
  val enemy=TdEnemyDefinition("tiny",11,.01,2,7,setOf("ground"),listOf(TdResistance("Arcane",.25)))
  val boss=TdBossDefinition("odd_boss",31,.01,19,9,phases=listOf(TdBossPhase(.4,enrageMultiplier=2.0)))
  val d=TowerDefenseDefinition("test:odd",5,4,listOf(0,1,2,3,4),mapOf(0 to listOf(1),1 to listOf(2),2 to listOf(3),3 to listOf(4)),listOf(5,6,7),0,4,23,13,10,.42,listOf(tower),listOf(enemy),listOf(boss),listOf(TdWaveDefinition(1,listOf(TdSpawnGroup("odd_boss",1,9,4)),37)),1)
  TowerDefenseDefinitions.validate(d,"test.json");val seats=listOf(NativeSeat("a","A"));val s=TowerDefenseSession(seats,4,"td-test",definition=d)
  assertEquals(5,s.viewFor("a").boardWidth);assertTrue(s.act("a","deploy",mapOf("type" to "odd","slot" to "5")).accepted);assertTrue(s.act("a","start_wave",emptyMap()).accepted)
  val snap=s.snapshotState();val restored=TowerDefenseSession(seats,4,"td-test",snap,d);assertEquals(s.viewFor("a").board,restored.viewFor("a").board);assertEquals("test:odd",restored.viewFor("a").fields["definition"])
 }
 @Test fun validatorRejectsImplicitOrUnknownWaveContentWithPath(){val bad=TowerDefenseDefinition(id="x",width=4,height=4,path=listOf(0,1),buildZones=listOf(2),spawn=0,core=1,towers=listOf(TdTowerDefinition(id="t",upgrades=listOf(TdUpgradeLevel(1)))),enemies=listOf(TdEnemyDefinition(id="e")),waves=listOf(TdWaveDefinition(1,listOf(TdSpawnGroup("missing"))))) ;val e=assertFailsWith<IllegalArgumentException>{TowerDefenseDefinitions.validate(bad,"bad.json")};assertContains(e.message!!,"bad.json x.waves.1.groups[0]")}
 @Test fun genericLootSettlementSurvivesRecoveryWithoutDuplication(){val effect=io.github.aristheg201.svarcade.engine.EffectDefinition.amount("damage","current_target",10.0);val tower=TdTowerDefinition("t","T","cobblemon:ditto","normal",1,10,9.0,0,effects=listOf(effect),upgrades=listOf(TdUpgradeLevel(1)));val waveLoot=TdLootTable("wave",1,listOf(TdLootEntry("gold","gold",7,1)));val clearLoot=TdLootTable("clear",1,listOf(TdLootEntry("gold","gold",11,1)));val d=TowerDefenseDefinition(id="loot",width=4,height=4,path=listOf(0,1),buildZones=listOf(4),spawn=0,core=1,startingGold=10,simulationStepMs=1,towers=listOf(tower),enemies=listOf(TdEnemyDefinition("e",1,0.0,0,1)),waves=listOf(TdWaveDefinition(1,listOf(TdSpawnGroup("e",1,0,0)),0,"wave")),victoryWave=1,clearLootTable="clear",lootTables=listOf(waveLoot,clearLoot));val seats=listOf(NativeSeat("a","A"));val session=TowerDefenseSession(seats,1,"loot",definition=d);assertTrue(session.act("a","deploy",mapOf("type" to "t","slot" to "4")).accepted);assertTrue(session.act("a","start_wave",emptyMap()).accepted);var now=System.currentTimeMillis();repeat(4){now+=2;session.tick(now)};assertTrue(session.finished);assertEquals("27",session.viewFor("a").fields["gold"]);val snapshot=session.snapshotState();val restored=TowerDefenseSession(seats,1,"loot",snapshot,d);repeat(4){now+=2;restored.tick(now)};assertEquals("27",restored.viewFor("a").fields["gold"])}
}
