package io.github.aristheg201.svhub.client.gui

import com.cobblemon.mod.common.api.pokemon.PokemonSpecies
import com.google.gson.JsonArray
import com.google.gson.JsonObject
import io.github.aristheg201.svhub.client.cobblemon.PokemonInfoProvider
import io.github.aristheg201.svhub.client.cobblemon.ClientPokemonRuntimeInfo
import io.github.aristheg201.svhub.client.cobblemon.PokemonModelRenderer
import io.github.aristheg201.svhub.client.cobblemon.PokemonView
import io.github.aristheg201.svhub.client.render.MiniMessageText
import io.github.aristheg201.svhub.client.render.PixelUi
import io.github.aristheg201.svhub.content.HubTheme
import net.minecraft.client.gui.Font
import net.minecraft.client.gui.GuiGraphics
import net.minecraft.network.chat.Component
import net.minecraft.resources.ResourceLocation
import kotlin.math.roundToInt

object PokemonDetailView {
    fun render(gui:GuiGraphics,font:Font,view:PokemonView,theme:HubTheme,width:Int,height:Int,yaw:Float,zoom:Float,scrollOffset:Int):Int{
        val left=modelLeft(width);val top=54;val modelWidth=modelWidth(width);val detailsX=left+modelWidth+18;val detailsWidth=maxOf(200,width-detailsX-left);val panelHeight=height-top-22;val p=theme.palette
        PixelUi.panel(gui,left,top,modelWidth,panelHeight,p.panel,p.accent);PixelUi.panel(gui,detailsX,top,detailsWidth,panelHeight,p.panel,p.accent)
        val species=ResourceLocation.tryParse(view.speciesId)?.let(PokemonSpecies::getByIdentifier)?:run{gui.drawString(font,"Species không còn tồn tại trong registry hiện tại.",detailsX+16,top+18,p.danger,false);return 0}
        val form=species.getForm(view.aspects);val info=PokemonInfoProvider.resolve(view);val runtimeInfo=ClientPokemonRuntimeInfo.getOrRequest(view)
        gui.fill(left,top,left+modelWidth,top+5,p.accent);MiniMessageText.drawCentered(gui,font,"<bold>${view.displayName}</bold>",left+modelWidth/2,top+13,p.text);gui.drawCenteredString(font,if(view.dexNumber>0)"#${view.dexNumber}" else "CUSTOM",left+modelWidth/2,top+29,p.accent2)
        val modelSize=minOf(modelWidth-26,panelHeight-128).coerceAtLeast(80);PokemonModelRenderer.render(gui,view,left+modelWidth/2,top+48+modelSize/2,modelSize,yaw,zoom);renderTypeChips(gui,font,form.types.map{it.name.replaceFirstChar(Char::uppercase)},left+12,top+54+modelSize,modelWidth-24,theme);gui.drawCenteredString(font,"Kéo: xoay  ·  Cuộn: zoom",left+modelWidth/2,top+panelHeight-25,p.mutedText)
        val x=detailsX+16;val innerWidth=detailsWidth-32;val viewportTop=top+8;val viewportBottom=top+panelHeight-8;val scroll=scrollOffset.coerceAtLeast(0);gui.enableScissor(detailsX+2,top+2,detailsX+detailsWidth-2,top+panelHeight-2);var y=top+14-scroll
        section(gui,font,x,y,innerWidth,"THÔNG TIN",theme);y+=31;y=line(gui,font,x,y,innerWidth,"Species ID",view.speciesId,theme);view.sourcePack?.takeIf(String::isNotBlank)?.let{y=line(gui,font,x,y,innerWidth,"Pack",it,theme)};if(view.aspects.isNotEmpty())y=wrappedValue(gui,font,x,y,innerWidth,"Aspect",view.aspects.sorted().joinToString(", "),theme);y=line(gui,font,x,y,innerWidth,"Height","${trim(form.height/10f)} m",theme);y=line(gui,font,x,y,innerWidth,"Weight","${trim(form.weight/10f)} kg",theme)
        info?.let{y=line(gui,font,x,y,innerWidth,"Catch Rate",it.catchRate.toString(),theme);y=line(gui,font,x,y,innerWidth,"Gender",it.gender,theme);y=line(gui,font,x,y,innerWidth,"Egg Group",it.eggGroups.ifEmpty{listOf("—")}.joinToString(" / "),theme);y=line(gui,font,x,y,innerWidth,"EXP Group",it.experienceGroup,theme);y=line(gui,font,x,y,innerWidth,"Base EXP",it.baseExperience.toString(),theme);y=line(gui,font,x,y,innerWidth,"Friendship",it.baseFriendship.toString(),theme)};y+=8
        info?.let{section(gui,font,x,y,innerWidth,"ABILITY",theme);y+=31;y=line(gui,font,x,y,innerWidth,"Ability",it.abilities.ifEmpty{listOf("—")}.joinToString(" / "),theme);y=line(gui,font,x,y,innerWidth,"Hidden",it.hiddenAbilities.ifEmpty{listOf("—")}.joinToString(" / "),theme);y+=8}
        section(gui,font,x,y,innerWidth,"BASE STATS",theme);y+=31;form.baseStats.entries.sortedBy{statOrder(it.key.showdownId)}.forEach{(stat,value)->y=statLine(gui,font,x,y,innerWidth,stat.displayName.string,value,theme)};info?.let{y=line(gui,font,x,y+2,innerWidth,"BST",it.bst.toString(),theme)};info?.takeIf{it.evYield.isNotEmpty()}?.let{y=wrappedValue(gui,font,x,y,innerWidth,"EV Yield",it.evYield.joinToString(" · "),theme)};y+=8
        info?.let{section(gui,font,x,y,innerWidth,"TIẾN HÓA & FORM",theme);y+=31;y=line(gui,font,x,y,innerWidth,"Pre-evolution",runtimeInfo?.stringOrNull("preEvolution")?:it.preEvolution?:"—",theme);val ev=runtimeInfo?.getAsJsonArray("evolutions");if(ev!=null&&ev.size()>0)y=renderEvolutionDetails(gui,font,x,y,innerWidth,ev,theme)else y=wrappedValue(gui,font,x,y,innerWidth,"Evolves to",it.evolutions.ifEmpty{listOf("—")}.joinToString(", "),theme);if(it.forms.isNotEmpty())y=wrappedValue(gui,font,x,y,innerWidth,"Forms",it.forms.joinToString(" · "),theme);y+=8}
        section(gui,font,x,y,innerWidth,"SPAWN & BIOME",theme);y+=31;if(runtimeInfo==null){gui.drawString(font,"Đang tải dữ liệu spawn từ server…",x,y,p.mutedText,false);y+=18}else{val sp=runtimeInfo.getAsJsonArray("spawns")?:JsonArray();when{runtimeInfo.boolOrFalse("truncated")->{gui.drawString(font,"Spawn payload đã được rút gọn vì quá lớn.",x,y,p.mutedText,false);y+=18};sp.size()==0->{gui.drawString(font,"Không có natural spawn trong pool hiện tại.",x,y,p.mutedText,false);y+=18};else->y=SpawnEcologyRenderer.render(gui,font,x,y,innerWidth,sp,runtimeInfo.intOrZero("spawnCount"),theme)}};y+=8
        info?.let{section(gui,font,x,y,innerWidth,"MOVESET",theme);y+=31;gui.drawString(font,"Level ${it.levelMoves.size} · TM ${it.tmMoveCount} · Egg ${it.eggMoveCount} · Tutor ${it.tutorMoveCount} · Other ${it.otherMoveCount}",x,y,p.mutedText,false);y+=16;it.levelMoves.take(24).forEach{move->gui.fill(x,y+3,x+3,y+7,p.accent2);gui.drawString(font,font.plainSubstrByWidth(move,innerWidth-14),x+9,y,p.text,false);y+=12};if(it.levelMoves.size>24){gui.drawString(font,"+ ${it.levelMoves.size-24} level-up moves khác",x+9,y,p.mutedText,false);y+=12};y+=8}
        info?.takeIf{it.drops.isNotEmpty()}?.let{section(gui,font,x,y,innerWidth,"DROPS",theme);y+=31;it.drops.take(10).forEach{drop->gui.fill(x,y+3,x+3,y+7,p.accent);gui.drawString(font,font.plainSubstrByWidth(drop,innerWidth-14),x+9,y,p.text,false);y+=12};if(it.drops.size>10){gui.drawString(font,"+ ${it.drops.size-10} drops khác",x+9,y,p.mutedText,false);y+=12};y+=8}
        info?.takeIf{it.pokedex.isNotEmpty()}?.let{section(gui,font,x,y,innerWidth,"POKÉDEX",theme);y+=31;it.pokedex.take(4).forEach{paragraph->MiniMessageText.split(font,paragraph,innerWidth).take(8).forEach{text->gui.drawString(font,text,x,y,p.text,false);y+=12};y+=5}}
        view.wikiPage?.let{wiki->y+=4;MiniMessageText.draw(gui,font,"<color:#2E7168>Server wiki:</color> $wiki",x,y,p.accent);y+=14};gui.disableScissor()
        val contentHeight=(y+scroll)-(top+14);val viewportHeight=viewportBottom-viewportTop-16;val maxScroll=(contentHeight-viewportHeight).coerceAtLeast(0);if(maxScroll>0){val track=panelHeight-16;val bar=((viewportHeight.toFloat()/contentHeight.coerceAtLeast(1))*track).roundToInt().coerceAtLeast(24);val travel=track-bar;val by=top+8+((scroll.coerceAtMost(maxScroll).toFloat()/maxScroll)*travel).roundToInt();gui.fill(detailsX+detailsWidth-7,top+8,detailsX+detailsWidth-4,top+panelHeight-8,PixelUi.withAlpha(p.mutedText,45));gui.fill(detailsX+detailsWidth-7,by,detailsX+detailsWidth-4,by+bar,p.accent)};return maxScroll
    }
    fun isModelArea(width:Int,mouseX:Double,mouseY:Double,height:Int):Boolean{val left=modelLeft(width);return mouseX>=left&&mouseX<left+modelWidth(width)&&mouseY>=54&&mouseY<height-22}
    private fun renderTypeChips(gui:GuiGraphics,font:Font,types:List<String>,x:Int,y:Int,width:Int,theme:HubTheme){if(types.isEmpty())return;val gap=5;val total=types.sumOf{font.width(it)+18}+gap*(types.size-1);var cx=x+((width-total).coerceAtLeast(0)/2);types.forEachIndexed{i,type->val w=font.width(type)+18;gui.fill(cx,y,cx+w,y+20,if(i==0)theme.palette.accent else theme.palette.accent2);gui.drawCenteredString(font,type,cx+w/2,y+7,0xFFFFFFFF.toInt());cx+=w+gap}}
    private fun section(gui:GuiGraphics,font:Font,x:Int,y:Int,width:Int,title:String,theme:HubTheme){PixelUi.sectionBand(gui,x,y,width,24,theme);gui.drawString(font,title,x+11,y+8,theme.palette.accent,true)}
    private fun line(gui:GuiGraphics,font:Font,x:Int,y:Int,width:Int,label:String,value:String,theme:HubTheme):Int{val lw=minOf(102,width/3);gui.drawString(font,"$label:",x,y,theme.palette.mutedText,false);gui.drawString(font,font.plainSubstrByWidth(value,width-lw),x+lw,y,theme.palette.text,false);return y+14}
    private fun statLine(gui:GuiGraphics,font:Font,x:Int,y:Int,width:Int,label:String,value:Int,theme:HubTheme):Int{val lw=minOf(82,width/4);val bx=x+lw+28;val bw=(width-lw-28).coerceAtLeast(40);gui.drawString(font,label,x,y+1,theme.palette.mutedText,false);gui.drawString(font,value.toString(),x+lw,y+1,theme.palette.text,true);gui.fill(bx,y+3,bx+bw,y+9,PixelUi.withAlpha(theme.palette.mutedText,35));val fill=((value.coerceIn(0,255)/255f)*bw).roundToInt().coerceAtLeast(if(value>0)2 else 0);gui.fill(bx,y+3,bx+fill,y+9,if(value>=100)theme.palette.accent2 else theme.palette.accent);return y+14}
    private fun wrappedValue(gui:GuiGraphics,font:Font,x:Int,y:Int,width:Int,label:String,value:String,theme:HubTheme):Int{val lw=minOf(102,width/3);gui.drawString(font,"$label:",x,y,theme.palette.mutedText,false);var cy=y;font.split(Component.literal(value),width-lw).take(6).forEach{text->gui.drawString(font,text,x+lw,cy,theme.palette.text,false);cy+=12};return maxOf(y+14,cy)}
    private fun renderEvolutionDetails(gui:GuiGraphics,font:Font,x:Int,startY:Int,width:Int,evolutions:JsonArray,theme:HubTheme):Int{var y=startY;val p=theme.palette;val count=minOf(12,evolutions.size());for(i in 0 until count){val e=evolutions[i].asJsonObject;val to=e.stringOrNull("to")?:"Unknown";val variant=e.stringOrNull("variant")?.takeIf(String::isNotBlank)?:"evolution";val aspects=e.getAsJsonArray("aspects")?.strings().orEmpty();val title=buildString{append("→ ").append(prettyId(to));if(aspects.isNotEmpty())append(" [").append(aspects.joinToString(", "){prettyId(it)}).append(']');append(" • ").append(prettyId(variant))};gui.drawString(font,font.plainSubstrByWidth(title,width),x,y,p.accent2,false);y+=13;val req=e.getAsJsonArray("requirements")?.strings().orEmpty();if(req.isEmpty()){gui.drawString(font,"  Điều kiện: —",x,y,p.mutedText,false);y+=12}else req.take(8).forEach{r->font.split(Component.literal("  • ${prettyRequirement(r)}"),width-6).take(3).forEach{text->gui.drawString(font,text,x+4,y,p.text,false);y+=12}};e.stringOrNull("context")?.takeIf(String::isNotBlank)?.let{y=wrappedValue(gui,font,x+4,y,width-4,"Context",prettyId(it),theme)};if(e.boolOrFalse("consumeHeldItem")){gui.drawString(font,"  • Consumes held item",x+4,y,p.mutedText,false);y+=12};y+=5};if(evolutions.size()>count){gui.drawString(font,"+ ${evolutions.size()-count} evolution routes khác",x,y,p.mutedText,false);y+=12};return y}
    private fun renderSpawnDetails(gui:GuiGraphics,font:Font,x:Int,startY:Int,width:Int,spawns:JsonArray,total:Int,theme:HubTheme):Int{var y=startY;val p=theme.palette;val count=minOf(14,spawns.size());for(i in 0 until count){val s=spawns[i].asJsonObject;val bucket=prettyId(s.stringOrNull("bucket")?:"common");val level=s.stringOrNull("level")?:"1-100";val context=prettyId(s.stringOrNull("context")?:"grounded");val weight=s.get("weight")?.let{runCatching{it.asDouble}.getOrNull()};val header=buildString{append(bucket).append(" • Lv.").append(level).append(" • ").append(context);weight?.let{append(" • W ").append(trim(it.toFloat()))}};gui.drawString(font,font.plainSubstrByWidth(header,width),x,y,p.accent2,false);y+=13;val form=s.stringOrNull("form").orEmpty();val aspects=s.getAsJsonArray("aspects")?.strings().orEmpty();val ft=buildList{if(form.isNotBlank()&&!form.equals("Normal",true))add(prettyId(form));addAll(aspects.map(::prettyId))}.distinct();if(ft.isNotEmpty())y=wrappedValue(gui,font,x+4,y,width-4,"Form",ft.joinToString(" · "),theme);s.stringOrNull("herd")?.takeIf(String::isNotBlank)?.let{y=wrappedValue(gui,font,x+4,y,width-4,"Herd",prettyId(it),theme)};val conditions=s.getAsJsonArray("conditions")?.strings().orEmpty();if(conditions.isEmpty()){gui.drawString(font,"  Điều kiện: mặc định",x+4,y,p.mutedText,false);y+=12}else conditions.take(12).forEach{c->font.split(Component.literal("  • $c"),width-6).take(3).forEach{text->gui.drawString(font,text,x+4,y,p.text,false);y+=12}};y+=5};val real=maxOf(total,spawns.size());if(real>count){gui.drawString(font,"+ ${real-count} spawn entries khác",x,y,p.mutedText,false);y+=12};return y}
    private fun JsonObject.stringOrNull(k:String)=get(k)?.let{runCatching{it.asString}.getOrNull()};private fun JsonObject.intOrZero(k:String)=get(k)?.let{runCatching{it.asInt}.getOrNull()}?:0;private fun JsonObject.boolOrFalse(k:String)=get(k)?.let{runCatching{it.asBoolean}.getOrNull()}?:false;private fun JsonArray.strings()=(0 until size()).mapNotNull{i->runCatching{get(i).asString}.getOrNull()?.takeIf(String::isNotBlank)}
    private fun prettyRequirement(v:String)=v.replace(" • "," · ").replace(Regex("([a-z])([A-Z])"),"$1 $2").replace('_',' ');private fun prettyId(v:String)=v.substringAfterLast(':').replace('_',' ').replace('-',' ').split(' ').filter(String::isNotBlank).joinToString(" "){it.replaceFirstChar(Char::uppercase)}
    private fun statOrder(id:String)=when(id.lowercase()){ "hp"->0;"attack"->1;"defense"->2;"special_attack","specialattack","spatk"->3;"special_defense","specialdefense","spdef"->4;"speed"->5;else->10 }
    private fun modelLeft(width:Int)=maxOf(18,width/12);private fun modelWidth(width:Int)=minOf(260,width/2-28).coerceAtLeast(150);private fun trim(value:Float)=if(value%1f==0f)value.toInt().toString() else "%.1f".format(value)
}
