package io.github.aristheg201.svarcade.network

import io.github.aristheg201.svarcade.SVArcade
import io.github.aristheg201.svarcade.SVArcadeRuntime
import io.github.aristheg201.svarcade.action.ServerActionDispatcher
import io.github.aristheg201.svarcade.content.*
import io.github.aristheg201.svarcade.permission.EditAuthorization
import io.github.aristheg201.svarcade.permission.SVArcadePermissions
import io.github.aristheg201.svarcade.server.EnvironmentManifest
import io.github.aristheg201.svarcade.server.HubPlaceholderResolver
import io.github.aristheg201.svarcade.server.PokemonRuntimeInfoService
import io.github.aristheg201.svarcade.server.SnapshotProjector
import io.github.aristheg201.svarcade.util.Compression
import net.fabricmc.fabric.api.networking.v1.PayloadTypeRegistry
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking
import net.minecraft.server.level.ServerPlayer
import java.util.UUID
import java.util.concurrent.*
import java.util.concurrent.atomic.AtomicInteger

object SVArcadeNetwork {
    private data class ClientState(val protocol:Int,val modIds:Set<String>)
    private data class SnapshotRateKey(val playerId:UUID,val editor:Boolean)
    private data class EditorSession(val baseRevision:Long,val baseline:HubContent,val createdAtEpochMs:Long)
    private val clients=ConcurrentHashMap<UUID,ClientState>();private val assemblers=ConcurrentHashMap<UUID,ChunkAssembler>();private val snapshotRequests=ConcurrentHashMap<SnapshotRateKey,Long>();private val editorSessions=ConcurrentHashMap<UUID,EditorSession>();private val pendingSnapshotJobs=ConcurrentHashMap.newKeySet<SnapshotRateKey>();private val pendingEditorDecodes=ConcurrentHashMap.newKeySet<UUID>();private val codecThreadCounter=AtomicInteger()
    private val codecExecutor=ThreadPoolExecutor(1,2,30L,TimeUnit.SECONDS,ArrayBlockingQueue(CODEC_QUEUE_CAPACITY),{task->Thread(task,"SVArcade-Codec-${codecThreadCounter.incrementAndGet()}").apply{isDaemon=true;priority=Thread.NORM_PRIORITY-1}},ThreadPoolExecutor.AbortPolicy()).apply{allowCoreThreadTimeOut(true)}

    fun registerCommon(){
        PayloadTypeRegistry.playS2C().register(HubHelloS2C.TYPE,HubHelloS2C.CODEC);PayloadTypeRegistry.playS2C().register(HubSnapshotChunkS2C.TYPE,HubSnapshotChunkS2C.CODEC);PayloadTypeRegistry.playS2C().register(HubOpenS2C.TYPE,HubOpenS2C.CODEC);PayloadTypeRegistry.playS2C().register(HubEditorResultS2C.TYPE,HubEditorResultS2C.CODEC);PayloadTypeRegistry.playS2C().register(PokemonRuntimeInfoS2C.TYPE,PokemonRuntimeInfoS2C.CODEC)
        PayloadTypeRegistry.playC2S().register(HubClientManifestC2S.TYPE,HubClientManifestC2S.CODEC);PayloadTypeRegistry.playC2S().register(HubActionC2S.TYPE,HubActionC2S.CODEC);PayloadTypeRegistry.playC2S().register(HubRequestSnapshotC2S.TYPE,HubRequestSnapshotC2S.CODEC);PayloadTypeRegistry.playC2S().register(HubEditorChunkC2S.TYPE,HubEditorChunkC2S.CODEC);PayloadTypeRegistry.playC2S().register(PokemonRuntimeInfoC2S.TYPE,PokemonRuntimeInfoC2S.CODEC)
        ServerPlayNetworking.registerGlobalReceiver(HubClientManifestC2S.TYPE){p,c->c.server().execute{val player=c.player();clients[player.uuid]=ClientState(p.protocol,EnvironmentManifest.modIds(p.clientManifest));if(p.protocol==HUB_PROTOCOL_VERSION&&SVArcadeRuntime.store.isReady()&&SVArcadePermissions.has(player,SVArcadePermissions.OPEN,0)&&p.cachedRevision!=SVArcadeRuntime.store.snapshot().revision&&allowSnapshotRequest(player,false))sendSnapshot(player,false)}}
        ServerPlayNetworking.registerGlobalReceiver(HubActionC2S.TYPE){p,c->c.server().execute{ServerActionDispatcher.execute(c.player(),p.actionId)}}
        ServerPlayNetworking.registerGlobalReceiver(HubRequestSnapshotC2S.TYPE){p,c->c.server().execute{val player=c.player();sendHello(player);if(!SVArcadeRuntime.store.isReady()){sendEditorResult(player,false,SVArcadeRuntime.store.snapshot().revision,"SVArcade đang tải dữ liệu, hãy thử lại ngay sau đó.");return@execute};val editor=p.editor&&SVArcadePermissions.has(player,SVArcadePermissions.EDITOR,2);if(SVArcadePermissions.has(player,SVArcadePermissions.OPEN,0)&&allowSnapshotRequest(player,editor))sendSnapshot(player,editor)}}
        ServerPlayNetworking.registerGlobalReceiver(HubEditorChunkC2S.TYPE){p,c->c.server().execute{receiveEditorChunk(c.player(),p)}}
        ServerPlayNetworking.registerGlobalReceiver(PokemonRuntimeInfoC2S.TYPE){p,c->c.server().execute{PokemonRuntimeInfoService.request(c.player(),p)}}
    }
    fun clientHasMod(player:ServerPlayer,modId:String)=clients[player.uuid]?.modIds?.contains(modId)==true
    fun onJoin(player:ServerPlayer){sendHello(player)}
    fun broadcastHello(){editorSessions.clear();SVArcadeRuntime.server?.playerList?.players?.forEach(::sendHello)}
    private fun sendHello(player:ServerPlayer){val open=SVArcadePermissions.has(player,SVArcadePermissions.OPEN,0);val edit=open&&SVArcadePermissions.has(player,SVArcadePermissions.EDITOR,2);val snapshot=SVArcadeRuntime.store.snapshot();val cacheable=!HubPlaceholderResolver.hasDynamicPlaceholders(snapshot.content);ServerPlayNetworking.send(player,HubHelloS2C(HUB_PROTOCOL_VERSION,snapshot.revision,open&&SVArcadeRuntime.store.isReady(),edit&&SVArcadeRuntime.store.isReady(),cacheable,EnvironmentManifest.publicAdvertisement(setOf("player-hub","minimessage","placeholder-api")).toJson()))}
    fun onDisconnect(player:ServerPlayer){clients.remove(player.uuid);assemblers.remove(player.uuid)?.clear();editorSessions.remove(player.uuid);snapshotRequests.keys.removeIf{it.playerId==player.uuid};pendingSnapshotJobs.removeIf{it.playerId==player.uuid};pendingEditorDecodes.remove(player.uuid);ServerActionDispatcher.clear(player);PokemonRuntimeInfoService.onDisconnect(player.uuid)}
    fun open(player:ServerPlayer,page:String,editor:Boolean){
        if(!SVArcadePermissions.has(player,SVArcadePermissions.OPEN,0))return
        // Send the open intent even while the store is warming up. The client keeps the
        // route pending and the normal hello/snapshot handshake fulfills it once ready.
        // Previously /hub could be swallowed with no packet at all.
        ServerPlayNetworking.send(player,HubOpenS2C(page,editor&&SVArcadePermissions.has(player,SVArcadePermissions.EDITOR,2)))
        if(!SVArcadeRuntime.store.isReady())sendHello(player)
    }
    fun sendSnapshot(player:ServerPlayer,editor:Boolean){if(!SVArcadeRuntime.store.isReady())return;val server=SVArcadeRuntime.server?:return;val key=SnapshotRateKey(player.uuid,editor);if(!pendingSnapshotJobs.add(key))return;val clientMods=clients[player.uuid]?.modIds.orEmpty();val projected=SnapshotProjector.forPlayer(SVArcadeRuntime.store.snapshot().content,player,editor,clientMods);if(editor)editorSessions[player.uuid]=EditorSession(projected.revision,projected,System.currentTimeMillis());val playerId=player.uuid;try{codecExecutor.execute{val result=runCatching{Compression.chunks(Compression.encodeUtf8(HubContentCodec.encode(projected)))};server.execute{pendingSnapshotJobs.remove(key);val live=server.playerList.getPlayer(playerId)?:return@execute;result.onSuccess{chunks->if(SVArcadeRuntime.store.snapshot().revision!=projected.revision){if(editor)editorSessions.remove(playerId);sendSnapshot(live,editor);return@onSuccess};val transfer=ThreadLocalRandom.current().nextLong();chunks.forEachIndexed{i,ch->ServerPlayNetworking.send(live,HubSnapshotChunkS2C(transfer,projected.revision,editor,i,chunks.size,ch))}}.onFailure{e->if(editor)editorSessions.remove(playerId);SVArcade.LOGGER.warn("Failed to encode SVArcade snapshot for {}",playerId,e);if(editor)sendEditorResult(live,false,SVArcadeRuntime.store.snapshot().revision,"Không thể chuẩn bị editor snapshot.")}}}}catch(_:RejectedExecutionException){pendingSnapshotJobs.remove(key);if(editor)editorSessions.remove(player.uuid);SVArcade.LOGGER.warn("SVArcade codec queue full while preparing snapshot for {}",player.uuid);if(editor)sendEditorResult(player,false,SVArcadeRuntime.store.snapshot().revision,"SVArcade đang bận xử lý dữ liệu; hãy thử lại.")}}
    fun broadcastPlayerSnapshots(){if(!SVArcadeRuntime.store.isReady())return;SVArcadeRuntime.server?.playerList?.players?.forEach{if(SVArcadePermissions.has(it,SVArcadePermissions.OPEN,0))sendSnapshot(it,false)}}
    private fun allowSnapshotRequest(player:ServerPlayer,editor:Boolean):Boolean{val now=System.currentTimeMillis();val key=SnapshotRateKey(player.uuid,editor);val prev=snapshotRequests[key];if(prev!=null&&now-prev<SNAPSHOT_REQUEST_COOLDOWN_MS)return false;snapshotRequests[key]=now;return true}
    private fun receiveEditorChunk(player:ServerPlayer,payload:HubEditorChunkC2S){if(!SVArcadeRuntime.store.isReady()){sendEditorResult(player,false,SVArcadeRuntime.store.snapshot().revision,"SVArcade chưa sẵn sàng.");return};if(!SVArcadePermissions.has(player,SVArcadePermissions.EDITOR,2)||!SVArcadePermissions.has(player,SVArcadePermissions.EDITOR_PUBLISH,2))return;val joined=runCatching{assemblers.computeIfAbsent(player.uuid){ChunkAssembler()}.accept(payload.transferId,payload.index,payload.total,payload.chunk)}.getOrElse{sendEditorResult(player,false,SVArcadeRuntime.store.snapshot().revision,it.message?:"Invalid editor transfer");return}?:return;val playerId=player.uuid;if(!pendingEditorDecodes.add(playerId)){sendEditorResult(player,false,SVArcadeRuntime.store.snapshot().revision,"Một publish khác đang được xử lý.");return};val server=SVArcadeRuntime.server?:run{pendingEditorDecodes.remove(playerId);return};val baseRevision=payload.baseRevision;try{codecExecutor.execute{val decoded=runCatching{HubContentCodec.decode(Compression.decodeUtf8(joined))};server.execute{pendingEditorDecodes.remove(playerId);val live=server.playerList.getPlayer(playerId)?:return@execute;decoded.onSuccess{processEditorCandidate(live,baseRevision,it)}.onFailure{sendEditorResult(live,false,SVArcadeRuntime.store.snapshot().revision,it.message?:"Decode failed")}}}}catch(_:RejectedExecutionException){pendingEditorDecodes.remove(playerId);sendEditorResult(player,false,SVArcadeRuntime.store.snapshot().revision,"SVArcade đang bận xử lý dữ liệu; hãy thử lại.")}}
    private fun processEditorCandidate(player:ServerPlayer,baseRevision:Long,candidate:HubContent){val current=SVArcadeRuntime.store.snapshot().content;val publishCandidate=if(SVArcadePermissions.has(player,SVArcadePermissions.EDITOR_ALL,2))candidate else{val session=editorSessions[player.uuid];if(session==null||session.baseRevision!=baseRevision){sendEditorResult(player,false,current.revision,"Editor session không còn hợp lệ; hãy tải lại editor.");return};if(System.currentTimeMillis()-session.createdAtEpochMs>EDITOR_SESSION_TTL_MS){editorSessions.remove(player.uuid,session);sendEditorResult(player,false,current.revision,"Editor session đã hết hạn; hãy tải lại editor.");return};val merge=ScopedEditMerge.merge(current,session.baseline,candidate,ScopedEditPermissions(SVArcadePermissions.has(player,SVArcadePermissions.EDITOR_SETTINGS,2),SVArcadePermissions.has(player,SVArcadePermissions.EDITOR_ASSETS,2),SVArcadePermissions.has(player,SVArcadePermissions.EDITOR_CREATE,2)){id->SVArcadePermissions.has(player,SVArcadePermissions.pageEditor(id),2)});if(!merge.ok){sendEditorResult(player,false,current.revision,merge.error?:"Scoped editor merge failed");return};requireNotNull(merge.content)};val reason=EditAuthorization.rejectReason(player,current,publishCandidate);if(reason!=null){sendEditorResult(player,false,current.revision,reason);return};val playerId=player.uuid;val playerName=player.gameProfile.name;SVArcadeRuntime.store.commitAsync(baseRevision,publishCandidate).whenComplete{result,error->SVArcadeRuntime.server?.execute{val live=SVArcadeRuntime.server?.playerList?.getPlayer(playerId)?:return@execute;if(error!=null){SVArcade.LOGGER.warn("Hub publish failed: player={} uuid={} baseRevision={} currentRevision={}",playerName,playerId,baseRevision,SVArcadeRuntime.store.snapshot().revision,error);sendEditorResult(live,false,SVArcadeRuntime.store.snapshot().revision,error.message?:"Publish failed");return@execute};sendEditorResult(live,result.ok,result.revision,result.message);if(result.ok){editorSessions.remove(playerId);broadcastPlayerSnapshots()}}}}
    private fun sendEditorResult(player:ServerPlayer,ok:Boolean,revision:Long,message:String){ServerPlayNetworking.send(player,HubEditorResultS2C(ok,revision,message.take(512)))}
    private const val SNAPSHOT_REQUEST_COOLDOWN_MS=750L;private const val EDITOR_SESSION_TTL_MS=15*60*1000L;private const val CODEC_QUEUE_CAPACITY=32
}
