package vn.worldcomesalive.civilization;
import vn.worldcomesalive.model.LivingWorld.*;
import vn.worldcomesalive.server.*;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.util.Identifier;
import java.util.*;
public final class CivilizationManager {
    private final WorldSimulation sim;
    public CivilizationManager(WorldSimulation sim){this.sim=sim;for(var s:sim.state.settlements.values())if(s.ready)initialize(s);}
    public void initialize(Settlement s){CivilizationRules.initialize(sim.state,s);TradeNetwork.initialize(sim.state,s);}
    public void tick(){if(sim.state.clock%100!=0)return;if(sim.state.clock%100==0)TradeNetwork.tick(sim.state);ContractDirector.tick(sim.state);for(var s:sim.state.settlements.values())if(s.ready){var g=sim.state.civilization.governments.get(s.id);if(g==null){initialize(s);g=sim.state.civilization.governments.get(s.id);}CivilizationRules.succession(sim.state,s,g);CivilizationRules.metrics(sim.state,s,g);Building bakery=s.service("bakery");if(bakery!=null){Npc baker=s.residents.stream().map(sim::npc).filter(n->n.workplace.equals(bakery.id)&&!n.lifeStage.equals("deceased")).findFirst().orElse(null);if(baker!=null)CivilizationRules.shortage(sim.state,s,bakery,baker);}long day=sim.state.clock/24000;if(g.lastTaxDay>=0&&g.lastTaxDay<day){for(var b:s.buildings.values()){long tax=(long)(b.money*g.salesTax);if(tax>0){b.money-=tax;g.treasury+=tax;sim.state.transact(b.id,s.id+":treasury","business tax",1,tax,"local business tax");}}}g.lastTaxDay=day;}for(var c:sim.state.civilization.contracts.values())if(Set.of("OFFERED","ACTIVE").contains(c.status)&&sim.state.clock>=c.deadline){c.status="EXPIRED";sim.state.settlements.get(c.settlement).buildings.get(c.business).money+=c.reward;sim.state.transact(c.id.toString(),c.business,"escrow refund",1,c.reward,"expired contract");}}
    public List<String> actions(Npc n,UUID player,boolean board,boolean journal){List<String> list=new ArrayList<>();for(var c:sim.state.civilization.contracts.values()){boolean own=player.equals(c.assignee);boolean visible=journal?own:board?c.settlement.equals(n.settlement):c.requester.equals(n.id);if(!visible)continue;list.add("details:"+c.id);if(!journal&&c.status.equals("OFFERED"))list.add("accept:"+c.id);if(!journal&&!board&&own&&c.status.equals("ACTIVE")&&c.requester.equals(n.id))list.add("fulfill:"+c.id);}return list;}
    public List<InteractionPackets.MenuRow> contracts(Npc n,UUID player,boolean board,boolean journal){return sim.state.civilization.contracts.values().stream().filter(c->journal?player.equals(c.assignee):board?c.settlement.equals(n.settlement):c.requester.equals(n.id)).map(c->new InteractionPackets.MenuRow(c.id.toString(),c.title+" · "+c.status+" · "+c.progress+"/"+c.required,"Contracts",c.reward,c.required-c.progress)).toList();}
    public String requestText(Npc n){return sim.state.civilization.contracts.values().stream().filter(c->c.requester.equals(n.id)&&c.status.equals("OFFERED")).findFirst().map(c->c.description+" "+c.knownInformation).orElse("I have no outstanding requests. Work appears when there is a real shortage or local problem.");}
    public String contractAction(ServerPlayerEntity p,Npc owner,String action){String[] parts=action.split(":",2);CivilizationState.Contract c;try{c=sim.state.civilization.contracts.get(UUID.fromString(parts[1]));}catch(RuntimeException invalid){return "Unknown contract.";}if(c==null)return "Unknown contract.";
        if(parts[0].equals("details"))return c.description+"\nRequester: "+sim.npc(c.requester).name+"\nKnown information: "+c.knownInformation+(c.route.isBlank()?"":"\nTrade route: "+c.route)+"\nLocation: "+c.locationQuality+" · "+c.target+"\nReward: "+c.reward+" crowns. Deadline in "+Math.max(0,c.deadline-sim.state.clock)+" ticks. Status: "+c.status;
        if(parts[0].equals("accept"))return CivilizationRules.accept(c,p.getUuid(),sim.state.clock)?"Contract accepted. Deliver "+c.required+" "+c.item.replace("minecraft:","").replace("_"," ")+" to "+sim.npc(c.requester).name+". You can review it in your journal.":"That contract is no longer available.";
        if(!c.requester.equals(owner.id)||!p.getUuid().equals(c.assignee)||!c.status.equals("ACTIVE"))return "This requester cannot receive your delivery.";int required=c.required-c.progress,have=0;var item=Registries.ITEM.get(Identifier.of(c.item));for(int i=0;i<p.getInventory().size();i++)if(p.getInventory().getStack(i).isOf(item))have+=p.getInventory().getStack(i).getCount();if(have<required)return "Bring "+required+" actual wheat. You currently carry "+have+".";long paid=CivilizationRules.deliver(sim.state,c,p.getUuid(),required);if(paid==0)return "The contract expired.";int remaining=required;for(int i=0;i<p.getInventory().size()&&remaining>0;i++){ItemStack stack=p.getInventory().getStack(i);if(stack.isOf(item)){int take=Math.min(remaining,stack.getCount());stack.decrement(take);remaining-=take;}}var delivered=sim.state.settlements.get(c.settlement).buildings.get(c.business);if(delivered!=null&&delivered.type.equals("bakery"))sim.domestic.work(sim.state.settlements.get(c.settlement),delivered,"baker",.2);return "Delivery complete. "+(delivered==null?"The destination":delivered.type.replace("_"," "))+" received "+required+" "+c.item.replace("minecraft:","").replace("_"," ")+" through the real economy. You earned "+paid+" crowns.";
    }
    public String status(Npc n){var s=sim.state.settlements.get(n.settlement);var g=sim.state.civilization.governments.get(s.id);if(g==null)return "Settlement administration is initializing.";StringBuilder text=new StringBuilder(s.name+" · "+g.type+"\nLeader: "+(g.leader==null?"Succession in progress":sim.npc(g.leader).name)+"\n");g.roles.forEach((role,id)->text.append(role).append(": ").append(sim.npc(id).name).append("\n"));g.metrics.forEach((key,value)->text.append(key).append(": ").append(Math.round(value)).append("\n"));text.append("Local laws:\n");g.laws.forEach(l->text.append("• ").append(l).append("\n"));return text.toString();}
    public List<String> bountyActions(Npc n){List<String> out=new ArrayList<>();for(var b:BountySystem.listings(sim.state,n.settlement))out.add("bounty:"+b.id);return out;}
    public List<InteractionPackets.MenuRow> bounties(Npc n){return BountySystem.listings(sim.state,n.settlement).stream().map(b->{Npc target=sim.state.npcs.get(b.target);String name=target==null?"Unknown fugitive":target.name;return new InteractionPackets.MenuRow(b.id.toString(),name+" · "+b.requirement+" · "+b.status,"Bounties",b.reward,b.crimes.size());}).toList();}
    public String bountyText(Npc n){var list=BountySystem.listings(sim.state,n.settlement);if(list.isEmpty())return "There are no active bounties in this jurisdiction.";var top=list.getFirst();return "The watch currently has "+list.size()+" active warrant"+(list.size()==1?"":"s")+". Highest priority: "+BountySystem.describe(sim.state,top);}
    public String bountyAction(Npc owner,String action){if(!action.startsWith("bounty:"))return "Unknown bounty.";try{var b=sim.state.civilization.bounties.get(UUID.fromString(action.substring("bounty:".length())));if(b==null||!b.jurisdiction.equals(owner.settlement))return "That warrant is not registered here.";return BountySystem.describe(sim.state,b);}catch(RuntimeException invalid){return "Unknown bounty.";}}
    public boolean canRestrain(Npc target){var bounty=BountySystem.activeForTarget(sim.state,target.id).orElse(null);if(bounty==null||bounty.requirement.equals("DEAD_ONLY"))return false;var entity=sim.world.getEntity(target.id);return target.relationship(bounty.target).fear>=50||(entity instanceof net.minecraft.entity.LivingEntity living&&living.getHealth()<=Math.max(4f,living.getMaxHealth()*.3f));}
    public String restrain(ServerPlayerEntity hunter,Npc target){var bounty=BountySystem.activeForTarget(sim.state,target.id).orElse(null);if(bounty==null)return "No active warrant covers this person.";var entity=sim.world.getEntity(target.id);boolean subdued=entity instanceof net.minecraft.entity.LivingEntity living&&living.getHealth()<=Math.max(4f,living.getMaxHealth()*.3f);if(!subdued&&target.relationship(hunter.getUuid()).fear<50)return "The target is not subdued and refuses to surrender.";long reward=BountySystem.captured(sim.state,bounty.id,hunter.getUuid());if(reward<=0)return "This warrant can no longer be resolved.";Settlement jurisdiction=sim.state.settlements.get(bounty.jurisdiction);Building guard=jurisdiction==null?null:jurisdiction.service("civic");if(guard==null&&jurisdiction!=null)guard=jurisdiction.service("leader_hall");if(guard!=null){target.location=guard.point(Marker.CUSTOMER_POINT);target.home=guard.id;}target.activity="in custody";target.goal="imprisoned";target.plan.clear();target.travel=null;target.version++;if(entity!=null)entity.discard();return "Target captured alive. The "+bounty.jurisdiction+" authority paid "+reward+" crowns.";}
}
