package vn.worldcomesalive.civilization;
import vn.worldcomesalive.model.LivingWorld;
import vn.worldcomesalive.model.LivingWorld.*;
import vn.worldcomesalive.world.SettlementBootstrap;
import vn.worldcomesalive.domestic.DomesticContent;
import java.util.*;
/** Deterministic government assignment and transactions operate on the existing world records. */
public final class CivilizationRules {
    public static void initialize(LivingWorld w,Settlement s){var g=w.civilization.governments.computeIfAbsent(s.id,k->new CivilizationState.Government());g.type=s.archetype.contains("hamlet")?"ELDER":s.archetype.contains("outpost")?"MILITARY":"COUNCIL";succession(w,s,g);for(Building b:s.buildings.values())if(b.beds>0){UUID id=SettlementBootstrap.uuid(b.id+"property");var p=w.civilization.properties.computeIfAbsent(id,k->new CivilizationState.Property());p.id=id;p.settlement=s.id;p.building=b.id;p.type=b.type.equals("farm")?"FARMHOUSE":b.type.equals("cottage")?"COTTAGE":b.type.equals("tavern")?"TAVERN":"WORKSHOP";p.value=Math.round(180+b.width*b.depth*b.wealth*3);p.plots.clear();s.fields.values().stream().filter(f->f.building.equals(b.id)).forEach(f->p.plots.add(f.id.toString()));}metrics(w,s,g);}
    public static void succession(LivingWorld w,Settlement s,CivilizationState.Government g){if(g.leader!=null&&alive(w.npcs.get(g.leader)))return;UUID former=g.leader;Npc next=g.deputy==null?null:w.npcs.get(g.deputy);if(!alive(next))next=s.residents.stream().map(w.npcs::get).filter(CivilizationRules::alive).filter(n->n.age>=18).max(Comparator.comparingDouble(n->g.type.equals("ELDER")?n.age:n.trait("loyalty")+n.trait("ambition"))).orElse(null);if(next==null){g.leader=null;return;}g.leader=next.id;g.roles.put("Leader",next.id);next.roles.add("Leader");if(former!=null&&w.npcs.get(former)!=null)w.npcs.get(former).roles.remove("Leader");Npc deputy=s.residents.stream().map(w.npcs::get).filter(CivilizationRules::alive).filter(n->n.age>=18&&!n.id.equals(g.leader)).max(Comparator.comparingDouble(n->n.trait("honesty")+n.trait("loyalty"))).orElse(null);if(deputy!=null){g.deputy=deputy.id;g.roles.put("Deputy",deputy.id);deputy.roles.add("Deputy");}for(String role:List.of("Guard Captain","Treasurer")){String job=role.equals("Guard Captain")?"guard":"merchant";s.residents.stream().map(w.npcs::get).filter(CivilizationRules::alive).filter(n->n.profession.equals(job)).findFirst().ifPresent(n->{g.roles.put(role,n.id);n.roles.add(role);});}w.revision++;}
    private static boolean alive(Npc n){return n!=null&&!n.lifeStage.equals("deceased");}
    public static void metrics(LivingWorld w,Settlement s,CivilizationState.Government g){long alive=s.residents.stream().map(w.npcs::get).filter(CivilizationRules::alive).count();long guards=s.residents.stream().map(w.npcs::get).filter(CivilizationRules::alive).filter(n->n.profession.equals("guard")).count();double food=s.buildings.values().stream().flatMap(b->b.stock.entrySet().stream()).filter(e->{var good=DomesticContent.active.good(e.getKey());return good!=null&&good.nutrition()>0;}).mapToInt(Map.Entry::getValue).sum()+s.households.values().stream().flatMap(h->h.supplies.values().stream()).mapToInt(Integer::intValue).sum();g.metrics.put("Population",(double)alive);g.metrics.put("Housing",(double)s.buildings.values().stream().mapToInt(b->b.beds).sum());g.metrics.put("Food portions",food);g.metrics.put("Agricultural capacity",(double)s.fields.values().stream().mapToInt(p->p.capacity).sum());g.metrics.put("Employment",(double)s.residents.stream().map(w.npcs::get).filter(CivilizationRules::alive).filter(n->!n.workplace.isBlank()).count());g.metrics.put("Security",Math.min(100.0,guards*25+25));g.metrics.put("Prosperity",s.buildings.values().stream().mapToLong(b->b.money).sum()/(double)Math.max(1,alive));g.metrics.put("Morale",s.residents.stream().map(w.npcs::get).filter(CivilizationRules::alive).mapToDouble(n->100*(1-n.need("loneliness"))).average().orElse(0));g.metrics.put("Treasury",(double)g.treasury);}
    public static CivilizationState.Contract shortage(LivingWorld w,Settlement s,Building b,Npc requester){int have=b.stock.getOrDefault("minecraft:wheat",0),threshold=Math.max(8,s.residents.size()/2);if(have>=threshold||b.money<16)return null;if(w.civilization.contracts.values().stream().anyMatch(c->c.business.equals(b.id)&&!Set.of("COMPLETED","EXPIRED","FAILED").contains(c.status)))return null;var c=new CivilizationState.Contract();c.id=SettlementBootstrap.uuid(b.id+"grain-contract-"+(w.clock/24000));if(w.civilization.contracts.containsKey(c.id))return null;c.requester=requester.id;c.business=b.id;c.settlement=s.id;c.item="minecraft:wheat";c.required=threshold-have;c.reward=Math.min(b.money,c.required*2L);c.title="Grain for "+s.name;c.description="Our bakery has "+have+" wheat remaining and needs "+c.required+" more for its next production run.";c.knownInformation="The baker inspected their own ingredient storage. Deliver actual wheat to the baker.";c.target=b.point(Marker.CUSTOMER_POINT);c.deadline=w.clock+48000;b.money-=c.reward;w.transact(b.id,c.id.toString(),"reward escrow",1,c.reward,"fund supply contract");w.civilization.contracts.put(c.id,c);w.remember(requester,new Memory("grain_shortage",null,b.id,w.clock,.8,-.2,1,"inspected workplace"));return c;}
    public static boolean accept(CivilizationState.Contract c,UUID player,long now){if(!c.status.equals("OFFERED")||now>=c.deadline)return false;c.assignee=player;c.status="ACTIVE";return true;}
    public static long deliver(LivingWorld w,CivilizationState.Contract c,UUID player,int quantity){if(!c.status.equals("ACTIVE")||!player.equals(c.assignee)||w.clock>=c.deadline||quantity!=c.required-c.progress)return 0;var s=w.settlements.get(c.settlement);var b=s.buildings.get(c.business);b.stock.merge(c.item,quantity,Integer::sum);c.progress+=quantity;c.status="COMPLETED";var life=w.players.computeIfAbsent(player,k->new PlayerLife());life.money+=c.reward;life.skills.merge("trading",.01,Double::sum);w.npcs.get(c.requester).relationship(player).trust+=3;w.transact(player.toString(),b.id,c.item,quantity,c.reward,"supply contract completed");return c.reward;}
    private CivilizationRules(){}
}
