package vn.svframe.lively.npc;

import java.io.BufferedReader;import java.io.BufferedWriter;import java.io.IOException;import java.nio.charset.StandardCharsets;import java.nio.file.Files;import java.nio.file.Path;import java.nio.file.StandardCopyOption;import java.util.Base64;import java.util.HashMap;import java.util.Map;import java.util.UUID;
/** Crash-safe definition store. Format 2 persists metadata and reads format 1 for migration. */
public final class NpcDefinitionStore {private static final int FORMAT=2;private final Path file;public NpcDefinitionStore(Path file){this.file=file;}
 public Map<UUID,NpcDefinition> loadAll(){Map<UUID,NpcDefinition> result=new HashMap<>();if(!Files.isRegularFile(file))return result;int format;try(BufferedReader reader=Files.newBufferedReader(file,StandardCharsets.UTF_8)){String first=reader.readLine();format=Integer.parseInt(first==null?"0":first.trim());if(format<1||format>FORMAT)throw new IllegalStateException("unsupported npc definition format "+format);String line;while((line=reader.readLine())!=null){if(line.isBlank())continue;String[] p=line.split("\\t",-1);if(p.length<18)continue;UUID id=UUID.fromString(p[0]);Map<String,String> metadata=format>=2&&p.length>=19?decodeMap(p[18]):Map.of();NpcDefinition d=new NpcDefinition(id,unescape(p[1]),unescape(p[2]),NpcDefinition.BodyType.valueOf(p[3]),unescape(p[4]),unescape(p[5]),unescape(p[6]),Double.parseDouble(p[7]),Double.parseDouble(p[8]),Double.parseDouble(p[9]),Float.parseFloat(p[10]),Float.parseFloat(p[11]),Boolean.parseBoolean(p[12]),Boolean.parseBoolean(p[13]),Boolean.parseBoolean(p[14]),Boolean.parseBoolean(p[15]),Boolean.parseBoolean(p[16]),Boolean.parseBoolean(p[17]),metadata);result.put(id,d);}}catch(Exception error){throw new IllegalStateException("failed to load npc definitions",error);}if(format<FORMAT)saveAll(result);return result;}
 public synchronized void saveAll(Map<UUID,NpcDefinition> definitions){try{Files.createDirectories(file.getParent());Path tmp=file.resolveSibling(file.getFileName()+".tmp");try(BufferedWriter writer=Files.newBufferedWriter(tmp,StandardCharsets.UTF_8)){writer.write(Integer.toString(FORMAT));writer.newLine();for(NpcDefinition d:definitions.values().stream().sorted(java.util.Comparator.comparing(v->v.id().toString())).toList()){writer.write(String.join("\t",d.id().toString(),escape(d.name()),escape(d.role()),d.bodyType().name(),escape(d.bodyKey()),escape(d.skinName()),escape(d.world()),Double.toString(d.x()),Double.toString(d.y()),Double.toString(d.z()),Float.toString(d.yaw()),Float.toString(d.pitch()),Boolean.toString(d.spawned()),Boolean.toString(d.aiEnabled()),Boolean.toString(d.invulnerable()),Boolean.toString(d.gravity()),Boolean.toString(d.silent()),Boolean.toString(d.nameVisible()),encodeMap(d.metadata())));writer.newLine();}}try{Files.move(tmp,file,StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}catch(IOException ignored){Files.move(tmp,file,StandardCopyOption.REPLACE_EXISTING);}}catch(IOException error){throw new IllegalStateException("failed to save npc definitions",error);}}
 private static String encodeMap(Map<String,String> map){if(map.isEmpty())return"";StringBuilder out=new StringBuilder();map.entrySet().stream().sorted(Map.Entry.comparingByKey()).forEach(e->out.append(e.getKey()).append('\u001f').append(e.getValue()).append('\u001e'));return Base64.getUrlEncoder().withoutPadding().encodeToString(out.toString().getBytes(StandardCharsets.UTF_8));}
 private static Map<String,String> decodeMap(String encoded){if(encoded==null||encoded.isBlank())return Map.of();String text=new String(Base64.getUrlDecoder().decode(encoded),StandardCharsets.UTF_8);HashMap<String,String> map=new HashMap<>();for(String entry:text.split(String.valueOf('\u001e'),-1)){if(entry.isEmpty())continue;int split=entry.indexOf('\u001f');if(split<=0)continue;map.put(entry.substring(0,split),entry.substring(split+1));}return Map.copyOf(map);}
 private static String escape(String value){return value.replace("\\","\\\\").replace("\t","\\t").replace("\n","\\n");}private static String unescape(String value){return value.replace("\\n","\n").replace("\\t","\t").replace("\\\\","\\");}}
