package io.github.aristheg201.svarcade.engine;

import org.junit.jupiter.api.Test;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

class BattleRuntimeTest {
    private static final BattleBoard BOARD=new BattleBoard(7,8,true,Set.of());
    private static final BattleRuntime.Limits LIMITS=new BattleRuntime.Limits(8,4096,1024,1024,128);
    private BattleUnit unit(String id,int team,int cell){return new BattleUnit(id,"owner:"+team,team,"test:unit",cell,Map.of(Stat.MAX_HP,1000.0,Stat.ATTACK,100.0,Stat.ARMOR,100.0,Stat.SPDEF,0.0,Stat.MAX_MANA,100.0,Stat.CRIT_MULTIPLIER,2.0));}
    private BattleRuntime world(){return new BattleRuntime(BOARD,LIMITS,724,(def,id,owner,team,cell)->unit(id,team,cell),Map.of());}
    private EffectDefinition node(String op,String selector,Map<String,Double> values,Map<String,String> strings,List<EffectDefinition> children){return new EffectDefinition(op,selector,values,strings,children,List.of());}
    private TriggerDefinition trigger(String id,BattleEvent event,int priority,List<EffectDefinition> effects){return new TriggerDefinition(id,event,priority,1,0,1,false,false,List.of(),effects);}

    @Test void damageOrderShieldsMitigationAndTrueDamage(){var w=world();var a=unit("a",0,0);var b=unit("b",1,1);w.add(a);w.add(b);b.shield=25;assertEquals(25,DamagePipeline.damage(w,a,b,100,DamagePipeline.Type.PHYSICAL,false,0,0));assertEquals(975,b.hp);assertEquals(100,DamagePipeline.damage(w,a,b,100,DamagePipeline.Type.TRUE,false,0,0));assertEquals(875,b.hp);}
    @Test void modifiersExpireWithoutCorruptingBaseStats(){var w=world();var a=unit("a",0,0);w.add(a);var effect=node("modify_stat","self",Map.of("amount",20.0,"duration_ms",100.0),Map.of("stat","ATTACK"),List.of());w.execute(a,a,List.of(effect),0);assertEquals(120,a.stat(Stat.ATTACK));w.advance(100);assertEquals(100,a.stat(Stat.ATTACK));}
    @Test void triggerPriorityAndStableIdDetermineOrder(){var w=world();var a=unit("a",0,0);w.add(a);a.triggers.add(trigger("b",BattleEvent.ON_CAST,1,List.of(node("gain_stack","self",Map.of("amount",2.0),Map.of("id","x"),List.of()))));a.triggers.add(trigger("a",BattleEvent.ON_CAST,0,List.of(node("consume_stack","self",Map.of("amount",1.0),Map.of("id","x"),List.of()))));w.emit(BattleEvent.ON_CAST,a,a,a,0,0);w.drain();assertEquals(2,a.stacks.get("x"));}
    @Test void recursionGuardTerminatesMutualDamageTriggers(){var w=world();var a=unit("a",0,0);var b=unit("b",1,1);w.add(a);w.add(b);var retaliate=trigger("retaliate",BattleEvent.ON_DAMAGE_TAKEN,0,List.of(EffectDefinition.amount("true_damage","current_target",1)));a.triggers.add(retaliate);b.triggers.add(retaliate);DamagePipeline.damage(w,a,b,1,DamagePipeline.Type.TRUE,false,0,0);w.drain();assertTrue(w.recursionPrevented()>0);assertTrue(a.hp>980&&b.hp>980);}
    @Test void delayedGraphAndRandomStreamSurviveRestart(){var w=world();var a=unit("a",0,0);var b=unit("b",1,1);w.add(a);w.add(b);w.schedule(100,a,b,List.of(EffectDefinition.amount("damage","current_target",100)),0);var saved=w.snapshot();var recovered=BattleRuntime.restore(BOARD,LIMITS,(def,id,owner,team,cell)->unit(id,team,cell),Map.of(),saved);w.advance(100);recovered.advance(100);assertEquals(w.snapshot(),recovered.snapshot());assertEquals(w.random().nextLong(),recovered.random().nextLong());}
    @Test void targetFilterAndFarthestSelectionAreDeterministic(){var w=world();var a=unit("a",0,0);var b=unit("b",1,1);var c=unit("c",1,40);w.add(a);w.add(b);w.add(c);var select=node("damage","farthest_enemy",Map.of(),Map.of(),List.of());assertEquals("c",w.select(a,b,select).getFirst().id);c.tags.add("boss");assertEquals(List.of(c),w.select(a,b,node("damage","all_enemies",Map.of(),Map.of("tag","boss"),List.of())));}
    @Test void statusIntensityCapsAndExpires(){var w=world();var a=unit("a",0,0);w.add(a);var effect=node("add_status","self",Map.of("duration_ms",100.0,"max_stacks",3.0,"intensity",2.0),Map.of("id","burn","policy","stack_intensity"),List.of());for(int i=0;i<9;i++)w.execute(a,a,List.of(effect),0);assertEquals(3,a.statuses.get("burn").stacks());assertEquals(6,a.statuses.get("burn").intensity());w.advance(100);assertFalse(a.hasStatus("burn"));}
    @Test void graphRejectsUnknownOperationAndCycleWithFieldPath(){var w=world();assertThrows(IllegalArgumentException.class,()->w.validate(List.of(EffectDefinition.amount("missing","self",1)),"units/test.ability"));var ref=node("ref","self",Map.of(),Map.of("id","loop"),List.of());var cycle=new BattleRuntime(BOARD,LIMITS,1,(d,i,o,t,c)->unit(i,t,c),Map.of("loop",List.of(ref)));var e=assertThrows(IllegalArgumentException.class,()->cycle.validate(List.of(ref),"abilities/loop"));assertTrue(e.getMessage().contains("circular"));assertTrue(e.getMessage().contains("abilities/loop"));}
    @Test void cloneKeepsOwnerAndSummonerAndInheritsConfiguredStats(){var w=world();var a=unit("a",0,0);w.add(a);var clone=w.summon(a,a.definitionId,1,0.6,true);assertNotNull(clone);assertEquals(a.id,clone.summoner);assertEquals(a.owner,clone.owner);assertEquals(600,clone.hp);assertEquals(60,clone.stat(Stat.ATTACK));}
    @Test void transformPreservesInstanceAndHealthFraction(){var w=world();var a=unit("a",0,0);w.add(a);a.hp=250;w.transform(a,"test:other",true,0);assertEquals("a",a.id);assertEquals("test:other",a.definitionId);assertEquals(0.25,a.healthFraction());}
    @Test void pathfindingRoutesAroundBlockedCells(){var board=new BattleBoard(5,5,false,Set.of(6,7,8));int next=board.nextStep(2,22,1,Set.of());assertTrue(board.valid(next));assertNotEquals(2,next);}
    @Test void noTriggerRunsTwiceWhenConfiguredOncePerCombat(){var w=world();var a=unit("a",0,0);w.add(a);a.triggers.add(new TriggerDefinition("once",BattleEvent.ON_CAST,0,1,0,1,true,false,List.of(),List.of(node("gain_stack","self",Map.of("amount",1.0),Map.of("id","test"),List.of()))));for(int i=0;i<10;i++)w.emit(BattleEvent.ON_CAST,a,a,a,0,0);w.drain();assertEquals(1,a.stacks.get("test"));}
}
