package vn.worldcomesalive.generation.v2;
import vn.worldcomesalive.model.LivingWorld.*;
import vn.worldcomesalive.model.LivingWorld;
import vn.worldcomesalive.data.WorldContent;
import vn.worldcomesalive.world.SettlementBootstrap;
import vn.worldcomesalive.world.SettlementStructures.Placement;
import vn.worldcomesalive.furniture.*;
import vn.worldcomesalive.civilization.Lodging;
import net.minecraft.block.*;
import net.minecraft.block.enums.*;
import net.minecraft.registry.*;
import net.minecraft.util.*;
import net.minecraft.util.math.*;
import java.util.*;
/** Minecraft execution adapter. Curated massing and room modules materialize one accepted immutable program. */
public final class BlockMaterializer {
    private final Settlement settlement;private final SettlementPlan plan;private final TerrainSnapshot terrain;private final GenerationCatalog data;private final LivingWorld state;
    private final LinkedHashMap<BlockPos,BlockState> blocks=new LinkedHashMap<>();private final BlockState wood,log,stone,roof;private final String timber;private final FurnitureBlock.Wood furnitureWood;
    public BlockMaterializer(Settlement s,TerrainSnapshot t,GenerationCatalog d,LivingWorld state,WorldContent content){settlement=s;plan=s.generationPlan;terrain=t;data=d;this.state=state;var region=content.regions.stream().filter(r->r.id().equals(s.region)).findFirst().orElse(content.regions.getLast());timber=region.wood();wood=block(timber+"_planks").getDefaultState();log=block("stripped_"+timber+"_log").getDefaultState();stone=block(region.stone()).getDefaultState();roof=block(timber+"_stairs").getDefaultState();FurnitureBlock.Wood fw;try{fw=FurnitureBlock.Wood.valueOf(timber.toUpperCase(Locale.ROOT));}catch(Exception unsupported){fw=FurnitureBlock.Wood.OAK;}furnitureWood=fw;}
    public void materialize(Queue<Placement> queue){roads();publicSpace();for(var b:plan.buildings){shell(b);rooms(b);exterior(b);}agriculture();for(var item:blocks.entrySet())queue.add(new Placement(item.getKey(),item.getValue()));blocks.clear();if(plan.dungeon!=null)DungeonMaterializer.generate(plan.dungeon,data,queue);}
    private static Block block(String id){Block b=Registries.BLOCK.get(Identifier.of(id.contains(":")?id:"minecraft:"+id));return b==Blocks.AIR?Blocks.OAK_PLANKS:b;}
    private void put(int x,int y,int z,BlockState block){blocks.put(new BlockPos(x,y,z),block);}
    private void local(SettlementPlan.Building b,int x,int y,int z,BlockState block){var p=b.local(x,z);BlockRotation rotation=BlockRotation.values()[b.rotation()];put((int)p.x(),b.foundation()+y,(int)p.z(),block.rotate(rotation));}
    private void surface(int x,int z,BlockState block){int y=terrain.heightAt(x,z);put(x,y,z,block);for(int i=1;i<=4;i++)put(x,y+i,z,Blocks.AIR.getDefaultState());}
    private void roads(){Set<Long> paved=new HashSet<>();for(var road:plan.roads){var style=data.roads.get(road.kind());for(int i=1;i<road.points().size();i++){var a=road.points().get(i-1);var b=road.points().get(i);int n=Math.max(1,(int)Math.ceil(a.distance(b)*2));for(int j=0;j<=n;j++){var p=a.lerp(b,j/(double)n);int x=(int)Math.round(p.x()),z=(int)Math.round(p.z());for(int dx=-(style.width()/2);dx<style.width()-style.width()/2;dx++)for(int dz=-(style.width()/2);dz<style.width()-style.width()/2;dz++){int xx=x+dx,zz=z+dz;long key=((long)xx<<32)^(zz&0xffffffffL);if(!paved.add(key))continue;BlockState material=style.material().equals("mixed_cobble")?(Math.floorMod(xx*31+zz,7)<2?Blocks.MOSSY_COBBLESTONE:Blocks.COBBLESTONE).getDefaultState():block(style.material()).getDefaultState();surface(xx,zz,material);}}
            }if(style.lighting())for(int i=8;i<road.points().size()-3;i+=12){var p=road.points().get(i);int x=(int)p.x()+style.width()/2+2,z=(int)p.z(),y=terrain.heightAt(x,z);put(x,y+1,z,block(timber+"_fence").getDefaultState());put(x,y+2,z,block(timber+"_fence").getDefaultState());put(x,y+3,z,Blocks.LANTERN.getDefaultState());}}
    }
    private void shell(SettlementPlan.Building b){var def=data.buildings.get(b.program());int w=def.width(),d=def.depth(),height=def.floors()*def.storey();
        // Foundations adapt per column; only the building footprint is excavated, preserving surrounding slopes.
        for(int x=-1;x<=w;x++)for(int z=-1;z<=d;z++){var p=b.local(x,z);int top=terrain.heightAt(p.x(),p.z());for(int y=Math.min(top-b.foundation(),0);y<=0;y++)local(b,x,y,z,stone);for(int y=1;y<=Math.max(height+Math.max(w,d)/2+2,top-b.foundation()+12);y++)local(b,x,y,z,Blocks.AIR.getDefaultState());if(x>=0&&x<w&&z>=0&&z<d){local(b,x,0,z,wood);for(int floor=0;floor<def.floors();floor++){int base=floor*def.storey();if(floor>0)local(b,x,base,z,wood);for(int h=1;h<def.storey();h++)if(x==0||z==0||x==w-1||z==d-1){boolean beam=x%4==0||z%4==0||h==def.storey()-1;boolean window=h==2&&!beam&&(x%4==2||z%4==2);BlockState wall=window?Blocks.GLASS_PANE.getDefaultState():beam?log:Blocks.WHITE_TERRACOTTA.getDefaultState();if(def.roof().equals("open_gable")&&h<3&&!beam)wall=Blocks.AIR.getDefaultState();local(b,x,base+h,z,wall);}}}}
        boolean rotated=def.roof().equals("gable_rotated");int span=rotated?d:w;for(int x=-1;x<=w;x++)for(int z=-1;z<=d;z++){int cross=rotated?z:x;int rise=Math.max(0,Math.min(cross+1,span-cross));if(def.roof().equals("hip"))rise=Math.max(0,Math.min(Math.min(x+1,w-x),Math.min(z+1,d-z)));int roofY=height+rise;Direction direction=rotated?(z<d/2?Direction.SOUTH:Direction.NORTH):(x<w/2?Direction.EAST:Direction.WEST);local(b,x,roofY,z,roof.with(StairsBlock.FACING,direction));if(x>=0&&x<w&&z>=0&&z<d&&(rotated?(x==0||x==w-1):(z==0||z==d-1)))for(int yy=height;yy<roofY;yy++)local(b,x,yy,z,(x%4==0||z%4==0)?log:wood);}
        // A cross-gable porch adds a second roof axis without cutting holes into the main roof.
        if(def.roof().equals("cross_gable")){int middle=w/2;for(int x=middle-3;x<=middle+3;x++)for(int z=d-3;z<=d+2;z++){int rise=3-Math.abs(x-middle);local(b,x,height+Math.max(0,rise),z,roof.with(StairsBlock.FACING,x<middle?Direction.EAST:Direction.WEST));}for(int x:new int[]{middle-3,middle+3})for(int y=1;y<height;y++)local(b,x,y,d+1,log);}
        door(b,w/2,1,d-1,Direction.SOUTH);for(int x=w/2-1;x<=w/2+1;x++)local(b,x,0,d,stone);
        for(int floor=0;floor<def.floors();floor++){int base=floor*def.storey();for(int x=1;x<w-1;x++)for(int z=4;z<d-1;z+=5)local(b,x,base+def.storey()-1,z,log.with(PillarBlock.AXIS,Direction.Axis.X));for(int z=3;z<d-1;z+=7)local(b,w/2,base+def.storey()-2,z,Blocks.LANTERN.getDefaultState().with(LanternBlock.HANGING,true));}
        if(!def.roof().equals("open_gable")){for(int y=height-1;y<=height+5;y++)for(int x=1;x<=2;x++)local(b,x,y,d-3,Blocks.STONE_BRICKS.getDefaultState());local(b,1,height+6,d-3,Blocks.CAMPFIRE.getDefaultState().with(CampfireBlock.LIT,true));}
        if(def.floors()>1){int sx=def.type().equals("tavern")?13:w-3,sz=def.type().equals("tavern")?d-5:d-2;for(int step=0;step<def.storey();step++){for(int clear=step+1;clear<=def.storey()+3;clear++)local(b,sx,clear,sz-step,Blocks.AIR.getDefaultState());local(b,sx,step+1,sz-step,block(timber+"_stairs").getDefaultState().with(StairsBlock.FACING,Direction.NORTH));}}
        var entry=settlement.buildings.get(SemanticRegistration.global(settlement,b.id())).point(Marker.ENTRANCE);var p=b.local(w/2,d);int y=terrain.heightAt(p.x(),p.z());for(int h=0;h<Math.max(1,b.foundation()-y);h++)put((int)p.x(),b.foundation()-h,(int)p.z()+h,stone);
    }
    private void door(SettlementPlan.Building b,int x,int y,int z,Direction direction){var ds=block(timber+"_door").getDefaultState().with(DoorBlock.FACING,direction).with(DoorBlock.OPEN,true);local(b,x,y,z,ds.with(DoorBlock.HALF,DoubleBlockHalf.LOWER));local(b,x,y+1,z,ds.with(DoorBlock.HALF,DoubleBlockHalf.UPPER));}
    private static boolean privateRoom(String type){return type.contains("BEDROOM")||type.equals("BARRACKS")||type.startsWith("INN_")||type.equals("PANTRY")||type.equals("LEADER_OFFICE");}
    private void rooms(SettlementPlan.Building b){var def=data.buildings.get(b.program());var record=settlement.buildings.get(SemanticRegistration.global(settlement,b.id()));for(var room:b.rooms()){
            var r=room.bounds();int floor=room.floor()*def.storey();if(privateRoom(room.type())){for(int x=r.x()-1;x<=r.maxX();x++)for(int z=r.z()-1;z<=r.maxZ();z++)if(x==r.x()-1||x==r.maxX()||z==r.z()-1||z==r.maxZ())for(int y=1;y<=def.storey()-1;y++)local(b,x,floor+y,z,(y==def.storey()-1)?log:wood);door(b,r.x()+RoomComposition.entryX(room,data),floor+1,r.maxZ(),Direction.SOUTH);}
            record.rooms.add(new FurnitureLayout.Room(room.type(),r.x(),r.z(),r.width(),r.depth(),room.composition()));var composition=data.compositions.get(room.composition());Lodging.Room guest=null;if(room.type().startsWith("INN_")){guest=new Lodging.Room();guest.id=SettlementBootstrap.uuid(record.id+room.id());guest.settlement=settlement.id;guest.building=record.id;guest.name=room.type().contains("PREMIUM")?"Merchant's Suite":"Hearthside Room";guest.quality=room.type().contains("PREMIUM")?"Comfort":"Standard";guest.price=guest.quality.equals("Comfort")?24:12;var p1=b.local(r.x(),r.z());var p2=b.local(r.maxX()-1,r.maxZ()-1);guest.min=new Pos(Math.min(p1.x(),p2.x()),b.foundation()+floor+1,Math.min(p1.z(),p2.z()));guest.max=new Pos(Math.max(p1.x(),p2.x())+1,b.foundation()+floor+def.storey(),Math.max(p1.z(),p2.z())+1);var e=b.local(r.x()+RoomComposition.entryX(room,data),r.maxZ());guest.entrance=new Pos(e.x()+.5,b.foundation()+floor+1,e.z()+.5);}
            for(var atom:composition.atoms()){int x=r.x()+atom.x(),z=r.z()+atom.z(),y=floor+1+atom.y();if(atom.x()<0||atom.z()<0||atom.x()>=r.width()||atom.z()>=r.depth())throw new IllegalArgumentException("Composition exceeds room "+room.id()+" "+atom.kind());local(b,x,y,z,atom(atom.kind(),atom.facing()));var p=b.local(x,z);Pos location=new Pos(p.x()+.5,b.foundation()+y,p.z()+.5);for(String marker:atom.markers()){if(marker.equals("GUEST_STORAGE")){if(guest!=null)guest.storage=location;continue;}if(marker.equals("BED")&&guest!=null){guest.beds.add(location);continue;}var semantic=Marker.valueOf(marker);record.mark(semantic,location);if(Set.of(Marker.WORKSTATION,Marker.KITCHEN_POINT,Marker.SHOP_COUNTER,Marker.READING_POINT).contains(semantic)){var access=RoomComposition.accessCell(room,atom,data);var walk=b.local(r.x()+(int)access.x(),r.z()+(int)access.z());record.activityAccess.computeIfAbsent(semantic,k->new ArrayList<>()).add(new Pos(walk.x()+.5,b.foundation()+floor+1,walk.z()+.5));}}}
            if(guest!=null){if(guest.storage==null)guest.storage=guest.beds.getFirst();state.rooms.putIfAbsent(guest.id,guest);}
        }
        if(record.markers.getOrDefault(Marker.BED,List.of()).size()!=record.beds)throw new IllegalArgumentException("Semantic residential capacity mismatch "+record.id);if(!record.profession.equals("resident")&&!record.markers.containsKey(Marker.WORKSTATION))record.mark(Marker.WORKSTATION,record.markers.getOrDefault(Marker.KITCHEN_POINT,record.markers.getOrDefault(Marker.SHOP_COUNTER,List.of(record.point(Marker.ENTRANCE)))).getFirst());if(!record.activityAccess.containsKey(Marker.WORKSTATION))record.activityAccess.put(Marker.WORKSTATION,record.activityAccess.getOrDefault(Marker.KITCHEN_POINT,record.activityAccess.getOrDefault(Marker.SHOP_COUNTER,List.of(record.point(Marker.ENTRANCE)))));if(Set.of("tavern","bakery","trading_post","forge","market").contains(record.type)&&!record.markers.containsKey(Marker.SHOP_COUNTER))record.mark(Marker.SHOP_COUNTER,record.point(Marker.WORKSTATION));record.markers.putIfAbsent(Marker.SOCIAL_POINT,record.markers.getOrDefault(Marker.DINING_POINT,List.of(record.point(Marker.ENTRANCE))));record.seatCapacity=record.markers.getOrDefault(Marker.TAVERN_SEAT,List.of()).size();record.standingCapacity=2;record.serviceCapacity=2;record.furnishingValid=true;
    }
    private BlockState atom(String kind,String facing){Direction direction=Direction.byName(facing);if(kind.equals("bed_foot")||kind.equals("bed_head"))return Blocks.RED_BED.getDefaultState().with(BedBlock.FACING,direction).with(BedBlock.PART,kind.equals("bed_head")?BedPart.HEAD:BedPart.FOOT);if(kind.equals("anvil"))return Blocks.ANVIL.getDefaultState();var furniture=FurnitureRegistry.BLOCKS.get(kind);if(furniture==null)throw new IllegalArgumentException("Missing furniture module "+kind);return furniture.getDefaultState().with(HorizontalFacingBlock.FACING,direction).with(FurnitureBlock.WOOD,furnitureWood);}
    private void exterior(SettlementPlan.Building b){var def=data.buildings.get(b.program());int d=def.depth(),w=def.width();for(String id:def.exterior()){var cluster=data.exteriors.get(id);for(var a:cluster.atoms()){int x=a.x(),z=a.z()+(cluster.anchor().equals("front")?d:0);local(b,x,1+a.y(),z,atom(a.kind(),a.facing()));}}for(int x:new int[]{2,w-3})local(b,x,2,d-1,Blocks.LANTERN.getDefaultState());
        // Private kitchen gardens inherit the same property and persistent field infrastructure.
        if(def.beds()>0&&!def.type().equals("tavern")){var field=new vn.worldcomesalive.agriculture.Agriculture.Plot();field.id=SettlementBootstrap.uuid(settlement.id+b.id()+"garden");field.settlement=settlement.id;field.building=SemanticRegistration.global(settlement,b.id());field.owner=field.building;field.storage=field.building;field.crop="minecraft:carrot";field.state="GROWING";field.width=6;field.depth=2;field.due=2100;for(int x=2;x<8;x++)for(int z=-3;z<-1;z++){var p=b.local(x,z);field.cells.add(new Pos(p.x(),terrain.heightAt(p.x(),p.z()),p.z()));}field.origin=field.cells.getFirst();field.capacity=field.cells.size();settlement.fields.put(field.id,field);}
    }
    private void publicSpace(){var center=plan.district("core").center();var well=Spatial.rotate(new Spatial.Point(5,4),plan.orientation);int x=(int)(center.x()+well.x()),z=(int)(center.z()+well.z()),y=terrain.heightAt(x,z);for(int dx=-2;dx<=2;dx++)for(int dz=-2;dz<=2;dz++)surface(x+dx,z+dz,Blocks.MOSSY_COBBLESTONE.getDefaultState());for(int dx=-1;dx<=1;dx++)for(int dz=-1;dz<=1;dz++)put(x+dx,y+1,z+dz,dx==0&&dz==0?Blocks.WATER.getDefaultState():Blocks.STONE_BRICK_WALL.getDefaultState());for(int dx:new int[]{-1,1})for(int h=2;h<=4;h++)put(x+dx,y+h,z,block(timber+"_fence").getDefaultState());for(int dx=-2;dx<=2;dx++)put(x+dx,y+5,z,block(timber+"_slab").getDefaultState());put(x+3,y+1,z+1,atom("notice_board","west"));
        var market=plan.district("market").center();for(int i=0;i<3;i++){int sx=(int)market.x()+4+i*4,sz=(int)market.z()-4,sy=terrain.heightAt(sx,sz);for(int a=0;a<3;a++){surface(sx+a,sz,Blocks.DIRT_PATH.getDefaultState());put(sx+a,sy+1,sz,atom("serving_counter","south"));put(sx+a,sy+2,sz,atom(i==0?"produce_basket":i==1?"bread_basket":"idle_tableware","north"));put(sx+a,sy+4,sz,Blocks.RED_WOOL.getDefaultState());}put(sx,sy+3,sz,block(timber+"_fence").getDefaultState());put(sx+2,sy+3,sz,block(timber+"_fence").getDefaultState());}}
    private void agriculture(){for(var field:plan.fields){var r=field.boundary();for(int x=r.x();x<r.maxX();x++)for(int z=r.z();z<r.maxZ();z++)if(x==r.x()||x==r.maxX()-1||z==r.z()||z==r.maxZ()-1){int y=terrain.heightAt(x,z);put(x,y+1,z,block(timber+"_fence").getDefaultState());}if(field.kind().equals("PASTURE")){for(int i=0;i<4;i++){int x=r.x()+3+i,z=r.z()+3,y=terrain.heightAt(x,z);put(x,y+1,z,Blocks.HAY_BLOCK.getDefaultState());}continue;}if(field.kind().equals("ORCHARD")){for(int x=r.x()+4;x<r.maxX()-3;x+=6)for(int z=r.z()+4;z<r.maxZ()-3;z+=6){int y=terrain.heightAt(x,z);for(int h=1;h<=3;h++)put(x,y+h,z,Blocks.OAK_LOG.getDefaultState());for(int dx=-2;dx<=2;dx++)for(int dz=-2;dz<=2;dz++)for(int h=3;h<=4;h++)if(Math.abs(dx)+Math.abs(dz)<4)put(x+dx,y+h,z+dz,Blocks.OAK_LEAVES.getDefaultState().with(LeavesBlock.PERSISTENT,true));}continue;}int gx=r.x(),gz=r.z()+r.depth()/2;put(gx,terrain.heightAt(gx,gz)+1,gz,block(timber+"_fence_gate").getDefaultState().with(FenceGateBlock.FACING,Direction.WEST).with(FenceGateBlock.OPEN,true));for(int x=r.x()+7;x<r.maxX()-1;x+=7)for(int z=r.z()+1;z<r.maxZ()-1;z++)surface(x,z,Blocks.WATER.getDefaultState());}
        for(var plot:settlement.fields.values())for(var c:plot.cells){int x=(int)c.x(),y=(int)c.y(),z=(int)c.z();put(x,y,z,Blocks.FARMLAND.getDefaultState().with(FarmlandBlock.MOISTURE,7));for(int clear=1;clear<5;clear++)put(x,y+clear,z,Blocks.AIR.getDefaultState());Block crop=plot.crop.equals("minecraft:carrot")?Blocks.CARROTS:plot.crop.equals("minecraft:potato")?Blocks.POTATOES:Blocks.WHEAT;put(x,y+1,z,crop.getDefaultState().with(CropBlock.AGE,plot.state.equals("MATURE")?7:3));}
    }
}
