package vn.worldcomesalive.generation.v2;
import vn.worldcomesalive.world.SettlementStructures.Placement;
import vn.worldcomesalive.furniture.*;
import net.minecraft.block.*;
import net.minecraft.util.math.*;
import java.util.*;
/** Semantic chambers and validated graph edges materialize as a ruined chapel and connected burial zones. */
public final class DungeonMaterializer {
    public static void generate(DungeonPlan dungeon,GenerationCatalog data,Queue<Placement> placements){Map<BlockPos,BlockState> blocks=new LinkedHashMap<>();for(var room:dungeon.chambers){var r=room.bounds();int floor=dungeon.surface-room.level()*8;for(int x=r.x()-1;x<=r.maxX();x++)for(int z=r.z()-1;z<=r.maxZ();z++)for(int y=0;y<=5;y++){boolean wall=x==r.x()-1||x==r.maxX()||z==r.z()-1||z==r.maxZ();BlockState material=y==0||y==5||wall?(Math.floorMod(x*19+z*7+y,8)==0?Blocks.CRACKED_STONE_BRICKS:Blocks.STONE_BRICKS).getDefaultState():Blocks.AIR.getDefaultState();if(room.level()==0&&y==5)material=Blocks.AIR.getDefaultState();blocks.put(new BlockPos(x,floor+y,z),material);}for(var atom:data.compositions.get(room.composition()).atoms()){var furniture=FurnitureRegistry.BLOCKS.get(atom.kind());if(furniture!=null)blocks.put(new BlockPos(r.x()+atom.x(),floor+1+atom.y(),r.z()+atom.z()),furniture.getDefaultState().with(HorizontalFacingBlock.FACING,Direction.byName(atom.facing())).with(FurnitureBlock.WOOD,FurnitureBlock.Wood.DARK_OAK));}for(int x:new int[]{r.x(),r.maxX()-1})blocks.put(new BlockPos(x,floor+3,r.z()+r.depth()/2),Blocks.LANTERN.getDefaultState());if(room.lootBudget()>0){BlockPos pos=new BlockPos(r.maxX()-2,floor+1,r.maxZ()-2);blocks.put(pos,Blocks.CHEST.getDefaultState());DungeonPlan.Loot loot=new DungeonPlan.Loot();loot.x=pos.getX();loot.y=pos.getY();loot.z=pos.getZ();loot.room=room.id();loot.items.put("minecraft:iron_ingot",Math.max(1,room.lootBudget()/3));if(room.role().equals("LIBRARY"))loot.items.put("minecraft:book",room.lootBudget()/2);if(room.role().equals("BOSS"))loot.items.put("minecraft:emerald",room.lootBudget()/4);else loot.items.put("minecraft:bone",Math.max(1,room.lootBudget()/4));dungeon.loot.add(loot);}}
        for(var edge:dungeon.links){var a=dungeon.chambers.stream().filter(r->r.id().equals(edge.from())).findFirst().orElseThrow();var b=dungeon.chambers.stream().filter(r->r.id().equals(edge.to())).findFirst().orElseThrow();var p=a.bounds().center();var q=b.bounds().center();List<Spatial.Point> corners=List.of(p,new Spatial.Point(q.x(),p.z()),q);double length=p.distance(corners.get(1))+corners.get(1).distance(q),travel=0;int ay=dungeon.surface-a.level()*8,by=dungeon.surface-b.level()*8;for(int part=1;part<corners.size();part++){var start=corners.get(part-1);var end=corners.get(part);int steps=Math.max(1,(int)Math.ceil(start.distance(end)));for(int step=0;step<=steps;step++){var point=start.lerp(end,step/(double)steps);double distance=travel+start.distance(point);int y=ay+(int)Math.round((by-ay)*distance/Math.max(1,length));int x=(int)point.x(),z=(int)point.z();boolean horizontal=Math.abs(end.x()-start.x())>Math.abs(end.z()-start.z());Direction facing=horizontal?(end.x()>start.x()?Direction.EAST:Direction.WEST):(end.z()>start.z()?Direction.SOUTH:Direction.NORTH);if(by<ay)facing=facing.getOpposite();for(int offset=-1;offset<=1;offset++){int xx=x+(horizontal?0:offset),zz=z+(horizontal?offset:0);blocks.put(new BlockPos(xx,y,zz),ay==by?Blocks.STONE_BRICKS.getDefaultState():Blocks.STONE_BRICK_STAIRS.getDefaultState().with(StairsBlock.FACING,facing));for(int h=1;h<=4;h++)blocks.put(new BlockPos(xx,y+h,zz),Blocks.AIR.getDefaultState());blocks.put(new BlockPos(xx,y+5,zz),Blocks.STONE_BRICKS.getDefaultState());}if(step%5==0)blocks.put(new BlockPos(x,y+4,z),Blocks.LANTERN.getDefaultState());}travel+=start.distance(end);}}
        var entrance=dungeon.chambers.stream().filter(r->r.id().equals("entrance")).findFirst().orElseThrow().bounds();int x=(int)entrance.center().x(),z=entrance.maxZ();for(int dx=-1;dx<=1;dx++)for(int h=1;h<=3;h++)blocks.put(new BlockPos(x+dx,dungeon.surface+h,z),Blocks.AIR.getDefaultState());for(int dx=-1;dx<=1;dx++)blocks.put(new BlockPos(x+dx,dungeon.surface,z),Blocks.MOSSY_COBBLESTONE.getDefaultState());blocks.forEach((p,s)->placements.add(new Placement(p,s)));
    }
    private DungeonMaterializer(){}
}
