package vn.worldcomesalive.generation.v2;
import vn.worldcomesalive.world.SettlementBootstrap;
import java.util.*;
import static vn.worldcomesalive.generation.v2.Spatial.*;
/** Regional site reservation -> authored macro graph -> semantic zones -> two vertical levels. */
public final class DungeonPlanner {
    public static DungeonPlan plan(SettlementPlan settlement,TerrainSnapshot terrain,GenerationCatalog catalog){var def=catalog.dungeons.values().iterator().next();Point chosen=null;double best=-Double.MAX_VALUE;for(int i=0;i<1000;i++){double angle=i*2.399963229728653;Point p=settlement.center.plus(Math.cos(angle)*135,Math.sin(angle)*135);Rect site=centered(p,def.width(),def.depth());if(!terrain.contains(p,40)||terrain.suitability(site)<-100||settlement.publicSpaces.stream().anyMatch(l->l.boundary().expand(5).overlaps(site))||settlement.lots.stream().anyMatch(l->l.boundary().expand(5).overlaps(site))||settlement.fields.stream().anyMatch(f->f.boundary().expand(4).overlaps(site))||settlement.roads.stream().anyMatch(r->TerrainRouter.crosses(site,r,2)))continue;double score=terrain.suitability(site)-p.distance(settlement.district("approach").center())*.02;if(score>best){best=score;chosen=p;}}if(chosen==null)throw new IllegalArgumentException("No compatible semantic dungeon anchor");var dungeon=new DungeonPlan();dungeon.id="dungeon_"+Long.toUnsignedString(settlement.program.seed(),36);dungeon.archetype=def.id();dungeon.history=def.history();dungeon.faction=def.faction();dungeon.anchor=chosen;dungeon.surface=terrain.foundation(centered(chosen,9,9));for(var room:def.rooms()){var bounds=new Rect((int)chosen.x()+room.x(),(int)chosen.z()+room.z(),room.width(),room.depth());dungeon.chambers.add(new DungeonPlan.Chamber(room.id(),room.role(),room.zone(),bounds,room.level(),room.composition(),room.lootBudget()));if(!room.encounter().isBlank()){var o=new DungeonPlan.Occupant();o.id=SettlementBootstrap.uuid(dungeon.id+room.id());o.room=room.id();o.species=room.encounter();o.danger=room.role().equals("BOSS")?3:1;dungeon.occupants.put(o.id,o);}}for(var edge:def.links())dungeon.links.add(new DungeonPlan.Link(edge.from(),edge.to(),edge.mandatory()));if(!dungeon.connected())throw new IllegalArgumentException("Dungeon macro graph disconnected");for(int i=0;i<dungeon.chambers.size();i++)for(int j=i+1;j<dungeon.chambers.size();j++){var a=dungeon.chambers.get(i);var b=dungeon.chambers.get(j);if(a.level()==b.level()&&a.bounds().expand(1).overlaps(b.bounds().expand(1)))throw new IllegalArgumentException("Dungeon chambers overlap");}return dungeon;}
    private DungeonPlanner(){}
}
