package vn.worldcomesalive.generation.v2;
import java.util.*;
/** Compiles authored compositions, proves bedside/workpoint access and budgets cheap visual detail before placement. */
public final class RoomComposition {
    public record Report(int primary,int secondary,int details,int walkable,int area,List<String> failures){public boolean valid(){return failures.isEmpty();}}
    public static Report validate(SettlementPlan.Room room,GenerationCatalog data){var composition=data.compositions.get(room.composition());int width=room.bounds().width(),depth=room.bounds().depth();Set<Integer> occupied=new HashSet<>();Set<String> positions=new HashSet<>();List<String> errors=new ArrayList<>();int primary=0,secondary=0,details=0;for(var a:composition.atoms()){if(a.x()<0||a.x()>=width||a.z()<0||a.z()>=depth||a.y()<0||a.y()>3)errors.add("Atom outside room: "+a.kind());if(!positions.add(a.x()+":"+a.y()+":"+a.z()))errors.add("Intersecting modules: "+a.kind());if(a.y()==0&&!a.kind().equals("rug")&&!a.kind().equals("firewood"))occupied.add(a.z()*width+a.x());switch(a.layer()){case "primary"->primary++;case "secondary"->secondary++;default->details++;}}
        int entry=(depth-1)*width+entryX(room,data);Set<Integer> reachable=new HashSet<>();ArrayDeque<Integer> queue=new ArrayDeque<>();if(!occupied.contains(entry)){queue.add(entry);reachable.add(entry);}while(!queue.isEmpty()){int p=queue.remove(),x=p%width,z=p/width;for(int[] d:new int[][]{{1,0},{-1,0},{0,1},{0,-1}}){int nx=x+d[0],nz=z+d[1],next=nz*width+nx;if(nx>=0&&nx<width&&nz>=0&&nz<depth&&!occupied.contains(next)&&reachable.add(next))queue.add(next);}}
        for(var atom:composition.atoms())if(atom.y()==0&&!atom.markers().isEmpty()){boolean access=false;for(int[] d:new int[][]{{1,0},{-1,0},{0,1},{0,-1}}){int x=atom.x()+d[0],z=atom.z()+d[1];if(x>=0&&x<width&&z>=0&&z<depth&&reachable.contains(z*width+x))access=true;}if(!access&&atom.markers().contains("DINING_TABLE")){for(var seat:composition.atoms())if(seat.y()==0&&(seat.kind().contains("chair")||seat.kind().contains("bench")||seat.kind().contains("stool"))&&Math.abs(seat.x()-atom.x())+Math.abs(seat.z()-atom.z())<=1)for(int[] d:new int[][]{{1,0},{-1,0},{0,1},{0,-1}}){int x=seat.x()+d[0],z=seat.z()+d[1];if(x>=0&&x<width&&z>=0&&z<depth&&reachable.contains(z*width+x))access=true;}}if(!access)errors.add("Inaccessible activity "+atom.kind());}
        if(primary<1||secondary<1||details<2)errors.add("Composition lacks visual layers");if(details>96)errors.add("Decoration budget exceeded");return new Report(primary,secondary,details,reachable.size(),width*depth,List.copyOf(errors));}
    public static Spatial.Point accessCell(SettlementPlan.Room room,GenerationCatalog.Atom target,GenerationCatalog data){int width=room.bounds().width(),depth=room.bounds().depth();Set<Integer> blocked=new HashSet<>();for(var atom:data.compositions.get(room.composition()).atoms())if(atom.y()==0&&!atom.kind().equals("rug")&&!atom.kind().equals("firewood"))blocked.add(atom.z()*width+atom.x());Set<Integer> reached=new HashSet<>();ArrayDeque<Integer> queue=new ArrayDeque<>();int entry=(depth-1)*width+entryX(room,data);queue.add(entry);reached.add(entry);while(!queue.isEmpty()){int p=queue.remove();for(int[] delta:new int[][]{{1,0},{-1,0},{0,1},{0,-1}}){int x=p%width+delta[0],z=p/width+delta[1],next=z*width+x;if(x>=0&&x<width&&z>=0&&z<depth&&!blocked.contains(next)&&reached.add(next))queue.add(next);}}for(int[] delta:new int[][]{{0,1},{1,0},{-1,0},{0,-1}}){int x=target.x()+delta[0],z=target.z()+delta[1];if(x>=0&&x<width&&z>=0&&z<depth&&reached.contains(z*width+x))return new Spatial.Point(x,z);}throw new IllegalArgumentException("No usable interaction access: "+room.id()+" "+target.kind());}
    public static int entryX(SettlementPlan.Room room,GenerationCatalog data){int mid=room.bounds().width()/2,last=room.bounds().depth()-1;for(int offset=0;offset<room.bounds().width();offset++)for(int sign:new int[]{1,-1}){int candidate=mid+offset*sign;if(candidate<0||candidate>=room.bounds().width())continue;if(data.compositions.get(room.composition()).atoms().stream().noneMatch(a->a.x()==candidate&&a.z()==last&&a.y()==0&&!a.kind().equals("rug")&&!a.kind().equals("firewood")))return candidate;}throw new IllegalArgumentException("No open room entrance "+room.id());}
    private RoomComposition(){}
}
