package vn.svarcade.tcg.client.screens;
import vn.svarcade.tcg.client.*;import vn.svarcade.tcg.client.component.*;import vn.svarcade.tcg.client.card.CardRenderer;import java.util.*;
public final class CollectionScreen implements Page {
 public void render(CardWorldsScreen a,Ui u,Rect b){a.field(u,"search","Search cards…",new Rect(b.x(),b.y(),300,34));a.select(u,a.rarity.equals("All")?"Rarity":a.rarity,new Rect(b.x()+310,b.y(),132,34),java.util.stream.Stream.concat(java.util.stream.Stream.of("All"),a.state.definitions().values().stream().map(c->c.rarity()).distinct().sorted()).toList(),v->a.rarity=v);a.select(u,a.set.equals("All")?"Set":a.set,new Rect(b.x()+452,b.y(),180,34),java.util.stream.Stream.concat(java.util.stream.Stream.of("All"),a.state.definitions().values().stream().map(c->c.set()).distinct().sorted()).toList(),v->a.set=v);a.select(u,a.ownership,new Rect(b.x()+642,b.y(),119,34),List.of("Owned","Missing","All","Favorites"),v->a.ownership=v);
 int x=b.x();for(String type:List.of("all","pokemon","trainer","item","technique","reaction","stadium")){String t=type;u.chip(type.equals("pokemon")?"Pokémon":type.substring(0,1).toUpperCase()+type.substring(1),new Rect(x,b.y()+44,101,29),a.category.equals(type),()->{a.category=t;a.scroll=0;a.scrolling.reset("collection/grid");});x+=109;}
 Rect grid=new Rect(b.x(),b.y()+88,b.w()-299,b.h()-118);var cards=a.cards();int cols=5,gap=12,cw=(grid.w()-14-gap*(cols-1))/cols,ch=(int)(cw*1.4);
 var region=a.beginScroll(u,"collection/grid",grid,((cards.size()+cols-1)/cols)*(ch+gap));
 for(int i=0;i<cards.size();i++){var card=cards.get(i);Rect r=new Rect(grid.x()+i%cols*(cw+gap),grid.y()+i/cols*(ch+gap)-region.offset(),cw,ch);if(!u.visible(r))continue;
  CardRenderer.draw(u,card,r,a.count(card.id()),card.id().equals(a.selected),a.count(card.id())>0,"binder");u.click(r,()->a.selected=card.id());}
 a.endScroll(u,region);
 if(cards.isEmpty())u.text("cardworlds.ui.no_cards_match_these_filters",grid.x()+18,grid.y()+40,18,Ui.MUTED);
 u.text(a.state.total()+" catalog ? "+a.state.collected()+" collected",b.x(),b.bottom()-20,14,Ui.MUTED);
 u.button("cardworlds.ui.previous",new Rect(grid.right()-194,b.bottom()-28,90,28),false,region.offset()>0,()->a.scrolling.move("collection/grid",-grid.h()));
 u.button("cardworlds.ui.next",new Rect(grid.right()-96,b.bottom()-28,90,28),false,region.offset()<region.max(),()->a.scrolling.move("collection/grid",grid.h()));
 inspector(a,u,new Rect(b.right()-281,b.y(),281,b.h()));
 }
 public static void inspector(CardWorldsScreen a,Ui u,Rect r){u.panel(r);var card=a.selectedCard();if(card==null){u.text("cardworlds.ui.card_details",r.x()+18,r.y()+18,17,Ui.GOLD);u.paragraph("cardworlds.ui.select_a_card_to_view_its_rules_copies_and_source",new Rect(r.x()+18,r.y()+55,r.w()-36,110),17,Ui.MUTED);return;}int ch=Math.min(243,(r.h()-210)/2+80),cw=(int)(ch/1.4);CardRenderer.draw(u,card,new Rect(r.x()+(r.w()-cw)/2,r.y()+16,cw,ch),a.count(card.id()),false,true,"inspector");int y=r.y()+ch+30;u.text(vn.svarcade.tcg.client.component.CardWorldsLanguage.name(card),r.x()+16,y,23,Ui.WHITE);u.text(card.category().equals("pokemon")?"★"+card.level()+" · "+card.type().toUpperCase()+" · "+card.summonRequirement()+" · "+a.count(card.id())+" owned":card.category().toUpperCase()+" · "+a.count(card.id())+" owned",r.x()+16,y+30,14,Ui.GOLD);Rect rules=new Rect(r.x()+16,y+55,r.w()-32,Math.max(55,r.bottom()-y-174));String text=CardWorldsLanguage.effect(card);int textHeight=u.paragraphHeight(text,rules.w()-14,16);
 var rulesScroll=a.beginScroll(u,"inspector/"+card.id(),rules,textHeight);u.paragraph(text,new Rect(rules.x(),rules.y()-rulesScroll.offset(),rules.w()-14,textHeight+20),16,Ui.WHITE);a.endScroll(u,rulesScroll);u.text("cardworlds.ui.set_d7585"+card.set()+" · Print rarity: "+card.rarity(),r.x()+16,r.bottom()-119,13,Ui.MUTED);
 u.button(card.extra()?"Add to Extra":"Add to Main",new Rect(r.x()+14,r.bottom()-96,125,32),true,a.owned(card.id())!=null,()->{a.add(card);a.notice("Added to deck draft.");});u.button(a.favorites.contains(card.id())?"Unfavorite":"Favorite",new Rect(r.x()+145,r.bottom()-96,122,32),false,true,()->a.favorite(card.id()));u.button("cardworlds.ui.list_on_market",new Rect(r.x()+14,r.bottom()-55,125,32),false,a.owned(card.id())!=null,()->a.navigate("Market"));u.button(a.details?"Hide details":"View details",new Rect(r.x()+145,r.bottom()-55,122,32),false,true,()->a.details=!a.details);
 if(a.details){var owned=a.owned(card.id());Rect info=new Rect(r.x()-430,r.y()+12,418,Math.min(560,r.h()-24));u.panel(info);u.text("cardworlds.ui.card_details",info.x()+15,info.y()+15,19,Ui.GOLD);
  String details=CardWorldsLanguage.effect(card)+"\n\nSource: "+String.join(", ",card.sources())+(owned==null?"":"\nFinish: "+owned.finish()+"\nSerial: "+owned.serial()+"\nFound: "+java.time.Instant.ofEpochSecond(owned.acquired()));
  Rect body=new Rect(info.x()+15,info.y()+48,info.w()-30,info.h()-63);int content=u.paragraphHeight(details,body.w()-14,14);var detailScroll=a.beginScroll(u,"details/"+card.id(),body,content);
  u.paragraph(details,new Rect(body.x(),body.y()-detailScroll.offset(),body.w()-14,content+20),14,Ui.WHITE);a.endScroll(u,detailScroll);}
 }
}
