package vn.svarcade.tcg.client.screens;
import vn.svarcade.tcg.client.*;import vn.svarcade.tcg.client.component.*;import vn.svarcade.tcg.client.render.PokemonModels;import net.minecraft.item.Items;import java.util.*;
public final class HomeScreen implements Page {
 public void render(CardWorldsScreen a,Ui u,Rect b){int heroW=b.w()-284,heroH=Math.min(300,b.h()/2);Rect hero=new Rect(b.x(),b.y(),heroW,heroH);u.arena(hero);u.fill(hero,0x55041321);u.ornament(hero,Ui.GOLD);PokemonModels.draw(u,"charizard",List.of(),new Rect(hero.right()-350,hero.y()+5,340,heroH-10),"home");u.text("cardworlds.ui.featured_set",b.x()+26,b.y()+35,14,Ui.GOLD);u.text("KANTO",b.x()+26,b.y()+72,47,Ui.WHITE);u.text("cardworlds.ui.crossroads_3f725",b.x()+26,b.y()+122,40,Ui.GOLD);u.text("cardworlds.ui.30_cards_evolution_reactions",b.x()+28,hero.bottom()-76,16,Ui.WHITE);u.button("cardworlds.ui.view_packs",new Rect(b.x()+28,hero.bottom()-47,145,32),true,true,()->a.navigate("Packs"));
 Rect rank=new Rect(hero.right()+16,b.y(),268,heroH/2-7);u.panel(rank);u.item(Items.AMETHYST_SHARD,new Rect(rank.x()+16,rank.y()+22,48,48));u.text("cardworlds.ui.ranked_1b706",rank.x()+79,rank.y()+20,14,Ui.GOLD);u.text(a.state.profile().rating()+" RP",rank.x()+79,rank.y()+45,27,Ui.WHITE);u.button("cardworlds.ui.play_ranked",new Rect(rank.x()+17,rank.bottom()-45,234,30),false,true,()->{a.mode="Ranked";a.navigate("Play");});
 Rect discovery=new Rect(rank.x(),rank.bottom()+14,268,heroH-rank.h()-14);u.panel(discovery);u.item(Items.BRUSH,new Rect(discovery.x()+16,discovery.y()+20,37,37));u.text("cardworlds.ui.ancient_sands_254d6",discovery.x()+66,discovery.y()+20,16,Ui.GOLD);u.text("cardworlds.ui.archaeology_discovery",discovery.x()+66,discovery.y()+43,14,Ui.MUTED);u.button("cardworlds.ui.view_activity",new Rect(discovery.x()+17,discovery.bottom()-44,234,29),false,true,()->a.navigate("World"));
 String[] names={"Play","Decks","Collection","Packs","Market","World"},subs={"Casual · Ranked · Practice","Build & save decks",a.state.collected()+" unique cards","Open packs · View rates","Buy · Sell · Trade","NPCs · Discoveries"},species={"pikachu","blastoise","mew","gengar","eevee","onix"};int gap=14,tileW=(b.w()-gap*2)/3,tileH=Math.max(92,(b.h()-heroH-40)/2);
 for(int i=0;i<6;i++){String name=names[i];Rect t=new Rect(b.x()+i%3*(tileW+gap),hero.bottom()+18+i/3*(tileH+gap),tileW,tileH);u.panel(t);u.c.fillGradient(t.x(),t.y(),t.right(),t.bottom(),0xFF16364C,0xFF071722);PokemonModels.draw(u,species[i],List.of(),new Rect(t.right()-130,t.y()+1,125,t.h()-2),"tile"+i);u.text(name.equals("Decks")?"DECK BUILDER":name.toUpperCase(),t.x()+17,t.bottom()-51,21,Ui.WHITE);u.text(subs[i],t.x()+17,t.bottom()-26,14,Ui.MUTED);u.ornament(t,t.contains(u.mx,u.my)?Ui.CYAN:Ui.LINE);u.click(t,()->a.navigate(name));}
 if(a.state.profile().owned()==0)u.button("cardworlds.ui.claim_starter_collection",new Rect(b.x()+28,hero.bottom()-47,216,32),true,true,()->a.send("starter"));
 }
}
