org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
loader_version=0.18.4
fabric_version=0.116.8+1.21.1
fabric_kotlin_version=1.13.6+kotlin.2.2.20
kotlin_version=2.2.20
cobblemon_version=1.8.0+1.21.1
placeholder_api_version=2.4.2+1.21
adventure_version=4.24.0
examination_version=1.3.0

mod_id=svhub
mod_name=SVHub
mod_version=0.2.0
maven_group=io.github.aristheg201
