package io.github.aristheg201.svarcade.engine;

public enum Stat {
    MAX_HP, ATTACK, AP, ARMOR, SPDEF, ATTACK_SPEED, RANGE, MAX_MANA, MANA_ON_ATTACK, MANA_ON_HIT,
    CRIT_CHANCE, CRIT_MULTIPLIER, DAMAGE_AMPLIFICATION, DAMAGE_REDUCTION, FLAT_REDUCTION,
    ARMOR_PENETRATION, MAGIC_PENETRATION, LIFESTEAL, OMNIVAMP, HEAL_POWER, HEAL_REDUCTION,
    MOVE_SPEED, KNOCKBACK_RESISTANCE, STAR, COST
}
