"""Authored high-level spatial programs and human-scale composition modules for WCA Engine V2."""
from pathlib import Path
import json
C={}
def atom(k,x,y,z,f='north',layer='detail',markers=()):return dict(kind=k,x=x,y=y,z=z,facing=f,layer=layer,markers=list(markers))
def composition(id,type,rows):C[id]=dict(id=id,roomType=type,atoms=[atom(*r) for r in rows])
def bed(x,z,f='north'):return [('bed_foot',x,0,z,f,'primary',['BED']),('bed_head',x+(1 if f=='east' else -1 if f=='west' else 0),0,z+(1 if f=='south' else -1 if f=='north' else 0),f,'primary',[])]
composition('bedroom_hearthside','MASTER_BEDROOM',bed(1,1)+bed(2,1)+[('bedside_table',3,0,1,'north','secondary'),('candle_holder',3,1,1),('wardrobe',0,0,2,'east','primary'),('folded_cloth',0,1,2),('rug',2,0,2),('storage_chest',3,0,3,'north','secondary'),('personal_belongings',3,1,3),('wall_shelf',3,1,0,'south','secondary'),('book_stack',3,2,0),('tapestry',0,1,1,'east')])
composition('bedroom_window_desk','MASTER_BEDROOM',bed(1,1)+bed(2,1)+[('bedside_table',0,0,1,'north','secondary'),('candle_holder',0,1,1),('dresser',3,0,0,'south','primary'),('folded_cloth',3,1,0),('writing_desk',0,0,3,'east','secondary',['READING_POINT']),('wooden_stool',1,0,3,'west','secondary'),('paper_quill',0,1,3),('rug',2,0,2),('wall_shelf',3,1,3,'west','secondary'),('book_stack',3,2,3),('tapestry',3,1,1,'west')])
composition('bedroom_alcove','MASTER_BEDROOM',bed(1,1)+bed(2,1)+[('wardrobe',0,0,0,'east','primary'),('bedside_table',3,0,1,'north','secondary'),('flower_vase',3,1,1),('rug',1,0,3),('rug',2,0,3),('medieval_bookshelf',0,0,3,'east','secondary'),('book_stack',0,1,3),('storage_chest',3,0,3,'north','secondary'),('personal_belongings',3,1,3),('wall_sconce',3,2,0,'south'),('wall_shelf',0,1,2,'east','secondary'),('folded_cloth',0,2,2)])
composition('child_reading','CHILD_BEDROOM',bed(2,1)+[('bedside_table',3,0,1,'north','secondary'),('book_stack',3,1,1),('writing_desk',0,0,2,'east','primary',['READING_POINT']),('wooden_stool',1,0,2,'west','secondary'),('paper_quill',0,1,2),('storage_chest',3,0,3,'north','secondary'),('personal_belongings',3,1,3),('rug',2,0,3),('wall_shelf',0,1,0,'south','secondary'),('flower_vase',0,2,0),('wall_sconce',3,2,2,'west')])
composition('shared_children','SHARED_BEDROOM',bed(1,1)+bed(3,2)+[('bedside_table',2,0,1,'north','secondary'),('candle_holder',2,1,1),('storage_chest',0,0,3,'north','secondary'),('personal_belongings',0,1,3),('rug',2,0,3),('wall_shelf',0,1,0,'south','secondary'),('book_stack',0,2,0),('wall_sconce',3,2,3,'west')])
composition('kitchen_larder','KITCHEN',[('oven_hearth',0,0,0,'south','primary',['KITCHEN_POINT']),('cooking_pot',0,1,0),('preparation_counter',1,0,0,'south','primary'),('preparation_counter',2,0,0,'south','primary'),('preparation_counter',3,0,0,'south','primary'),('chopping_board',1,1,0),('plate_stack',2,1,0),('water_pitcher',3,1,0),('food_pantry',3,0,3,'west','secondary',['FOOD_STORAGE']),('produce_basket',3,1,3),('ingredient_shelf',0,1,2,'east','secondary'),('hanging_herbs',0,2,2,'east'),('flour_sack',0,0,2),('cookware_rack',3,2,1,'west'),('wall_sconce',2,2,0,'south'),('firewood',0,0,1)])
composition('kitchen_window','KITCHEN',[('oven_hearth',3,0,0,'west','primary',['KITCHEN_POINT']),('cooking_pot',3,1,0),('preparation_counter',3,0,1,'west','primary'),('preparation_counter',3,0,2,'west','primary'),('chopping_board',3,1,1),('water_pitcher',3,1,2),('food_pantry',0,0,0,'south','secondary',['FOOD_STORAGE']),('bread_basket',0,1,0),('ingredient_shelf',1,1,0,'south','secondary'),('hanging_herbs',1,2,0,'south'),('produce_basket',0,0,3),('firewood',2,0,0),('wall_sconce',3,2,3,'west'),('plate_stack',0,2,0)])
composition('dining_hearth','DINING_LIVING',[('medieval_table',2,0,2,'north','primary',['DINING_TABLE']),('dining_chair',1,0,2,'east','primary',['DINING_POINT']),('dining_chair',3,0,2,'west','primary',['DINING_POINT']),('wooden_bench',2,0,3,'north','primary',['DINING_POINT']),('idle_tableware',2,1,2),('rug',1,0,3),('rug',3,0,3),('oven_hearth',0,0,0,'south','primary'),('firewood',1,0,0),('armchair',0,0,2,'east','secondary',['SOCIAL_POINT']),('medieval_bookshelf',4,0,0,'south','secondary',['READING_POINT']),('book_stack',4,1,0),('wall_sconce',0,2,3,'east'),('coat_rack',4,0,4,'north','secondary'),('tapestry',0,1,1,'east')])
composition('dining_window','DINING_LIVING',[('dining_table',2,0,1,'north','primary',['DINING_TABLE']),('dining_table',2,0,2,'north','primary',['DINING_TABLE']),('wooden_bench',1,0,1,'east','primary',['DINING_POINT']),('dining_chair',3,0,1,'west','primary',['DINING_POINT']),('dining_chair',3,0,2,'west','primary',['DINING_POINT']),('dining_chair',2,0,3,'north','primary',['DINING_POINT']),('idle_tableware',2,1,1),('bread_basket',2,1,2),('medieval_bookshelf',0,0,0,'south','secondary',['READING_POINT']),('paper_quill',0,1,0),('armchair',0,0,3,'east','secondary',['SOCIAL_POINT']),('rug',1,0,3),('flower_vase',4,1,0),('cabinet',4,0,0,'west','secondary'),('wall_shelf',0,1,2,'east','secondary'),('book_stack',0,2,2),('wall_sconce',4,2,3,'west')])
composition('shop_goods','SHOP',[('serving_counter',1,0,1,'south','primary',['SHOP_COUNTER']),('serving_counter',2,0,1,'south','primary'),('serving_counter',3,0,1,'south','primary'),('bread_basket',1,1,1),('produce_basket',3,1,1),('crate',0,0,0,'south','secondary',['STORAGE']),('flour_sack',0,1,0),('ingredient_shelf',4,1,0,'south','secondary'),('barrel_rack',4,0,3,'west','secondary'),('bottle_shelf',4,1,3,'west','secondary'),('wall_sconce',0,2,3,'east'),('notice_board',0,1,2,'east')])
composition('forge_tools','WORKSHOP',[('oven_hearth',0,0,0,'south','primary'),('anvil',2,0,1,'north','primary',['WORKSTATION']),('work_table',5,0,0,'south','primary'),('work_table',6,0,0,'south','primary'),('tool_samples',5,1,0),('ore_crate',0,0,3,'south','secondary',['STORAGE']),('ore_crate',1,0,3,'south','secondary'),('tool_rack',0,1,2,'east'),('firewood',1,0,0),('crate',6,0,4,'west','secondary'),('tool_samples',6,1,4),('rug',4,0,2),('wall_sconce',6,2,2,'west')])
composition('pantry_full','PANTRY',[('food_pantry',0,0,0,'south','primary',['FOOD_STORAGE']),('food_pantry',1,0,0,'south','primary'),('wine_rack',3,0,0,'south','secondary',['DRINK_STORAGE']),('bottle_shelf',3,1,0,'south','secondary'),('crate',0,0,2,'east','secondary',['STORAGE']),('flour_sack',0,1,2),('produce_basket',1,0,2),('plate_stack',1,1,0),('hanging_herbs',0,2,2,'east'),('wall_sconce',3,2,2,'west')])
composition('guest_standard','INN_ROOM',bed(1,1)+[('bedside_table',2,0,1,'north','secondary'),('candle_holder',2,1,1),('wardrobe',0,0,3,'east','primary'),('folded_cloth',0,1,3),('storage_chest',4,0,0,'south','secondary',['GUEST_STORAGE']),('personal_belongings',4,1,0),('rug',2,0,3),('writing_desk',4,0,3,'west','secondary',['READING_POINT']),('wooden_stool',3,0,3,'east','secondary'),('book_stack',4,1,3),('wall_shelf',3,1,0,'south','secondary'),('flower_vase',3,2,0),('tapestry',0,1,1,'east'),('wall_sconce',4,2,4,'west')])
composition('guest_premium','INN_PREMIUM_ROOM',bed(1,1)+bed(2,1)+[('bedside_table',3,0,1,'north','secondary'),('candle_holder',3,1,1),('wardrobe',0,0,4,'east','primary'),('folded_cloth',0,1,4),('storage_chest',7,0,0,'south','secondary',['GUEST_STORAGE']),('medieval_table',5,0,3,'north','primary',['DINING_TABLE']),('armchair',4,0,3,'east','primary',['DINING_POINT']),('armchair',6,0,3,'west','primary',['DINING_POINT']),('idle_tableware',5,1,3),('wine_rack',7,0,4,'west','secondary'),('bottle_shelf',7,1,4,'west','secondary'),('medieval_bookshelf',0,0,0,'east','secondary',['READING_POINT']),('book_stack',0,1,0),('rug',2,0,3),('rug',3,0,3),('tapestry',7,1,2,'west'),('wall_sconce',0,2,2,'east')])
# Three deliberately distinct seating compositions, with an open aisle between groups.
rows=[]
for tx,tz,seat in [(2,2,'wooden_bench'),(7,2,'dining_chair'),(3,7,'tavern_stool')]:
 rows += [('dining_table',tx,0,tz,'north','primary',['DINING_TABLE']),('dining_table',tx,0,tz+1,'north','primary',['DINING_TABLE']),(seat,tx-1,0,tz,'east','primary',['DINING_POINT','TAVERN_SEAT']),('dining_chair',tx+1,0,tz,'west','primary',['DINING_POINT','TAVERN_SEAT']),(seat,tx-1,0,tz+1,'east','primary',['DINING_POINT','TAVERN_SEAT']),('dining_chair',tx+1,0,tz+1,'west','primary',['DINING_POINT','TAVERN_SEAT']),('idle_tableware',tx,1,tz),('bread_basket',tx,1,tz+1),('rug',tx,0,tz+2)]
rows += [('oven_hearth',0,0,5,'east','primary'),('firewood',0,0,6),('armchair',1,0,5,'west','secondary',['SOCIAL_POINT']),('rug',2,0,5),('coat_rack',10,0,9,'north','secondary'),('tapestry',0,1,3,'east'),('wall_sconce',0,2,8,'east'),('medieval_bookshelf',9,0,0,'south','secondary'),('book_stack',9,1,0),('notice_board',0,1,0,'east')]
composition('tavern_common_rustic','TAVERN_COMMON',rows)
composition('tavern_bar_crowned','TAVERN_BAR', [('bar_counter',x,0,2,'south','primary',['SHOP_COUNTER'] if x==3 else []) for x in range(7)]+[('keg',5,0,0,'south','secondary',['DRINK_STORAGE']),('keg',6,0,0,'south','secondary'),('bottle_shelf',1,1,0,'south','secondary'),('bottle_shelf',2,1,0,'south','secondary'),('mug_rack',3,1,0,'south','secondary'),('wine_rack',6,1,0,'south','secondary'),('serving_tray_prop',1,1,2),('mug_cluster',4,1,2),('candle_holder',6,1,2),('wall_sconce',0,2,0,'south')])
composition('tavern_card_gallery','CARD_WORLDS',[('dining_table',2,0,2,'north','primary',['DINING_TABLE','CARD_DUEL_TABLE']),('dining_table',3,0,2,'north','primary',['DINING_TABLE','CARD_DUEL_TABLE']),('dining_chair',2,0,1,'south','primary',['DINING_POINT','TAVERN_SEAT']),('dining_chair',3,0,3,'north','primary',['DINING_POINT','TAVERN_SEAT']),('card_set',2,1,2),('mug_cluster',3,1,2),('wooden_bench',5,0,2,'west','secondary',['SOCIAL_POINT']),('medieval_bookshelf',5,0,0,'south','secondary'),('card_set',5,1,0),('wine_rack',0,0,5,'east','secondary'),('rug',2,0,4),('tapestry',5,1,4,'west'),('wall_sconce',5,2,1,'west')])
composition('council_hall','COUNCIL_ROOM',[('throne',8,0,1,'south','primary',['WORKSTATION']),('dining_table',6,0,5,'north','primary',['DINING_TABLE']),('dining_table',7,0,5,'north','primary',['DINING_TABLE']),('dining_table',8,0,5,'north','primary',['DINING_TABLE']),('dining_chair',6,0,4,'south','primary',['DINING_POINT']),('dining_chair',8,0,4,'south','primary',['DINING_POINT']),('dining_chair',6,0,6,'north','primary',['DINING_POINT']),('dining_chair',8,0,6,'north','primary',['DINING_POINT']),('candle_holder',7,1,5),('paper_quill',6,1,5),('medieval_bookshelf',0,0,2,'east','secondary',['READING_POINT']),('medieval_bookshelf',0,0,3,'east','secondary'),('writing_desk',15,0,3,'west','secondary',['READING_POINT']),('paper_quill',15,1,3),('wooden_stool',14,0,3,'east','secondary'),('tapestry',3,1,0,'south'),('tapestry',12,1,0,'south'),('wall_sconce',0,2,7,'east'),('wall_sconce',15,2,7,'west')]+[('rug',8,0,z) for z in range(3,11)])
composition('hay_granary','AGRICULTURAL_STORAGE',[('hay_storage',x,0,z,'north','primary') for x in range(4) for z in range(3)]+[('crate',6,0,0,'south','secondary',['FOOD_STORAGE']),('crate',6,0,1,'south','secondary'),('flour_sack',6,1,0),('flour_sack',6,1,1),('work_table',0,0,6,'south','primary',['WORKSTATION']),('tool_samples',0,1,6),('tool_rack',0,1,4,'east'),('wall_sconce',6,2,4,'west')])
composition('stable_stalls','ANIMAL_STALL',[('hay_storage',0,0,0,'south','primary'),('water_pitcher',1,0,0),('wooden_bench',3,0,0,'south','secondary'),('tool_rack',3,1,4,'west'),('crate',3,0,6,'north','secondary',['STORAGE']),('flour_sack',3,1,6)])
B={}
def room(t,x,z,w,d,c,beds=0,floor=0):return dict(type=t,x=x,z=z,width=w,depth=d,floor=floor,composition=c,beds=beds)
def building(id,t,p,w,d,rooms,beds,roof='gable',floors=1,margin=4,ext=None):B[id]=dict(id=id,type=t,profession=p,width=w,depth=d,floors=floors,storey=5,roof=roof,beds=beds,lotMargin=margin,rooms=rooms,exterior=ext or ['domestic_yard'])
def house(id,w,d,roof,master,kitchen,dining,floors=1,beds=3):
 left=5;right=w-8;split=5;front=d-7
 rooms=[room('MASTER_BEDROOM',1,1,left,4,master,2),room('CHILD_BEDROOM',7,1,right,4,'shared_children' if beds==4 else 'child_reading',beds-2),room('KITCHEN',7,6,right,front,kitchen),room('DINING_LIVING',1,6,5,front,dining)]
 if floors==2:rooms += [room('STUDY',1,1,5,4,'dining_window',floor=1),room('LIVING_ROOM',7,1,right,4,'dining_hearth',floor=1)]
 building(id,'cottage','resident',w,d,rooms,beds,roof,floors)
for args in [('house_hearth',12,12,'gable','bedroom_hearthside','kitchen_larder','dining_hearth',1,3),('house_long',14,12,'gable_rotated','bedroom_window_desk','kitchen_window','dining_window',1,3),('house_crofter',12,15,'steep','bedroom_alcove','kitchen_larder','dining_window',1,4),('house_guild',14,13,'cross_gable','bedroom_window_desk','kitchen_window','dining_hearth',2,3),('house_noble',16,14,'hip','bedroom_alcove','kitchen_larder','dining_window',2,4),('farmstead',14,14,'steep','bedroom_hearthside','kitchen_larder','dining_window',1,4)]:house(*args)
B['farmstead'].update(type='farm',profession='farmer',lotMargin=7,exterior=['farm_yard'])
building('crowned_inn','tavern','innkeeper',24,21,[room('STAFF_BEDROOM',1,1,6,5,'bedroom_window_desk',2),room('PANTRY',8,1,5,4,'pantry_full'),room('TAVERN_KITCHEN',16,1,7,4,'kitchen_larder'),room('TAVERN_BAR',15,6,8,4,'tavern_bar_crowned'),room('TAVERN_COMMON',1,8,12,12,'tavern_common_rustic'),room('CARD_WORLDS',16,12,7,8,'tavern_card_gallery'),room('INN_ROOM',1,1,8,7,'guest_standard',floor=1),room('INN_PREMIUM_ROOM',10,1,13,7,'guest_premium',floor=1)],2,'cross_gable',2,6,['tavern_service','outdoor_dining','stable'])
building('smithy','forge','blacksmith',15,14,[room('WORKSHOP',1,1,8,6,'forge_tools'),room('PANTRY',10,1,4,5,'pantry_full'),room('MASTER_BEDROOM',1,8,5,5,'bedroom_alcove',2),room('DINING_LIVING',8,8,6,5,'dining_hearth')],2,'gable_rotated',1,5,['smith_yard'])
building('bakery','bakery','baker',14,14,[room('MASTER_BEDROOM',1,1,5,4,'bedroom_hearthside',2),room('KITCHEN',8,1,5,4,'kitchen_window'),room('SHOP',1,7,12,6,'shop_goods')],2,'cross_gable')
building('trading_hall','trading_post','merchant',17,15,[room('MASTER_BEDROOM',1,1,5,4,'bedroom_window_desk',2),room('PANTRY',9,1,7,4,'pantry_full'),room('SHOP',1,7,15,7,'shop_goods')],2,'gable_rotated',1,6,['cargo_yard','stable'])
building('civic_hall','civic','resident',20,17,[room('COUNCIL_ROOM',1,1,18,15,'council_hall'),room('MASTER_BEDROOM',1,1,6,5,'bedroom_alcove',2,1),room('LEADER_OFFICE',10,1,9,5,'dining_window',floor=1)],2,'steep',2,5,['civic_forecourt'])
building('guard_lodge','guardhouse','guard',14,13,[room('BARRACKS',1,1,5,4,'bedroom_window_desk',2),room('WORKSHOP',7,1,6,4,'shop_goods'),room('DINING_LIVING',1,6,5,6,'dining_window'),room('KITCHEN',8,6,5,6,'kitchen_larder')],2,'gable_rotated')
building('barn','barn','carpenter',19,14,[room('AGRICULTURAL_STORAGE',1,1,8,12,'hay_granary'),room('ANIMAL_STALL',12,1,6,12,'stable_stalls')],0,'steep',1,5,['farm_yard'])
building('market_hall','market','merchant',15,11,[room('SHOP',1,1,13,9,'shop_goods')],0,'open_gable',1,3,['market_stalls'])
# Spatial relationships are authored graphs. Planner adapts their placement to sampled terrain.
districts=[dict(id=i,kind=k,x=x,z=z,radius=r,density=d) for i,k,x,z,r,d in [('core','CIVIC',0,0,15,.85),('market','MARKET',12,13,14,.8),('west','RESIDENTIAL',-38,-22,30,.6),('east','RESIDENTIAL',40,-18,30,.55),('craft','CRAFT',-36,28,24,.65),('trade','TRADE',38,30,26,.65),('farm','AGRICULTURAL',0,72,55,.25),('pasture','LIVESTOCK',-45,82,28,.15),('approach','OUTSKIRTS',4,-78,14,.1)]]
links=[dict(**{'from':a,'to':b,'road':r}) for a,b,r in [('approach','core','REGIONAL_ROUTE'),('core','market','MAIN_STREET'),('core','west','SECONDARY_STREET'),('core','east','SECONDARY_STREET'),('core','craft','MAIN_STREET'),('core','trade','MAIN_STREET'),('craft','west','SECONDARY_STREET'),('trade','east','SECONDARY_STREET'),('core','farm','FARM_TRACK'),('farm','pasture','FARM_TRACK')]]
A={}
for id,lo,hi,cells,fields,eco,services in [('farming_village',34,40,64,6,['GRAIN','LIVESTOCK','WOODWORKING'],{'farmstead':2,'barn':2,'crowned_inn':1,'smithy':1,'bakery':1,'trading_hall':1,'civic_hall':1,'market_hall':1,'guard_lodge':1}),('market_town',44,52,24,3,['TRADE','CRAFT','REGIONAL_AGRICULTURE'],{'farmstead':1,'barn':1,'crowned_inn':1,'smithy':1,'bakery':1,'trading_hall':1,'civic_hall':1,'market_hall':1,'guard_lodge':1})]:A[id]=dict(id=id,minPopulation=lo,maxPopulation=hi,foodCellsPerPerson=cells,minFields=fields,economies=eco,districts=districts,links=links,services=services)
roads={id:dict(width=w,material=m,slopeCost=s,lighting=l) for id,w,m,s,l in [('REGIONAL_ROUTE',4,'coarse_dirt',8,False),('MAIN_STREET',3,'mixed_cobble',12,True),('SECONDARY_STREET',2,'dirt_path',10,True),('FARM_TRACK',2,'coarse_dirt',6,False),('FOOTPATH',1,'dirt_path',10,False)]}
D=dict(archetypes=A,roads=roads,buildings=B,compositions=C,residential={a:['house_hearth','house_long','house_crofter','house_guild','house_noble'] for a in A})
p=Path('src/main/resources/data/worldcomesalive/generation/v2.json');p.write_text(json.dumps(D,indent=2)+'\n')
