"""Reproducible built-in content, all consumed through the datapack reload listener."""
import json
from pathlib import Path
plots=[]
for x in [-30,-14,2,18]:
 plots.append(dict(type='cottage',profession='resident',x=x,z=-28,width=11,depth=11,beds=3,markers=['HOME','BED','STORAGE','DINING_POINT','OWNER_SLOT']))
for typ,job,x in [('farm','farmer',-30),('bakery','baker',-14),('forge','blacksmith',2),('tavern','innkeeper',18)]:
 plots.append(dict(type=typ,profession=job,x=x,z=12,width=11,depth=11,beds=2,markers=['HOME','BED','WORKSTATION','SHOP_COUNTER','CUSTOMER_POINT','STORAGE','OWNER_SLOT']+(['FARM_FIELD','STABLE','HORSE_OR_MOUNT_POINT'] if typ=='farm' else ['SOCIAL_POINT','TAVERN_SEAT','CARD_DUEL_TABLE','FESTIVAL_POINT'] if typ=='tavern' else [])))
plots.append(dict(type='guardhouse',profession='guard',x=-46,z=-8,width=11,depth=11,beds=2,markers=['HOME','BED','WORKSTATION','GUARD_POST','PATROL_POINT','STORAGE','OWNER_SLOT']))
plots.append(dict(type='guild_hall',profession='healer',x=34,z=-8,width=11,depth=11,beds=2,markers=['HOME','BED','WORKSTATION','SOCIAL_POINT','STORAGE','OWNER_SLOT']))
regions=[dict(id=i,biome=b,wood=w,stone=s,food=f,culture=c,faction=k) for i,b,w,s,f,c,k in [
 ('nordic','snow','spruce','stone_bricks',['salmon','potato'],['sagas','midwinter'],'winter_holds'),
 ('highland','windswept','spruce','cobblestone',['mutton'],['clans'],'highland_clans'),
 ('forest','forest','dark_oak','mossy_stone_bricks',['apple','mushroom_stew'],['woodland_fair'],'greenward'),
 ('coastal','beach','oak','stone_bricks',['cod'],['harvest_tide'],'crown'),
 ('mountain','peak','spruce','deepslate_bricks',['potato'],['craft_guilds'],'stone_council'),
 ('swamp','swamp','mangrove','mossy_cobblestone',['mushroom_stew'],['lantern_night'],'fenward'),
 ('desert','desert','acacia','cut_sandstone',['bread'],['market_day'],'sun_court'),
 ('temperate_kingdom','*','oak','stone_bricks',['bread','apple'],['harvest_fair'],'crown')]]
professions={i:dict(pokemon=p,pokemonRole=r,start=a,end=b,skill=s) for i,p,r,a,b,s in [
 ('resident','','',2000,9000,'crafting'),('farmer','wooloo','animal care',1000,9000,'farming'),('baker','fidough','baking',500,8000,'cooking'),('blacksmith','vulpix','forge heating',1500,9000,'smithing'),('innkeeper','eevee','companionship',5000,14000,'trading'),('guard','growlithe','patrol and tracking',0,12000,'combat'),('healer','chansey','medical care',2000,10000,'alchemy'),('hunter','rockruff','tracking',1000,9000,'hunting'),('fisher','buizel','fishing',500,8000,'fishing'),('logger','timburr','carrying timber',1000,9000,'crafting'),('miner','drilbur','mining',1000,9000,'mining')]}
actions=[dict(id=i,requires=r,adds=e,cost=c,execution=x) for i,r,e,c,x in [
 ('flee',['alive'],['safe'],1,'guard'),('go_home',['alive'],['home'],2,'home'),('sleep',['home'],['rested'],1,'sleep'),
 ('visit_market',['shop_open'],['market'],2,'market'),('buy_food',['market'],['food'],2,'buy'),('gather_food',['can_gather'],['food'],5,'gather'),('eat',['food'],['nourished'],1,'eat'),
 ('go_work',['alive'],['workplace'],2,'work'),('produce',['workplace'],['worked'],2,'produce'),('visit_tavern',['alive'],['tavern'],2,'tavern'),('converse',['tavern'],['social'],2,'social'),('train_partner',['alive'],['trained'],3,'train')]]
def line(i,topic,text,profession='*',activity='*',minTrust=-100,memory='',season='*',weather='*'):
 return dict(id=i,topic=topic,profession=profession,activity=activity,minTrust=minTrust,memory=memory,season=season,weather=weather,text=text)
dialogue=[line('welcome','talk','Welcome to {settlement}. The {faction} keeps these roads safe. I am {name}, the {profession}.'),line('work','talk','I am {activity}. Our household lives in {home}; come by after my shift.',activity='working'),line('social','talk','A warm hearth, good company and a game of cards. That is what keeps {settlement} alive.',activity='socializing'),line('guard','talk','My Growlithe helps me patrol the roads. Report trouble to the watch.',profession='guard'),line('farmer','talk','My Wooloo and I tend the fields. The bakery depends on our wheat.',profession='farmer'),line('baker','talk','Fresh bread for the village. If the roads close, flour gets scarce.',profession='baker'),line('smith','talk','Vulpix keeps the forge hot. Tools, repairs and honest work.',profession='blacksmith'),line('inn','talk','Our card night begins after the work bell. Bring a deck and a friendly spirit.',profession='innkeeper'),line('saved','talk','I remember the help you gave our household. You have earned my trust.',minTrust=15,memory='helped'),line('assault','talk','Keep your distance. I remember what you did.',memory='assault'),line('rain','talk','This rain makes the road heavy. Travellers will be late.',weather='rain'),line('greet','greet','Good day, {player}. May the road treat you kindly.'),line('ask','ask','We have a bakery, a forge, a watch and a tavern. Our roads connect homes to work. Ask the innkeeper about cards.'),line('gift','gift','You thought of me. Thank you, {player}.'),line('flirt','flirt','Trust takes time. Let us get to know one another first.'),line('invite','invite','Find me at the tavern when the workday ends.'),line('help','help','The village always needs willing hands. Thank you for helping.'),line('cards','cards','I keep my own deck. A friendly game sounds good.'),line('rob','rob','Guards! Someone is threatening me!')]
archetypes=[dict(id='village',plots=plots),dict(id='farming_hamlet',plots=[plots[0],plots[1],plots[4],plots[7],plots[8]]),dict(id='trading_post',plots=[plots[0],plots[5],plots[6],plots[7],plots[8]]),dict(id='town',plots=plots+[dict(plots[0],x=-30,z=-46),dict(plots[1],x=-14,z=-46)])]
# Further location families use the same semantic template machinery, with capacity and profession derived from plots.
for ident,typ,job,beds in [('ranch','farm','farmer',4),('isolated_cottage','cottage','resident',2),('hunter_cabin','cottage','hunter',2),('fishing_settlement','farm','fisher',4),('roadside_inn','tavern','innkeeper',4),('mining_settlement','forge','miner',4),('logging_camp','guild_hall','logger',4),('military_outpost','guardhouse','guard',4),('guild_hall','guild_hall','blacksmith',4),('monastery','guild_hall','healer',4),('keep','guardhouse','guard',4),('wilderness_camp','cottage','hunter',2)]:
 archetypes.append(dict(id=ident,plots=[dict(plots[7 if typ=='tavern' else 8 if typ=='guardhouse' else 4 if typ=='farm' else 9 if typ=='guild_hall' else 0],type=typ,profession=job,x=-5,z=10,beds=beds)]))
content=dict(firstNames=['Alden','Brina','Cedric','Dara','Edric','Freya','Gareth','Hilda','Ivor','Jora','Kael','Lyra','Merrin','Nora','Oren','Petra','Quinn','Rhea','Soren','Talia','Ulric','Vera','Wren','Yara'],lastNames=['Ashford','Briar','Cooper','Dunholm','Ember','Fairbrook','Greymere','Hart','Ironwood','Kestrel','Miller','Oakheart','Reed','Stone','Thorn','Winter'],traits=['aggression','bravery','greed','kindness','sociability','honesty','loyalty','curiosity','ambition','patience','risk_tolerance'],regions=regions,archetypes=archetypes,professions=professions,actions=actions,dialogue=dialogue,recipes=[dict(profession='farmer',input='',consumed=0,output='minecraft:wheat',produced=6,wage=2),dict(profession='baker',input='minecraft:wheat',consumed=3,output='minecraft:bread',produced=2,wage=3),dict(profession='blacksmith',input='minecraft:iron_ingot',consumed=1,output='minecraft:iron_nugget',produced=9,wage=3)],events=[dict(type='festival',duration=6000,chance=.20),dict(type='route_damage',duration=18000,chance=.10),dict(type='shortage',duration=12000,chance=.12),dict(type='pokemon_outbreak',duration=9000,chance=.08)],gifts=[dict(tag='food',profession='*',value=3,need='hunger'),dict(tag='tool',profession='blacksmith',value=4,need=''),dict(tag='flower',profession='*',value=2,need='loneliness'),dict(tag='pokemon',profession='farmer',value=4,need='')],regionChunks=24,relevance=80)
Path('src/main/resources/data/worldcomesalive/living_world/default.json').write_text(json.dumps(content,indent=2)+'\n')
