package vn.svframe.svrelationships.fabric.gui;

import org.yaml.snakeyaml.LoaderOptions;
import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.constructor.SafeConstructor;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.atomic.AtomicReference;
import java.util.stream.Stream;

public final class GuiDefinitionService {
    private final Path directory;
    private final AtomicLong generation = new AtomicLong();
    private final AtomicReference<Snapshot> current = new AtomicReference<>(new Snapshot(0, Map.of()));

    public GuiDefinitionService(Path root) {
        this.directory = Objects.requireNonNull(root, "root").resolve("gui");
    }

    public ReloadResult reload() {
        try {
            if (!Files.isDirectory(directory)) {
                throw new IllegalArgumentException("GUI directory does not exist: " + directory);
            }

            Map<String, GuiDefinition> definitions = new LinkedHashMap<>();
            try (Stream<Path> paths = Files.list(directory)) {
                for (Path path : paths
                        .filter(p -> p.getFileName().toString().endsWith(".yml"))
                        .sorted()
                        .toList()) {
                    GuiDefinition definition = parse(load(path));
                    if (definitions.putIfAbsent(definition.id(), definition) != null) {
                        throw new IllegalArgumentException("Duplicate GUI id: " + definition.id());
                    }
                }
            }

            current.set(new Snapshot(generation.incrementAndGet(), definitions));
            return new ReloadResult(true, "");
        } catch (Exception exception) {
            return new ReloadResult(false, exception.getClass().getSimpleName() + ": " + exception.getMessage());
        }
    }

    public Snapshot snapshot() {
        return current.get();
    }

    private GuiDefinition parse(Map<String, Object> root) {
        String id = string(root, "id");
        String screen = string(root, "screen");
        String titleKey = string(root, "title_key");
        int capacity = screenCapacity(screen);

        Map<String, ComponentDefinition> components = new LinkedHashMap<>();
        for (var entry : map(root, "components").entrySet()) {
            Map<String, Object> value = mapValue(entry.getValue(), "component " + entry.getKey());
            int slot = integer(value, "slot");
            validateSlot(id, slot, capacity);
            components.put(entry.getKey(), new ComponentDefinition(
                    entry.getKey(),
                    slot,
                    string(value, "item"),
                    string(value, "name_key"),
                    stringList(value, "lore_keys"),
                    string(value, "action"),
                    stringMap(value, "args"),
                    stringMap(value, "conditions")
            ));
        }

        Map<String, RepeaterDefinition> repeaters = new LinkedHashMap<>();
        for (var entry : map(root, "repeaters").entrySet()) {
            Map<String, Object> value = mapValue(entry.getValue(), "repeater " + entry.getKey());
            List<Integer> slots = integerList(value, "slots");
            if (slots.isEmpty()) {
                throw new IllegalArgumentException("Repeater has no slots: " + entry.getKey());
            }
            for (int slot : slots) {
                validateSlot(id, slot, capacity);
                if (components.values().stream().anyMatch(component -> component.slot() == slot)) {
                    throw new IllegalArgumentException("Repeater slot overlaps static component in GUI " + id + ": " + slot);
                }
            }

            String source = string(value, "source");
            String visual = optionalString(value, "visual", defaultVisualForSource(source));
            if (!visual.equals("item") && !visual.equals("pokemon_model")) {
                throw new IllegalArgumentException("Unsupported repeater visual '" + visual + "' in GUI " + id);
            }

            repeaters.put(entry.getKey(), new RepeaterDefinition(
                    entry.getKey(),
                    slots,
                    source,
                    visual,
                    string(value, "item"),
                    string(value, "name_key"),
                    stringList(value, "lore_keys"),
                    string(value, "action"),
                    stringMap(value, "args"),
                    stringMap(value, "conditions")
            ));
        }

        return new GuiDefinition(id, screen, titleKey, components, repeaters);
    }

    /**
     * Compatibility migration for GUI files generated by pre-model builds.
     * Those builds used placeholder item icons for Pokémon collections. The
     * explicit `visual` key always wins, so admins can still choose `item`.
     */
    private static String defaultVisualForSource(String source) {
        return switch (source) {
            case "owned_pokemon", "partners" -> "pokemon_model";
            default -> "item";
        };
    }

    private Map<String, Object> load(Path path) throws IOException {
        try (InputStream input = Files.newInputStream(path)) {
            return mapValue(
                    new Yaml(new SafeConstructor(new LoaderOptions())).load(input),
                    path.getFileName().toString()
            );
        }
    }

    private static void validateSlot(String id, int slot, int capacity) {
        if (slot < 0 || slot >= capacity) {
            throw new IllegalArgumentException("Invalid slot " + slot + " in GUI " + id + " with capacity " + capacity);
        }
    }

    private static int screenCapacity(String id) {
        return switch (id) {
            case "generic_9x1" -> 9;
            case "generic_9x2" -> 18;
            case "generic_9x3" -> 27;
            case "generic_9x4" -> 36;
            case "generic_9x5" -> 45;
            case "hopper" -> 5;
            case "generic_3x3" -> 9;
            default -> 54;
        };
    }

    private static Map<String, Object> map(Map<String, Object> source, String key) {
        Object value = source.get(key);
        return value == null ? Map.of() : mapValue(value, key);
    }

    private static Map<String, Object> mapValue(Object value, String label) {
        if (value == null) {
            return Map.of();
        }
        if (!(value instanceof Map<?, ?> raw)) {
            throw new IllegalArgumentException("Expected map at " + label);
        }
        Map<String, Object> result = new LinkedHashMap<>();
        raw.forEach((key, item) -> result.put(String.valueOf(key), item));
        return result;
    }

    private static String string(Map<String, Object> source, String key) {
        Object value = source.get(key);
        if (value == null) {
            throw new IllegalArgumentException("Missing GUI key: " + key);
        }
        return String.valueOf(value);
    }

    private static String optionalString(Map<String, Object> source, String key, String fallback) {
        Object value = source.get(key);
        return value == null ? fallback : String.valueOf(value);
    }

    private static int integer(Map<String, Object> source, String key) {
        Object value = source.get(key);
        return value instanceof Number number ? number.intValue() : Integer.parseInt(string(source, key));
    }

    private static List<String> stringList(Map<String, Object> source, String key) {
        Object value = source.get(key);
        if (value == null) {
            return List.of();
        }
        if (!(value instanceof List<?> list)) {
            throw new IllegalArgumentException("Expected list at " + key);
        }
        return list.stream().map(String::valueOf).toList();
    }

    private static List<Integer> integerList(Map<String, Object> source, String key) {
        Object value = source.get(key);
        if (value == null) {
            return List.of();
        }
        if (!(value instanceof List<?> list)) {
            throw new IllegalArgumentException("Expected list at " + key);
        }
        List<Integer> result = new ArrayList<>();
        for (Object item : list) {
            result.add(item instanceof Number number ? number.intValue() : Integer.parseInt(String.valueOf(item)));
        }
        return List.copyOf(result);
    }

    private static Map<String, String> stringMap(Map<String, Object> source, String key) {
        Object value = source.get(key);
        if (value == null) {
            return Map.of();
        }
        Map<String, Object> raw = mapValue(value, key);
        Map<String, String> result = new LinkedHashMap<>();
        raw.forEach((name, item) -> result.put(name, String.valueOf(item)));
        return result;
    }

    public record Snapshot(long generation, Map<String, GuiDefinition> definitions) {
        public Snapshot {
            definitions = Map.copyOf(definitions);
        }
    }

    public record GuiDefinition(
            String id,
            String screen,
            String titleKey,
            Map<String, ComponentDefinition> components,
            Map<String, RepeaterDefinition> repeaters
    ) {
        public GuiDefinition {
            components = Map.copyOf(components);
            repeaters = Map.copyOf(repeaters);
        }
    }

    public record ComponentDefinition(
            String id,
            int slot,
            String itemId,
            String nameKey,
            List<String> loreKeys,
            String action,
            Map<String, String> args,
            Map<String, String> conditions
    ) {
        public ComponentDefinition {
            loreKeys = List.copyOf(loreKeys);
            args = Map.copyOf(args);
            conditions = Map.copyOf(conditions);
        }
    }

    public record RepeaterDefinition(
            String id,
            List<Integer> slots,
            String source,
            String visual,
            String itemId,
            String nameKey,
            List<String> loreKeys,
            String action,
            Map<String, String> args,
            Map<String, String> conditions
    ) {
        public RepeaterDefinition {
            slots = List.copyOf(slots);
            loreKeys = List.copyOf(loreKeys);
            args = Map.copyOf(args);
            conditions = Map.copyOf(conditions);
        }
    }

    public record ReloadResult(boolean success, String detail) {}
}
