package vn.svframe.mmocorefabric.runtime.persistence;
import java.io.*;import java.nio.file.*;import java.util.*;import vn.svframe.mmocorefabric.runtime.gameplay.*;import vn.svframe.mmocorefabric.runtime.progression.PlayerProgress;
public final class MMOCoreProfileStore {
 private static final int MAGIC=0x4d4d4f43,VERSION=1; private final Path directory;
 public record Profile(PlayerProgress progress,String classId,Map<String,ProfessionRuntime.State> professions,Map<String,QuestRuntime.Snapshot> quests){public Profile{classId=classId==null?"":classId;professions=Map.copyOf(professions);quests=Map.copyOf(quests);}}
 public MMOCoreProfileStore(Path directory){this.directory=directory;}
 public Profile load(UUID id)throws IOException{Path file=file(id);PlayerProgress p=new PlayerProgress();if(!Files.exists(file))return new Profile(p,"",Map.of(),Map.of());try(DataInputStream in=new DataInputStream(new BufferedInputStream(Files.newInputStream(file)))){if(in.readInt()!=MAGIC)throw new IOException("invalid MMOCore profile magic");int v=in.readInt();if(v!=VERSION)throw new IOException("unsupported MMOCore profile version "+v);int level=in.readInt();double exp=in.readDouble();int sp=in.readInt(),ap=in.readInt();Map<String,Integer> skills=readStringIntMap(in,8192),attrs=readStringIntMap(in,8192);int bc=bounded(in.readInt(),0,9,"binding count");Map<Integer,String> bindings=new HashMap<>();for(int i=0;i<bc;i++)bindings.put(in.readInt(),in.readUTF());int fc=bounded(in.readInt(),0,100000,"friend count");Set<UUID> friends=new HashSet<>();for(int i=0;i<fc;i++)friends.add(new UUID(in.readLong(),in.readLong()));p.restore(level,exp,sp,ap,skills,attrs,bindings,friends);String classId=in.readUTF();int pc=bounded(in.readInt(),0,4096,"profession count");Map<String,ProfessionRuntime.State> professions=new HashMap<>();for(int i=0;i<pc;i++)professions.put(in.readUTF(),new ProfessionRuntime.State(in.readInt(),in.readDouble()));int qc=bounded(in.readInt(),0,16384,"quest count");Map<String,QuestRuntime.Snapshot> quests=new HashMap<>();for(int i=0;i<qc;i++){String q=in.readUTF();QuestRuntime.Status status=QuestRuntime.Status.valueOf(in.readUTF());long until=in.readLong();Map<String,Integer> progress=readStringIntMap(in,4096);quests.put(q,new QuestRuntime.Snapshot(status,progress,until));}try{in.readByte();throw new IOException("trailing profile bytes");}catch(EOFException expected){}return new Profile(p,classId,professions,quests);}}
 public void save(UUID id,Profile profile)throws IOException{Files.createDirectories(directory);Path target=file(id),temp=target.resolveSibling(target.getFileName()+".tmp");PlayerProgress p=profile.progress();try(DataOutputStream out=new DataOutputStream(new BufferedOutputStream(Files.newOutputStream(temp)))){out.writeInt(MAGIC);out.writeInt(VERSION);out.writeInt(p.level());out.writeDouble(p.exp());out.writeInt(p.skillPoints());out.writeInt(p.attributePoints());writeStringIntMap(out,p.skills());writeStringIntMap(out,p.attributes());out.writeInt(p.bindings().size());for(var e:new TreeMap<>(p.bindings()).entrySet()){out.writeInt(e.getKey());out.writeUTF(e.getValue());}List<UUID> friends=new ArrayList<>(p.friends());friends.sort(Comparator.comparing(UUID::toString));out.writeInt(friends.size());for(UUID f:friends){out.writeLong(f.getMostSignificantBits());out.writeLong(f.getLeastSignificantBits());}out.writeUTF(profile.classId());List<String> pk=new ArrayList<>(profile.professions().keySet());Collections.sort(pk);out.writeInt(pk.size());for(String k:pk){var s=profile.professions().get(k);out.writeUTF(k);out.writeInt(s.level());out.writeDouble(s.exp());}List<String> qk=new ArrayList<>(profile.quests().keySet());Collections.sort(qk);out.writeInt(qk.size());for(String k:qk){var s=profile.quests().get(k);out.writeUTF(k);out.writeUTF(s.status().name());out.writeLong(s.cooldownUntil());writeStringIntMap(out,s.progress());}}
  try{Files.move(temp,target,StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException ignored){Files.move(temp,target,StandardCopyOption.REPLACE_EXISTING);}}
 private Path file(UUID id){return directory.resolve(id.toString()+".bin");}
 private static void writeStringIntMap(DataOutputStream out,Map<String,Integer> map)throws IOException{List<String> keys=new ArrayList<>(map.keySet());Collections.sort(keys);out.writeInt(keys.size());for(String key:keys){out.writeUTF(key);out.writeInt(map.get(key));}}
 private static Map<String,Integer> readStringIntMap(DataInputStream in,int max)throws IOException{int n=bounded(in.readInt(),0,max,"map size");Map<String,Integer> out=new HashMap<>();for(int i=0;i<n;i++){String k=in.readUTF();int v=in.readInt();if(v<0)throw new IOException("negative persisted value");out.put(k,v);}return out;}
 private static int bounded(int v,int min,int max,String what)throws IOException{if(v<min||v>max)throw new IOException("invalid "+what+": "+v);return v;}
}
