package vn.svframe.mmocorefabric.runtime.gameplay;
import java.util.*;
public final class QuestRuntime {
 public enum Status{LOCKED,AVAILABLE,ACTIVE,COMPLETE,COOLDOWN}
 public record Objective(String id,int required){public Objective{if(required<1)throw new IllegalArgumentException();}}
 public record Definition(String id,String parent,int minLevel,String profession,int professionLevel,long cooldownMillis,List<Objective> objectives){public Definition{id=norm(id);parent=parent==null?"":norm(parent);profession=profession==null?"":norm(profession);objectives=List.copyOf(objectives);}}
 public record Snapshot(Status status,Map<String,Integer> progress,long cooldownUntil){public Snapshot{progress=Map.copyOf(progress);}}
 public static final class State{private Status status=Status.AVAILABLE;private final Map<String,Integer> progress=new HashMap<>();private long cooldownUntil;public Status status(long now){if(status==Status.COOLDOWN&&now>=cooldownUntil)status=Status.AVAILABLE;return status;}public Map<String,Integer> progress(){return Map.copyOf(progress);}private Snapshot snapshot(){return new Snapshot(status,progress,cooldownUntil);}private void restore(Snapshot s){status=s.status();progress.clear();progress.putAll(s.progress());cooldownUntil=s.cooldownUntil();}}
 private final Map<String,Definition> defs=new LinkedHashMap<>();private final Map<UUID,Map<String,State>> states=new HashMap<>();
 public synchronized void register(Definition d){defs.put(d.id(),d);} public synchronized void clearDefinitions(){defs.clear();} public synchronized Map<String,Definition> definitions(){return Map.copyOf(defs);} public synchronized State state(UUID p,String id){require(id);return states.computeIfAbsent(p,x->new HashMap<>()).computeIfAbsent(norm(id),x->new State());}
 public synchronized boolean start(UUID p,String id,int level,java.util.function.ToIntFunction<String> professionLevel,long now){Definition d=require(id);State s=state(p,id);if(s.status(now)!=Status.AVAILABLE)return false;if(level<d.minLevel())return false;if(!d.parent().isEmpty()&&state(p,d.parent()).status(now)!=Status.COMPLETE)return false;if(!d.profession().isEmpty()&&professionLevel.applyAsInt(d.profession())<d.professionLevel())return false;s.status=Status.ACTIVE;s.progress.clear();return true;}
 public synchronized boolean progress(UUID p,String id,String objective,int amount,long now){Definition d=require(id);State s=state(p,id);if(s.status(now)!=Status.ACTIVE||amount<=0)return false;Objective o=d.objectives().stream().filter(x->x.id().equalsIgnoreCase(objective)).findFirst().orElse(null);if(o==null)return false;s.progress.merge(o.id(),amount,(a,b)->Math.min(o.required(),a+b));boolean done=d.objectives().stream().allMatch(x->s.progress.getOrDefault(x.id(),0)>=x.required());if(done)s.status=Status.COMPLETE;return done;}
 public synchronized void finish(UUID p,String id,long now){Definition d=require(id);State s=state(p,id);if(s.status(now)!=Status.COMPLETE)throw new IllegalStateException();if(d.cooldownMillis()>0){s.status=Status.COOLDOWN;s.cooldownUntil=now+d.cooldownMillis();}}
 public synchronized void cancel(UUID p,String id){State s=state(p,id);s.status=Status.AVAILABLE;s.progress.clear();}
 public synchronized Map<String,Snapshot> snapshot(UUID p){Map<String,Snapshot> out=new HashMap<>();states.getOrDefault(p,Map.of()).forEach((k,v)->out.put(k,v.snapshot()));return Map.copyOf(out);} public synchronized void restore(UUID p,Map<String,Snapshot> snapshot){if(snapshot.isEmpty()){states.remove(p);return;}Map<String,State> out=new HashMap<>();snapshot.forEach((k,v)->{State s=new State();s.restore(v);out.put(norm(k),s);});states.put(p,out);} public synchronized void forget(UUID p){states.remove(p);}
 private Definition require(String id){Definition d=defs.get(norm(id));if(d==null)throw new IllegalArgumentException("unknown quest "+id);return d;}private static String norm(String s){return Objects.requireNonNull(s).trim().toLowerCase(Locale.ROOT);}
}
