package vn.svarcade.tcg.performance;
import org.junit.jupiter.api.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
import static org.junit.jupiter.api.Assertions.*;
class AsyncRaceTest {
 @Test void staleEndedAndDisconnectedAiNeverCommits(){for(boolean live:List.of(true,false)){var task=new AsyncDerivedTask<String>();var f=new CompletableFuture<String>();task.begin(10,f);f.complete("action");assertNull(task.take(live?11:10,live));assertFalse(task.pending());}}
 @Test void obsoleteAiStillOwnsItsSlotUntilComputationFinishes(){var task=new AsyncDerivedTask<String>();var pending=new CompletableFuture<String>();task.begin(1,pending);task.cancel();assertTrue(task.pending());assertThrows(IllegalStateException.class,()->task.begin(2,new CompletableFuture<>()));assertNull(task.take(2,true));pending.complete("obsolete");assertNull(task.take(2,true));assertFalse(task.pending());var current=CompletableFuture.completedFuture("current");task.begin(2,current);assertEquals("current",task.take(2,true));}
 @Test void lateSnapshotCannotOverwriteNewerRevision()throws Exception{try(var workers=new CardWorldsExecutors(PerformanceConfig.defaults())){var entered=new CountDownLatch(1);var release=new CountDownLatch(1);var pipeline=new CoalescingPipeline<String,Integer,Integer>(workers,CardWorldsExecutors.Kind.SERIALIZATION,n->{if(n==1){entered.countDown();try{release.await();}catch(InterruptedException e){throw new RuntimeException(e);}}return n;},(a,b)->b);List<Integer> committed=new ArrayList<>();pipeline.offer("duel",1,1);pipeline.poll((k,v)->committed.add(v),(k,e)->fail(e));assertTrue(entered.await(5,TimeUnit.SECONDS));pipeline.offer("duel",2,2);release.countDown();long end=System.nanoTime()+TimeUnit.SECONDS.toNanos(5);while(pipeline.owners()>0&&System.nanoTime()<end){pipeline.poll((k,v)->committed.add(v),(k,e)->fail(e));Thread.yield();}assertEquals(List.of(2),committed);}}
 @Test void disconnectCancelsDerivedWorkAndDoesNotSend()throws Exception{try(var workers=new CardWorldsExecutors(PerformanceConfig.defaults())){var gate=new CountDownLatch(1);var started=new CountDownLatch(1);var pipeline=new CoalescingPipeline<String,Integer,Integer>(workers,CardWorldsExecutors.Kind.CPU,n->{started.countDown();try{gate.await();}catch(Exception e){throw new RuntimeException(e);}return n;},(a,b)->b);pipeline.offer("player",1,1);pipeline.poll((k,v)->fail("Unexpected commit"),(k,e)->fail(e));assertTrue(started.await(5,TimeUnit.SECONDS));pipeline.cancel("player");gate.countDown();pipeline.poll((k,v)->fail("Disconnected player must not receive result"),(k,e)->fail(e));assertEquals(0,pipeline.owners());}}
 @Test void boundedQueueUsesExplicitCorrectFallbackAndDrains()throws Exception{var c=new PerformanceConfig(1,1,1,1,1,1,true,false);try(var workers=new CardWorldsExecutors(c)){var release=new CountDownLatch(1);var entered=new CountDownLatch(1);var running=workers.submit(CardWorldsExecutors.Kind.CPU,new CardWorldsExecutors.Context("blocked","a",1),()->{entered.countDown();try{release.await();}catch(Exception e){throw new RuntimeException(e);}return 1;});assertTrue(entered.await(5,TimeUnit.SECONDS));var queued=workers.submit(CardWorldsExecutors.Kind.CPU,new CardWorldsExecutors.Context("queued","b",1),()->2);var fallback=workers.submit(CardWorldsExecutors.Kind.CPU,new CardWorldsExecutors.Context("backpressure","c",1),()->3);assertEquals(3,fallback.join());assertTrue(workers.pending(CardWorldsExecutors.Kind.CPU)<=1);assertEquals(1,workers.backpressure(CardWorldsExecutors.Kind.CPU));release.countDown();assertEquals(1,running.get());assertEquals(2,queued.get());}assertTrue(Thread.getAllStackTraces().keySet().stream().noneMatch(t->t.isAlive()&&t.getName().startsWith("cardworlds-")));}
 @Test void failedWorkerFallsBackOnOwnerThread(){try(var workers=new CardWorldsExecutors(PerformanceConfig.defaults())){var pipeline=new CoalescingPipeline<String,Integer,Integer>(workers,CardWorldsExecutors.Kind.CPU,n->{if(Thread.currentThread().getName().startsWith("cardworlds-"))throw new IllegalStateException("fixture worker failure");return n;},(a,b)->b);AtomicInteger result=new AtomicInteger(),errors=new AtomicInteger();pipeline.offer("a",1,7);long end=System.nanoTime()+TimeUnit.SECONDS.toNanos(5);while(pipeline.owners()>0&&System.nanoTime()<end){pipeline.poll((k,v)->result.set(v),(k,e)->errors.incrementAndGet());Thread.yield();}assertEquals(7,result.get());assertEquals(1,errors.get());}}
 @Test void resourceGenerationUsesNewIndexWithoutChangingOldDefinitions()throws Exception{var old=vn.svarcade.tcg.data.Catalog.load(java.nio.file.Path.of("absent-race-catalog.json"));var first=CatalogIndex.of(old.cards());var next=new LinkedHashMap<>(old.cards());next.remove("charmander");var second=CatalogIndex.of(Collections.unmodifiableMap(next));assertNotSame(first,second);assertTrue(first.byName.containsKey("Charmander"));assertFalse(second.byName.containsKey("Charmander"));assertThrows(UnsupportedOperationException.class,()->old.cards().clear());}
}
