package vn.svarcade.tcg.performance;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import vn.svarcade.tcg.data.*;
import vn.svarcade.tcg.economy.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
import static org.junit.jupiter.api.Assertions.*;
class EconomyConcurrencyTest {
 @TempDir Path temp;
 @Test void uiReadersDoNotTakeWriterMonitorAndInvalidationUsesCommittedRevision()throws Exception{var catalog=Catalog.load(temp.resolve("read-data.json"));try(var store=new CardStore(temp.resolve("readers.db"),catalog,new Random(1));var workers=new CardWorldsExecutors(PerformanceConfig.defaults())){store.createProfile("player","crossroads");CardStore.UiData first;synchronized(store){first=workers.submit(CardWorldsExecutors.Kind.IO,new CardWorldsExecutors.Context("read-monitor","player",store.dataRevision()),()->store.uiData("player",0)).get(5,TimeUnit.SECONDS);}assertEquals(store.profile("player"),first.profile());assertSame(first,store.uiData("player",0));store.createProfile("second","crossroads");var next=store.uiData("player",0);assertTrue(next.revision()>first.revision());assertNotSame(first,next);assertEquals(first.counts(),next.counts());}}
 @Test void concurrentRewardsPayExactlyOnceAndSurviveRestart()throws Exception{AtomicInteger paid=new AtomicInteger();try(var journal=new RewardReceiptJournal(temp.resolve("receipts.db"),temp.resolve("legacy.txt"));var workers=new CardWorldsExecutors(PerformanceConfig.defaults())){var a=workers.submit(CardWorldsExecutors.Kind.CPU,new CardWorldsExecutors.Context("reward-race","match",1),()->journal.payOnce("match|player|beastcoin|50",paid::incrementAndGet));var b=workers.submit(CardWorldsExecutors.Kind.CPU,new CardWorldsExecutors.Context("reward-race","match",1),()->journal.payOnce("match|player|beastcoin|50",paid::incrementAndGet));assertNotEquals(a.get(),b.get());assertEquals(1,paid.get());}try(var journal=new RewardReceiptJournal(temp.resolve("receipts.db"),temp.resolve("legacy.txt"))){assertFalse(journal.payOnce("match|player|beastcoin|50",paid::incrementAndGet));assertEquals(1,paid.get());}}
 @Test void concurrentPullReceiptHasOneDebitAndOneAward()throws Exception{var catalog=Catalog.load(temp.resolve("absent.json"));try(var store=new CardStore(temp.resolve("cards.db"),catalog,new Random(31));var workers=new CardWorldsExecutors(PerformanceConfig.defaults())){store.createProfile("player","crossroads");AtomicInteger debits=new AtomicInteger(),refunds=new AtomicInteger();java.util.function.Supplier<List<CardStore.Pull>> action=()->EconomyTransactions.pull("player","beastcoin:race",()->store.hasReceipt("player","beastcoin:race"),debits::incrementAndGet,()->store.pull("player","crossroads","beastcoin:race",1),refunds::incrementAndGet);var a=workers.submit(CardWorldsExecutors.Kind.CPU,new CardWorldsExecutors.Context("pull-race","p",1),action);var b=workers.submit(CardWorldsExecutors.Kind.CPU,new CardWorldsExecutors.Context("pull-race","p",1),action);assertEquals(a.get(),b.get());assertEquals(1,debits.get());assertEquals(0,refunds.get());assertEquals(catalog.banners().get("crossroads").slots(),a.get().size());assertEquals(40+catalog.banners().get("crossroads").slots(),store.profile("player").owned());assertEquals(2000,store.profile("player").coins());}}
 @Test void failedPullRefundsOnceAndDoesNotLeaveReceipt()throws Exception{AtomicInteger charged=new AtomicInteger(),refunded=new AtomicInteger();assertThrows(IllegalArgumentException.class,()->EconomyTransactions.pull("p","receipt",()->false,charged::incrementAndGet,()->{throw new IllegalArgumentException("transaction failure");},refunded::incrementAndGet));assertEquals(1,charged.get());assertEquals(1,refunded.get());}
 @Test void uncertainExternalPayoutRemainsExplicitAndNeverDuplicates()throws Exception{AtomicInteger calls=new AtomicInteger();try(var journal=new RewardReceiptJournal(temp.resolve("uncertain.db"),temp.resolve("old.txt"))){assertThrows(IllegalStateException.class,()->journal.payOnce("uncertain",()->{calls.incrementAndGet();throw new IllegalStateException("External API outcome unknown");}));}try(var journal=new RewardReceiptJournal(temp.resolve("uncertain.db"),temp.resolve("old.txt"))){var e=assertThrows(IllegalStateException.class,()->journal.payOnce("uncertain",calls::incrementAndGet));assertTrue(e.getMessage().contains("requires reconciliation"));assertEquals(1,calls.get());}}
 @Test void legacyReceiptsMigrateAndPreferencesFlushOnShutdown()throws Exception{Files.writeString(temp.resolve("old.txt"),"paid-receipt\n");try(var journal=new RewardReceiptJournal(temp.resolve("migrate.db"),temp.resolve("old.txt"))){assertFalse(journal.payOnce("paid-receipt",()->fail("Legacy reward was already paid")));}try(var workers=new CardWorldsExecutors(PerformanceConfig.defaults());var queue=new PersistenceQueue<Path,List<String>>(workers,(path,values)->{try{Files.write(path,values);}catch(Exception e){throw new RuntimeException(e);}})){queue.put(temp.resolve("favorites"),List.of("old"));queue.poll();queue.put(temp.resolve("favorites"),List.of("new"));}assertEquals(List.of("new"),Files.readAllLines(temp.resolve("favorites")));}
}
