package vn.svarcade.tcg.duel;
import vn.svarcade.tcg.fabric.*;
import vn.svarcade.tcg.data.*;
import vn.svarcade.tcg.economy.*;
import vn.svarcade.tcg.performance.*;
import com.google.gson.*;
import java.nio.file.*;
import java.lang.management.*;
import java.util.*;
import java.util.concurrent.*;
/** No graphical/Minecraft runtime. Every logical tick commits an action in each populated duel.
 * Reports owner-thread CPU, actual wall time and worker latency independently. It does not infer 20 TPS.
 */
public final class PerformanceLoadHarness {
 record Planned(List<Duel.Action> actions,long latency){}
 record Run(double p50,double p95,double p99,double max,long actions,long completedDuels,long snapshotBytes,long rawSnapshotBytes,double snapshotMs,double aiP95,int maxQueue,double workerCpuMs,long allocations,double wallTimeMs,double workerCpuUtilizationPercent,double effectOperationsPerSecond,int maxDuelTaskBacklog,List<String> states){}
 static final Gson JSON=new Gson();static final ThreadMXBean THREADS=ManagementFactory.getThreadMXBean();
 static long cpu(){return THREADS.isCurrentThreadCpuTimeSupported()?THREADS.getCurrentThreadCpuTime():System.nanoTime();}
 static long allocated(){return THREADS instanceof com.sun.management.ThreadMXBean t&&t.isThreadAllocatedMemorySupported()?t.getThreadAllocatedBytes(Thread.currentThread().threadId()):0;}
 static double pct(List<Long> a,double p){return a.stream().sorted().skip(Math.max(0,(long)Math.ceil(a.size()*p)-1)).findFirst().orElse(0L)/1e6;}
 static long workerCpu(){long total=0;for(long id:THREADS.getAllThreadIds()){ThreadInfo info=THREADS.getThreadInfo(id);if(info!=null&&info.getThreadName().startsWith("cardworlds-")){long n=THREADS.getThreadCpuTime(id);if(n>0)total+=n;}}return total;}
 public static void main(String[] args)throws Exception {
  int concurrent=args.length>0?Integer.parseInt(args[0]):8,ticks=args.length>1?Integer.parseInt(args[1]):160;if(concurrent<8||concurrent>64||ticks<40||ticks>2000)throw new IllegalArgumentException("Use 8..64 populated duels and 40..2000 action rounds");
  CardWorldsPerfStats.enable(true);Catalog catalog=HeadlessCatalog.load();long species=catalog.cards().values().stream().filter(c->c.category().equals("pokemon")&&c.aspects().isEmpty()).count();if(species<1025)throw new AssertionError("Full National Dex must remain: "+species);
  Path temp=Files.createTempDirectory("cardworlds-load-");List<CardStore.UiData> data=new ArrayList<>();try(var store=new CardStore(temp.resolve("cards.db"),catalog,new Random(17));var workers=new CardWorldsExecutors(PerformanceConfig.defaults())){
   for(int i=0;i<concurrent;i++)store.createProfile("load-"+i,"crossroads");List<CompletableFuture<CardStore.UiData>> reads=new ArrayList<>();for(int i=0;i<concurrent;i++){String owner="load-"+i;reads.add(workers.submit(CardWorldsExecutors.Kind.IO,new CardWorldsExecutors.Context("load-ui",owner,store.dataRevision()),()->store.uiData(owner,0)));}for(var read:reads)data.add(read.get());
   var coldBase=LoadSnapshotFixture.full(catalog,data.getFirst(),DeterminismTest.fixture(catalog,0).view(0));var content=new SnapshotPipeline.Content(catalog.cards(),catalog.starters(),catalog.rules());long coldStarted=System.nanoTime();var cold=workers.submit(CardWorldsExecutors.Kind.SERIALIZATION,new CardWorldsExecutors.Context("initial-content","load",0),()->SnapshotPipeline.encode(new SnapshotPipeline.Wire(1,1,data.getFirst().revision()+":0:",true,false,"load",coldBase.duel().revision(),content,coldBase.withContent(null)))).get();double coldMs=(System.nanoTime()-coldStarted)/1e6;
   Run baseline=run(catalog,data,workers,concurrent,ticks,false);CardWorldsPerfStats.reset();Run async=run(catalog,data,workers,concurrent,ticks,true);if(!baseline.states().equals(async.states()))throw new AssertionError("Baseline / async final authoritative states differ");
   Map<String,Object> report=new LinkedHashMap<>();report.put("concurrentDuels",concurrent);report.put("logicalActionRounds",ticks);report.put("catalogCards",catalog.cards().size());report.put("basePokemonCards",species);report.put("effectPrimitives",Duel.effectPrimitiveCount());report.put("workload","40-card decks; populated fields, set counters, paid special-card counters, active Ember Domain, Normal/Hard AI, complete legality and sequential Chain resolution");report.put("measurement","Measured owner-thread CPU per action round; every round commits one action per duel. AI/serialization run on workers; no simulated TPS claim.");report.put("determinism","PASS: baseline and async final LP/zones/deck order/counters/statuses/history/winner identical; per-command comparisons are separately tested");report.put("baseline",withoutStates(baseline));report.put("async",withoutStates(async));report.put("initialContentBytes",cold.bytes().length);report.put("initialContentMs",coldMs);report.put("metrics",metrics());report.put("maxCpuQueue",workers.maxDepth(CardWorldsExecutors.Kind.CPU));report.put("maxIoQueue",workers.maxDepth(CardWorldsExecutors.Kind.IO));report.put("maxSerializationQueue",workers.maxDepth(CardWorldsExecutors.Kind.SERIALIZATION));report.put("maxDuelTaskBacklog",async.maxDuelTaskBacklog());report.put("perDuelDerivedTaskLimit",2);report.put("backlogMeasurement","Queue high-water marks sampled at enqueue; duel backlog sampled from pending AI/snapshot futures");report.put("workers",PerformanceConfig.defaults());report.put("gameplaySystemsDisabled",0);
   Path out=Path.of("build/performance/load-"+concurrent+".json");Files.createDirectories(out.getParent());Files.writeString(out,new GsonBuilder().setPrettyPrinting().create().toJson(report));System.out.printf(Locale.ROOT,"CARDWORLDS_LOAD_PASS duels=%d cards=%d actions=%d main_ms p50=%.3f p95=%.3f p99=%.3f max=%.3f baseline_p95=%.3f queue=%d ai_p95=%.3f snapshot_bytes=%d snapshot_ms=%.3f%n",concurrent,catalog.cards().size(),async.actions(),async.p50(),async.p95(),async.p99(),async.max(),baseline.p95(),async.maxQueue(),async.aiP95(),async.snapshotBytes(),async.snapshotMs());
  }finally{try(var files=Files.walk(temp)){for(Path f:files.sorted(Comparator.reverseOrder()).toList())Files.deleteIfExists(f);}}
 }
 static Map<String,Object> withoutStates(Run r){Map<String,Object> m=new LinkedHashMap<>();m.put("mainThreadP50Ms",r.p50());m.put("mainThreadP95Ms",r.p95());m.put("mainThreadP99Ms",r.p99());m.put("mainThreadMaxMs",r.max());m.put("committedActions",r.actions());m.put("completedDuels",r.completedDuels());m.put("meanSnapshotBytes",r.snapshotBytes());m.put("meanRawSnapshotBytes",r.rawSnapshotBytes());m.put("meanSnapshotWorkerMs",r.snapshotMs());m.put("aiQueueLatencyP95Ms",r.aiP95());m.put("maxAsyncQueue",r.maxQueue());m.put("workerCpuMs",r.workerCpuMs());m.put("ownerAllocatedBytes",r.allocations());m.put("wallTimeMs",r.wallTimeMs());m.put("workerCpuUtilizationPercent",r.workerCpuUtilizationPercent());m.put("effectOperationsPerSecond",r.effectOperationsPerSecond());m.put("maxDuelTaskBacklog",r.maxDuelTaskBacklog());return m;}
 static Map<String,Object> metrics(){Map<String,Object> out=new LinkedHashMap<>();for(var p:CardWorldsPerfStats.Path.values()){var s=CardWorldsPerfStats.sample(p);if(s.count()>0)out.put(p.name(),s);}return out;}
 static Run run(Catalog c,List<CardStore.UiData> ui,CardWorldsExecutors workers,int n,int rounds,boolean async)throws Exception {
  Duel[] live=new Duel[n];BaselineDuel[] old=new BaselineDuel[n];int[] generations=new int[n];Random[] random=new Random[n];TcgMod.Snapshot[] bases=new TcgMod.Snapshot[n];List<Map<String,Object>> legacy=new ArrayList<>();
  for(int i=0;i<n;i++){live[i]=DeterminismTest.fixture(c,i);old[i]=DeterminismTest.baseline(c,i);random[i]=new Random(i+310);bases[i]=LoadSnapshotFixture.full(c,ui.get(i),live[i].view(0));legacy.add(LoadSnapshotFixture.legacy(bases[i],old[i].view(0)));}
  List<Long> ticks=new ArrayList<>(),aiLatency=new ArrayList<>();long actions=0,completed=0,totalBytes=0,rawBytes=0,serialized=0,totalSerialization=0,max=0,allocation=0,workerStart=workerCpu();int maxQueue=0,maxDuelBacklog=0;long wallStart=System.nanoTime(),opsBefore=CardWorldsPerfStats.sample(CardWorldsPerfStats.Path.EFFECT_OPERATION).count();
  for(int round=0;round<rounds;round++){
   long work=0,allocationBefore=allocated();List<CompletableFuture<Planned>> plans=new ArrayList<>();List<DuelReadSnapshot> inputs=new ArrayList<>();List<Long> seeds=new ArrayList<>();List<CompletableFuture<long[]>> snapshots=new ArrayList<>();
   if(async){long start=cpu();for(int i=0;i<n;i++){if(live[i].winner()>=0){completed++;live[i]=DeterminismTest.fixture(c,i+(++generations[i])*1000);}Duel.View v=live[i].view(live[i].priority());var input=new DuelReadSnapshot("load-"+i,v.revision(),v,c.cards());inputs.add(input);long seed=random[i].nextLong();seeds.add(seed);String difficulty=i%2==0?"NORMAL":"HARD";long queued=System.nanoTime();plans.add(workers.submit(CardWorldsExecutors.Kind.CPU,new CardWorldsExecutors.Context("load-ai",input.duelId(),input.revision()),()->new Planned(AiPlanner.plan(input,difficulty,seed),System.nanoTime()-queued)));}work+=cpu()-start;for(var task:plans)if(!task.isDone())maxDuelBacklog=Math.max(maxDuelBacklog,1);}
   for(int i=0;i<n;i++){
    List<Duel.Action> candidates=null;Planned planned=null;if(async){planned=plans.get(i).get();candidates=planned.actions();aiLatency.add(planned.latency());}
    long start=cpu();String difficulty=i%2==0?"NORMAL":"HARD";
    if(async){Duel d=live[i];var input=inputs.get(i);if(d.revision()!=input.revision())throw new AssertionError("Unexpected stale load action");boolean applied=false;for(var action:candidates)try{d.act(d.priority(),action,input.revision());actions++;applied=true;break;}catch(IllegalArgumentException ignored){}if(!applied)throw new AssertionError("No legal AI action");var state=LoadSnapshotFixture.dynamic(bases[i],d.view(0));var wire=new SnapshotPipeline.Wire(round+2,1,ui.get(i).revision()+":0:",false,false,"load-"+i,d.revision(),null,state);snapshots.add(workers.submit(CardWorldsExecutors.Kind.SERIALIZATION,new CardWorldsExecutors.Context("load-snapshot","load-"+i,d.revision()),()->{long begun=System.nanoTime();var encoded=SnapshotPipeline.encode(wire);return new long[]{encoded.bytes().length,SnapshotCompression.decode(encoded.bytes()).getBytes(java.nio.charset.StandardCharsets.UTF_8).length,System.nanoTime()-begun};}));}
    else {BaselineDuel d=old[i];if(d.winner()>=0){completed++;d=old[i]=DeterminismTest.baseline(c,i+(++generations[i])*1000);}long seed=random[i].nextLong();long begin=System.nanoTime();var ranked=BaselineBenchPlanner.plan(new BaselineBenchPlanner.Read(d.view(d.view(0).priority()),c.cards()),difficulty,seed);aiLatency.add(System.nanoTime()-begin);boolean applied=false;for(var a:ranked)try{d.act(d.view(0).priority(),a,d.revision());actions++;applied=true;break;}catch(IllegalArgumentException ignored){}if(!applied)throw new AssertionError("Baseline AI has no legal action");legacy.get(i).put("duel",d.view(0));String json=JSON.toJson(legacy.get(i));long began=System.nanoTime();byte[] encoded=SnapshotCompression.encode(json);if(round>=20){totalBytes+=encoded.length;rawBytes+=json.getBytes(java.nio.charset.StandardCharsets.UTF_8).length;totalSerialization+=System.nanoTime()-began;serialized++;}}
    work+=cpu()-start;if(async&&!snapshots.getLast().isDone())maxDuelBacklog=Math.max(maxDuelBacklog,1);
   }
   // A completion barrier belongs only to this deterministic harness; live Minecraft never waits here.
   for(var future:snapshots){long[] result=future.get();if(round>=20){totalBytes+=result[0];rawBytes+=result[1];totalSerialization+=result[2];serialized++;}}
   if(round>=20){ticks.add(work);max=Math.max(max,work);allocation+=allocated()-allocationBefore;}maxQueue=(int)Math.max(maxQueue,Math.max(workers.pending(CardWorldsExecutors.Kind.CPU),workers.pending(CardWorldsExecutors.Kind.SERIALIZATION)));
  }
  double wallMs=(System.nanoTime()-wallStart)/1e6,workerMs=(workerCpu()-workerStart)/1e6,utilization=100*workerMs/(wallMs*(PerformanceConfig.defaults().cpuWorkers()+PerformanceConfig.defaults().ioConcurrency()+PerformanceConfig.defaults().serializationWorkers()));long operations=CardWorldsPerfStats.sample(CardWorldsPerfStats.Path.EFFECT_OPERATION).count()-opsBefore;List<String> states=new ArrayList<>();for(int i=0;i<n;i++)states.add(DeterminismTest.state(async?live[i]:old[i],new DeterminismTest.Tokens()));return new Run(pct(ticks,.50),pct(ticks,.95),pct(ticks,.99),max/1e6,actions,completed,totalBytes/serialized,rawBytes/serialized,totalSerialization/(serialized*1e6),pct(aiLatency,.95),Math.max(maxQueue,(int)Math.max(workers.maxDepth(CardWorldsExecutors.Kind.CPU),workers.maxDepth(CardWorldsExecutors.Kind.SERIALIZATION))),workerMs,allocation,wallMs,utilization,operations/(wallMs/1000),maxDuelBacklog,states);
 }
}
