package io.github.aristheg201.svhub.client.nativeui

import com.google.gson.Gson
import com.google.gson.JsonArray
import com.google.gson.JsonObject
import io.github.aristheg201.svhub.client.gui.SVHubScreen
import io.github.aristheg201.svhub.native.network.NativeIntentC2S
import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking
import net.minecraft.client.Minecraft
import net.minecraft.client.gui.GuiGraphics
import net.minecraft.client.gui.components.Button
import net.minecraft.network.chat.Component
import net.minecraft.world.item.ItemStack
import net.minecraft.world.item.Items
import kotlin.math.min

class NativePlatformScreen(val module:String,private var state:JsonObject,private var notice:String):SVHubScreen(Component.literal("SVHub Native")){
 private val gson=Gson();private var selectedCell:Int?=null;private var selectedSkin:String?=null;private var boardX=0;private var boardY=0;private var cellSize=24;private var boardW=0;private var boardH=0
 fun applyState(newState:JsonObject,message:String){state=newState;notice=message;Minecraft.getInstance().setScreen(NativePlatformScreen(module,state,notice))}
 override fun init(){when(module){"dashboard"->dashboardButtons();"gacha"->gachaButtons();"skins"->skinButtons();"arcade"->arcadeButtons();"game"->gameButtons();"companions"->companionButtons();"wallet"->navButtons()};addButton(width-82,10,70,20,"Đóng"){onClose()}}
 private fun navButtons(){addButton(12,42,92,22,"Dashboard"){open("dashboard")};addButton(108,42,72,22,"Gacha"){open("gacha")};addButton(184,42,72,22,"Skins"){open("skins")};addButton(260,42,72,22,"Arcade"){open("arcade")};addButton(336,42,92,22,"Linh Thú"){open("companions")}}
 private fun dashboardButtons(){navButtons();var x=30;listOf("gacha" to "GACHA","skins" to "SKINS","arcade" to "ARCADE","companions" to "LINH THÚ","wallet" to "WALLET").forEach{(target,label)->addButton(x,105,110,32,label){open(target)};x+=118}}
 private fun gachaButtons(){navButtons();addButton(28,90,150,28,"Hunter Roll • 1 Ticket"){intent("roll",json("banner" to "hunter"))};addButton(188,90,150,28,"Dragon Roll • 1 Ticket"){intent("roll",json("banner" to "beast"))};addButton(348,90,120,28,"Skies Wardrobe"){open("skins")}}
 private fun skinButtons(){navButtons();val source=state.str("source","all");val page=state.num("page",0);val pages=state.num("pages",1);var x=24;listOf("all" to "Tất cả","dbz" to "DBZ","naruto" to "Naruto","pokelegends" to "PokeLegends").forEach{(id,label)->addButton(x,78,88,20,label){intent("source",json("source" to id,"page" to 0))};x+=92};addButton(24,height-34,70,20,"< Trang"){intent("page",json("source" to source,"page" to (page-1).coerceAtLeast(0)))};addButton(98,height-34,70,20,"Trang >"){intent("page",json("source" to source,"page" to (page+1).coerceAtMost(pages-1)))};addButton(176,height-34,116,20,"Tủ SkiesSkins"){intent("inventory",JsonObject())};selectedSkin?.let{selected->addButton(298,height-34,90,20,"Mở shop"){intent("shop",json("skin" to selected))};for(slot in 1..6)addButton(394+(slot-1)*38,height-34,34,20,slot.toString()){intent("equip",json("skin" to selected,"slot" to slot))}};val skins=state.getAsJsonArray("skins")?:return;for(i in 0 until minOf(18,skins.size())){val e=skins[i].asJsonObject;val id=e.str("id");val name=e.str("name",id);val row=i/3;val col=i%3;addButton(24+col*200,110+row*35,190,28,(if(e.bool("owned"))"✓ " else "")+name.take(22)){selectedSkin=id;Minecraft.getInstance().setScreen(NativePlatformScreen(module,state,"Đã chọn $name • chọn party slot 1-6 phía dưới"))}}}
 private fun arcadeButtons(){navButtons();val games=state.getAsJsonArray("games")?:return;for(i in 0 until games.size()){val g=games[i].asJsonObject;val id=g.str("id");val title=g.str("title",id);val y=82+i*34;if(id=="tower_defense"){addButton(24,y,170,27,"$title • Solo"){intent("start",json("game" to id,"mode" to "solo"))};addButton(200,y,54,27,"Easy"){intent("start",json("game" to id,"mode" to "bot_easy"))};addButton(258,y,64,27,"Normal"){intent("start",json("game" to id,"mode" to "bot_normal"))};addButton(326,y,54,27,"Hard"){intent("start",json("game" to id,"mode" to "bot_hard"))}}else{addButton(24,y,170,27,"$title • Normal"){intent("start",json("game" to id,"mode" to "bot_normal"))};addButton(200,y,54,27,"Easy"){intent("start",json("game" to id,"mode" to "bot_easy"))};addButton(258,y,54,27,"Hard"){intent("start",json("game" to id,"mode" to "bot_hard"))};addButton(316,y,54,27,"PvP"){intent("start",json("game" to id,"mode" to "pvp"))}}};addButton(width-130,82,105,25,"Resume"){intent("resume",JsonObject())}}
 private fun companionButtons(){navButtons();val c=state.getAsJsonArray("companions")?:return;for(i in 0 until c.size()){val e=c[i].asJsonObject;val id=e.str("id");addButton(28+(i%4)*130,82+(i/4)*34,120,27,e.str("name",id)){intent("select",json("entity" to id))}}}
 private fun gameButtons(){addButton(12,12,82,22,"← Arcade"){intent("leave",JsonObject())};val view=state.getAsJsonObject("view")?:return;view.getAsJsonArray("actions")?.let{a->for(i in 0 until minOf(6,a.size())){val action=a[i].asJsonObject;if(action.bool("enabled",true))addButton(width-126,50+i*27,112,22,action.str("label",action.str("id"))){gameAct(action.str("id"),emptyMap())}}};view.getAsJsonArray("cards")?.let{cards->for(i in 0 until minOf(10,cards.size())){val card=cards[i].asJsonObject;addButton(18+(i%5)*112,height-64+(i/5)*26,106,22,card.str("label",card.str("id")).take(16)){when(view.str("gameId")){"uno"->gameAct("play",mapOf("index" to card.str("id"),"color" to "red"));"tft"->gameAct("buy",mapOf("index" to card.str("id").substringAfter(':')));else->gameAct("play",mapOf("index" to card.str("id")))}}}}}
 override fun render(gui:GuiGraphics,mouseX:Int,mouseY:Int,partialTick:Float){gui.fill(0,0,width,height,0xFF07101E.toInt());gui.fill(0,0,width,36,0xFF111F34.toInt());gui.drawString(font,"SV HUB • ${module.uppercase()}",14,14,0xFFEFF8FF.toInt(),false);if(notice.isNotBlank())gui.drawCenteredString(font,notice.take(90),width/2,48,0xFFFFD166.toInt());when(module){"dashboard"->renderDashboard(gui);"gacha"->renderGacha(gui);"skins"->renderSkins(gui);"arcade"->renderArcade(gui);"game"->renderGame(gui);"wallet"->renderWallet(gui);"companions"->gui.drawString(font,"Vanilla companions • server authoritative",24,72,0xFF9DCBFF.toInt(),false)};super.render(gui,mouseX,mouseY,partialTick)}
 private fun renderDashboard(gui:GuiGraphics){val wallet=state.getAsJsonObject("wallet");gui.drawCenteredString(font,"SkiesSkins: ${if(state.bool("skinBackendReady"))"ONLINE" else "OFFLINE"} • Owned ${state.num("ownedSkins")}/${state.num("skinTotal")}",width/2,75,0xFF78E6C8.toInt());gui.drawCenteredString(font,"Arcade ${wallet?.num("arcade")?:0} • Gacha Tickets ${wallet?.num("ticket")?:0}",width/2,89,0xFFEFF8FF.toInt());listOf(Items.CHEST,Items.ARMOR_STAND,Items.DIAMOND_SWORD,Items.LEAD,Items.EMERALD).forEachIndexed{i,item->gui.renderItem(ItemStack(item),77+i*118,118)}}
 private fun renderGacha(gui:GuiGraphics){val wallet=state.getAsJsonObject("wallet");gui.drawString(font,"Tickets: ${wallet?.num("ticket")?:0} • Backend: ${state.str("backend","SkiesSkins")}",28,70,0xFFEFF8FF.toInt(),false);state.getAsJsonObject("lastRoll")?.let{r->gui.drawCenteredString(font,"WIN: ${r.str("winnerName")} [${r.str("rarity")}]",width/2,132,0xFFFFD166.toInt());gui.drawCenteredString(font,"${r.str("species")} • ${r.str("aspect")}",width/2,147,0xFF9DCBFF.toInt())}}
 private fun renderSkins(gui:GuiGraphics){gui.drawString(font,"Backend: SkiesSkins • Owned ${state.num("ownedCount")} • Page ${state.num("page")+1}/${state.num("pages",1)}",24,65,0xFF9DE6D0.toInt(),false)}
 private fun renderArcade(gui:GuiGraphics){gui.drawString(font,"Native games • AI Easy/Normal/Hard off-thread • rewards enabled",24,65,0xFF9DCBFF.toInt(),false)}
 private fun renderWallet(gui:GuiGraphics){val w=state.getAsJsonObject("wallet");gui.drawCenteredString(font,"Arcade Token: ${w?.num("arcade")?:0}",width/2,110,0xFFFFD166.toInt());gui.drawCenteredString(font,"Gacha Ticket: ${w?.num("ticket")?:0}",width/2,128,0xFFEFF8FF.toInt());gui.drawCenteredString(font,"Skin economy/ownership: SkiesSkins + BECONOMY",width/2,150,0xFF78E6C8.toInt())}
 private fun renderGame(gui:GuiGraphics){val view=state.getAsJsonObject("view")?:return;gui.drawString(font,view.str("title","Game"),110,14,0xFFEFF8FF.toInt(),false);gui.drawString(font,view.str("status"),18,42,0xFFFFD166.toInt(),false);boardW=view.num("boardWidth");boardH=view.num("boardHeight");if(boardW<=0||boardH<=0)return;cellSize=min(30,((height-145)/boardH).coerceAtLeast(14));boardX=18;boardY=62;val board=view.getAsJsonArray("board")?:return;for(r in 0 until boardH)for(c in 0 until boardW){val index=r*boardW+c;val x=boardX+c*cellSize;val y=boardY+r*cellSize;gui.fill(x,y,x+cellSize-1,y+cellSize-1,if(selectedCell==index)0xFF375E87.toInt()else if((r+c)%2==0)0xFF213651.toInt()else 0xFF172A40.toInt());val text=board.elementOrNull(index)?.asString.orEmpty();if(text.isNotBlank())gui.drawCenteredString(font,text.take(4),x+cellSize/2,y+cellSize/2-4,0xFFF4F7FF.toInt())}}
 override fun mouseClicked(mouseX:Double,mouseY:Double,button:Int):Boolean{if(module=="game"&&button==0&&boardW>0&&boardH>0&&mouseX>=boardX&&mouseY>=boardY){val c=((mouseX-boardX)/cellSize).toInt();val r=((mouseY-boardY)/cellSize).toInt();if(c in 0 until boardW&&r in 0 until boardH){val index=r*boardW+c;val game=state.getAsJsonObject("view")?.str("gameId").orEmpty();if(game=="chess"||game=="xiangqi"){val first=selectedCell;if(first==null)selectedCell=index else{val from=coord(game,first);val to=coord(game,index);selectedCell=null;gameAct("move",mapOf("from" to from,"to" to to))}}else selectedCell=index;return true}};return super.mouseClicked(mouseX,mouseY,button)}
 private fun coord(game:String,index:Int):String{val w=if(game=="xiangqi")9 else 8;val r=index/w;val c=index%w;return if(game=="xiangqi")"${('a'.code+c).toChar()}$r" else "${('a'.code+c).toChar()}${8-r}"}
 private fun gameAct(action:String,args:Map<String,String>){val data=JsonObject();data.addProperty("gameAction",action);val obj=JsonObject();args.forEach{(k,v)->obj.addProperty(k,v)};data.add("args",obj);intent("act",data)}
 private fun open(target:String)=intent("open",json("module" to target),"dashboard")
 private fun intent(action:String,data:JsonObject,targetModule:String=module){ClientPlayNetworking.send(NativeIntentC2S(targetModule,action,gson.toJson(data)))}
 private fun json(vararg pairs:Pair<String,Any>)=JsonObject().apply{pairs.forEach{(k,v)->when(v){is Number->addProperty(k,v);is Boolean->addProperty(k,v);else->addProperty(k,v.toString())}}}
 private fun addButton(x:Int,y:Int,w:Int,h:Int,label:String,action:()->Unit){addRenderableWidget(Button.builder(Component.literal(label)){action()}.bounds(x,y,w,h).build())}
 private fun JsonObject.str(k:String,f:String="")=runCatching{get(k)?.asString?:f}.getOrDefault(f);private fun JsonObject.num(k:String,f:Int=0)=runCatching{get(k)?.asInt?:f}.getOrDefault(f);private fun JsonObject.bool(k:String,f:Boolean=false)=runCatching{get(k)?.asBoolean?:f}.getOrDefault(f);private fun JsonArray.elementOrNull(index:Int)=if(index in 0 until size())get(index)else null
}
