package vn.svframe.svrelationships.fabric.config;

import org.yaml.snakeyaml.LoaderOptions;
import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.constructor.SafeConstructor;
import vn.svframe.svrelationships.gameplay.DialogueDefinition;

import java.io.IOException;import java.io.InputStream;import java.nio.file.Files;import java.nio.file.Path;import java.nio.file.StandardCopyOption;import java.util.ArrayList;import java.util.LinkedHashMap;import java.util.LinkedHashSet;import java.util.List;import java.util.Map;import java.util.Objects;import java.util.Set;import java.util.concurrent.atomic.AtomicLong;import java.util.concurrent.atomic.AtomicReference;

public final class DialogueDefinitionService {
    private final Path root;private final AtomicLong generation=new AtomicLong();private final AtomicReference<Snapshot> current=new AtomicReference<>();
    public DialogueDefinitionService(Path root){this.root=Objects.requireNonNull(root,"root");}
    public void initialize(){try{Path target=root.resolve("dialogues.yml");if(!Files.exists(target)){Files.createDirectories(target.getParent());try(InputStream input=DialogueDefinitionService.class.getResourceAsStream("/defaults/dialogues.yml")){if(input==null)throw new IOException("Missing bundled resource: /defaults/dialogues.yml");Files.copy(input,target,StandardCopyOption.COPY_ATTRIBUTES);}}}catch(IOException exception){throw new IllegalStateException("Unable to install dialogue definitions",exception);}ReloadResult result=reload();if(!result.success())throw new IllegalStateException("Unable to load dialogue definitions: "+result.detail());}
    public Snapshot snapshot(){return Objects.requireNonNull(current.get(),"dialogues not initialized");}
    public ReloadResult reload(){try{Map<String,Object> rootMap;try(InputStream input=Files.newInputStream(root.resolve("dialogues.yml"))){rootMap=mapValue(new Yaml(new SafeConstructor(new LoaderOptions())).load(input),"dialogues.yml");}Map<String,DialogueDefinition> definitions=new LinkedHashMap<>();for(var entry:map(rootMap,"dialogues").entrySet()){Map<String,Object> value=mapValue(entry.getValue(),"dialogue "+entry.getKey());List<DialogueDefinition.Entry> entries=new ArrayList<>();Object raw=value.get("entries");if(raw instanceof List<?> list)for(Object item:list){Map<String,Object> e=mapValue(item,"dialogue entry");entries.add(new DialogueDefinition.Entry(string(e,"id"),integer(e,"weight"),string(e,"message_key")));}if(entries.isEmpty())throw new IllegalArgumentException("Dialogue has no entries: "+entry.getKey());definitions.put(entry.getKey(),new DialogueDefinition(entry.getKey(),optionalString(value,"required_route",""),optionalString(value,"required_state",""),set(value,"required_personality_tags"),GameplayDefinitionService.durationMillis(optionalString(value,"cooldown","0s")),entries));}current.set(new Snapshot(generation.incrementAndGet(),definitions));return new ReloadResult(true,"");}catch(Exception exception){return new ReloadResult(false,exception.getClass().getSimpleName()+": "+exception.getMessage());}}
    private static Map<String,Object> map(Map<String,Object>s,String k){return mapValue(s.get(k),k);}private static Map<String,Object> mapValue(Object v,String l){if(!(v instanceof Map<?,?> r))throw new IllegalArgumentException("Expected map at "+l);Map<String,Object> o=new LinkedHashMap<>();r.forEach((k,x)->o.put(String.valueOf(k),x));return o;}private static String string(Map<String,Object>s,String k){Object v=s.get(k);if(v==null)throw new IllegalArgumentException("Missing key: "+k);return String.valueOf(v);}private static String optionalString(Map<String,Object>s,String k,String f){Object v=s.get(k);return v==null?f:String.valueOf(v);}private static int integer(Map<String,Object>s,String k){Object v=s.get(k);return v instanceof Number n?n.intValue():Integer.parseInt(string(s,k));}private static Set<String> set(Map<String,Object>s,String k){Object v=s.get(k);if(v==null)return Set.of();if(!(v instanceof Iterable<?> iterable))throw new IllegalArgumentException("Expected list at "+k);Set<String> o=new LinkedHashSet<>();iterable.forEach(x->o.add(String.valueOf(x)));return o;}
    public record Snapshot(long generation,Map<String,DialogueDefinition> definitions){public Snapshot{definitions=Map.copyOf(definitions);}}public record ReloadResult(boolean success,String detail){}
}
