package io.github.aristheg201.svhub.native.game

import com.google.gson.JsonObject
import kotlin.random.Random

class CardDuelSession(override val seats:List<NativeSeat>,seed:Long=Random.nextLong(),override val sessionId:String=NativeIds.session("pokecards"),private val restoreState:JsonObject?=null):NativeGameSession{
 override val gameId="pokecards";private val rng=NativeStatefulRandom(seed);private val decks=seats.associate{it.id to ROSTER.shuffled(rng).toMutableList()}.toMutableMap();private val hands=seats.associate{it.id to mutableListOf<Card>()}.toMutableMap();private val selected=mutableMapOf<String,Card>();private val score=seats.associate{it.id to 0}.toMutableMap();private var round=1;private var revision=0L;private var winner:String?=null;private var result:String?=null;private val log=ArrayDeque<String>()
 init{require(seats.size==2);if(restoreState==null)seats.forEach{refill(it.id)}else restoreSnapshot(restoreState)};override val finished get()=result!=null;override val winnerSeatId get()=winner
 override fun viewFor(viewerId:String):NativeGameView{val vi=seats.indexOfFirst{it.id==viewerId};val hand=hands[viewerId].orEmpty();val opp=seats.firstOrNull{it.id!=viewerId};val locked=viewerId in selected;return NativeGameView(sessionId,gameId,"PokéDraft Cards",if(finished)"finished" else if(locked)"waiting" else "pick","Round $round",result?:if(locked)"Đã khóa bài • chờ đối thủ" else "Chọn 1 Pokémon card",cards=hand.mapIndexed{i,c->NativeCardView(i.toString(),c.species,"${c.type} • Power ${c.power}${if(c.trait.isNotBlank())" • ${c.trait}" else ""}",c.type.lowercase(),c.power,mapOf("species" to c.id,"type" to c.type))},actions=listOf(NativeActionView("resign","Nhận thua",enabled=!finished&&vi>=0)),fields=linkedMapOf("yourScore" to (score[viewerId]?:0).toString(),"opponentScore" to (opp?.id?.let(score::get)?:0).toString(),"opponent" to (opp?.name?:""),"locked" to locked.toString()),log=log.toList().takeLast(12),revision=revision,finished=finished,winner=winner?.let{id->seats.firstOrNull{it.id==id}?.name})}
 override fun act(viewerId:String,action:String,args:Map<String,String>):NativeGameResult{if(finished)return NativeGameResult(false,message="Game finished");val seat=seats.indexOfFirst{it.id==viewerId};if(seat<0)return NativeGameResult(false,message="Spectator");if(action=="resign"){finish("${seats[seat].name} nhận thua",seats[1-seat].id);return NativeGameResult(true,true,result.orEmpty())};if(action!="play")return NativeGameResult(false,message="Unknown card action");if(viewerId in selected)return NativeGameResult(false,message="Bạn đã khóa card");val i=args["index"]?.toIntOrNull()?:return NativeGameResult(false,message="Missing card index");val h=hands.getValue(viewerId);val c=h.getOrNull(i)?:return NativeGameResult(false,message="Card not found");selected[viewerId]=c;bump("${seats[seat].name} đã khóa card");runBotSelections();if(selected.size==seats.size)resolveRound();return NativeGameResult(true,true,result?:"Card locked")}
 override fun tick(nowMillis:Long):Boolean{if(finished)return false;val before=selected.size;runBotSelections();if(selected.size==seats.size)resolveRound();return before!=selected.size}
 override fun snapshotState(nowMillis:Long):JsonObject=NativeGamePersistence.toJson(Snapshot(decks.mapValues{it.value.toList()},hands.mapValues{it.value.toList()},selected.toMap(),score.toMap(),round,revision,winner,result,log.toList(),rng.state))
 private fun restoreSnapshot(state:JsonObject){val s=NativeGamePersistence.fromJson(state,Snapshot::class.java);decks.values.forEach{it.clear()};hands.values.forEach{it.clear()};seats.forEach{seat->s.decks[seat.id].orEmpty().forEach(decks.getValue(seat.id)::add);s.hands[seat.id].orEmpty().forEach(hands.getValue(seat.id)::add)};selected.clear();s.selected.filterKeys{id->seats.any{it.id==id}}.forEach{(id,value)->selected[id]=value};score.clear();seats.forEach{seat->score[seat.id]=(s.score[seat.id]?:0).coerceAtLeast(0)};round=s.round.coerceAtLeast(1);revision=s.revision.coerceAtLeast(0L);winner=s.winner?.takeIf{id->seats.any{it.id==id}};result=s.result;log.clear();s.log.takeLast(32).forEach(log::add);rng.restore(s.rngState)}
 private fun runBotSelections(){seats.filter{it.bot&&it.id !in selected}.forEach{b->val p=hands.getValue(b.id).maxByOrNull{it.power+rng.nextInt(0,8)}?:return@forEach;selected[b.id]=p;bump("${b.name} đã khóa card")}}
 private fun resolveRound(){val aS=seats[0];val bS=seats[1];val a=selected.getValue(aS.id);val b=selected.getValue(bS.id);val av=combatScore(a,b);val bv=combatScore(b,a);hands.getValue(aS.id).remove(a);hands.getValue(bS.id).remove(b);when{av>bv->{score[aS.id]=score.getValue(aS.id)+1;bump("${aS.name}: ${a.species} thắng ${b.species} ($av-$bv)")};bv>av->{score[bS.id]=score.getValue(bS.id)+1;bump("${bS.name}: ${b.species} thắng ${a.species} ($bv-$av)")};else->bump("Hòa: ${a.species} vs ${b.species} ($av-$bv)")};selected.clear();round++;seats.forEach{refill(it.id)};val win=score.entries.firstOrNull{it.value>=5};if(win!=null)finish("${seat(win.key).name} thắng PokéDraft ${win.value} điểm",win.key)else if(decks.values.all{it.isEmpty()}&&hands.values.all{it.isEmpty()}){val top=score.maxByOrNull{it.value};val ties=score.values.count{it==top?.value};finish(if(ties>1)"PokéDraft hòa" else "${seat(top!!.key).name} thắng khi hết deck",if(ties>1)null else top!!.key)}}
 private fun combatScore(c:Card,o:Card):Int{var t=c.power;t+=effectiveness(c.type,o.type);t+=when(c.trait){"glass_cannon"->6;"guardian"->if(o.power>=14)5 else 0;"swift"->rng.nextInt(0,5);"legend"->4;else->0};return t}
 private fun effectiveness(a:String,d:String):Int{if(a==d)return 0;return when(a to d){"Fire" to "Grass","Water" to "Fire","Grass" to "Water","Electric" to "Water","Ice" to "Dragon","Fighting" to "Dark","Psychic" to "Fighting","Dark" to "Psychic","Fairy" to "Dragon","Ground" to "Electric","Rock" to "Flying"->7;"Grass" to "Fire","Fire" to "Water","Water" to "Grass","Water" to "Electric","Dragon" to "Fairy","Electric" to "Ground"->-4;else->0}}
 private fun refill(id:String){val h=hands.getValue(id);val d=decks.getValue(id);while(h.size<5&&d.isNotEmpty())h+=d.removeAt(d.lastIndex)};private fun seat(id:String)=seats.first{it.id==id};private fun finish(r:String,w:String?){result=r;winner=w;bump(r)};private fun bump(m:String){revision++;log.add(m);while(log.size>32)log.removeFirst()};private data class Snapshot(val decks:Map<String,List<Card>>,val hands:Map<String,List<Card>>,val selected:Map<String,Card>,val score:Map<String,Int>,val round:Int,val revision:Long,val winner:String?,val result:String?,val log:List<String>,val rngState:Long);private data class Card(val id:String,val species:String,val type:String,val power:Int,val trait:String="")
 companion object{private val ROSTER=listOf(Card("charizard","Charizard","Fire",17,"glass_cannon"),Card("blastoise","Blastoise","Water",16,"guardian"),Card("venusaur","Venusaur","Grass",16,"guardian"),Card("pikachu","Pikachu","Electric",13,"swift"),Card("gengar","Gengar","Ghost",16,"swift"),Card("lucario","Lucario","Fighting",16),Card("gardevoir","Gardevoir","Psychic",16),Card("greninja","Greninja","Water",16,"swift"),Card("garchomp","Garchomp","Dragon",18),Card("tyranitar","Tyranitar","Rock",18,"guardian"),Card("dragonite","Dragonite","Dragon",18),Card("metagross","Metagross","Psychic",18,"guardian"),Card("sylveon","Sylveon","Fairy",15),Card("mamoswine","Mamoswine","Ice",16),Card("excadrill","Excadrill","Ground",16),Card("zoroark","Zoroark","Dark",15,"swift"),Card("arcanine","Arcanine","Fire",16),Card("milotic","Milotic","Water",16,"guardian"),Card("roserade","Roserade","Grass",14),Card("electivire","Electivire","Electric",16),Card("mewtwo","Mewtwo","Psychic",21,"legend"),Card("rayquaza","Rayquaza","Dragon",22,"legend"),Card("zacian","Zacian","Fairy",21,"legend"),Card("kyogre","Kyogre","Water",21,"legend"))}
}
