package io.github.aristheg201.svhub.native.game

import kotlin.random.Random

class LudoSession(override val seats:List<NativeSeat>,seed:Long=Random.nextLong(),override val sessionId:String=NativeIds.session("ludo")):NativeGameSession{
 override val gameId="ludo";private val rng=Random(seed);private val pieces=seats.associate{it.id to IntArray(4){HOME}}.toMutableMap();private var turn=0;private var rolled=0;private var sixChain=0;private var revision=0L;private var winner:String?=null;private var result:String?=null;private val log=ArrayDeque<String>()
 init{require(seats.size in 2..4)};override val finished get()=result!=null;override val winnerSeatId get()=winner
 override fun viewFor(viewerId:String):NativeGameView{val track=MutableList(52){""};seats.forEachIndexed{si,s->pieces.getValue(s.id).forEachIndexed{pi,p->if(p in 0..51){val sq=globalSquare(si,p);val t="${si+1}:${pi+1}";track[sq]=if(track[sq].isBlank())t else track[sq]+","+t}}};val vs=seats.indexOfFirst{it.id==viewerId};val mine=pieces[viewerId];val mov=if(vs==turn&&rolled>0&&mine!=null)movablePieces(vs,rolled)else emptyList();val actions=buildList{add(NativeActionView("roll","Tung xúc xắc",enabled=!finished&&vs==turn&&rolled==0));if(mine!=null)for(i in mov)add(NativeActionView("move","Đi quân ${i+1}","Dùng $rolled điểm",true,mapOf("piece" to i.toString())));add(NativeActionView("resign","Rời ván",enabled=!finished&&vs>=0))};return NativeGameView(sessionId,gameId,"Cờ Cá Ngựa",if(finished)"finished" else if(rolled==0)"roll" else "move",seats[turn].name,result?:if(rolled==0)"Chờ tung xúc xắc" else "Đã tung: $rolled",13,4,track,actions=actions,fields=linkedMapOf("rolled" to rolled.toString(),"positions" to seats.mapIndexed{i,s->"${i+1}:${s.name}=[${pieces.getValue(s.id).joinToString(","){p->when(p){HOME->"H";FINISHED->"F";else->p.toString()}}}]"}.joinToString(" • "),"you" to vs.toString(),"safeSquares" to SAFE.joinToString(",")),log=log.toList().takeLast(12),revision=revision,finished=finished,winner=winner?.let{w->seats.firstOrNull{it.id==w}?.name})}
 override fun act(viewerId:String,action:String,args:Map<String,String>):NativeGameResult{if(finished)return NativeGameResult(false,message="Game finished");val seat=seats.indexOfFirst{it.id==viewerId};if(seat<0)return NativeGameResult(false,message="Spectator");if(action=="resign"){val rem=seats.indices.filter{it!=seat};if(rem.size==1)finish("${seats[seat].name} rời ván",seats[rem[0]].id)else{bump("${seats[seat].name} bỏ lượt");nextTurn(true)};return NativeGameResult(true,true,"Đã rời/bỏ lượt")};if(seat!=turn)return NativeGameResult(false,message="Chưa tới lượt");return when(action){"roll"->{if(rolled!=0)return NativeGameResult(false,message="Đã tung xúc xắc");doRoll();runBots();NativeGameResult(true,true,"Đã tung $rolled")};"move"->{if(rolled==0)return NativeGameResult(false,message="Hãy tung xúc xắc trước");val piece=args["piece"]?.toIntOrNull()?:return NativeGameResult(false,message="Thiếu quân");if(piece !in movablePieces(seat,rolled))return NativeGameResult(false,message="Quân không đi được");movePiece(seat,piece);runBots();NativeGameResult(true,true,result?:"Đã đi")};else->NativeGameResult(false,message="Unknown Ludo action")}}
 override fun tick(nowMillis:Long):Boolean{if(!finished&&seats[turn].bot){runBots();return true};return false}
 private fun doRoll(){rolled=rng.nextInt(1,7);if(rolled==6)sixChain++ else sixChain=0;bump("${seats[turn].name} tung $rolled");if(sixChain>=3){bump("Ba lần 6 liên tiếp: mất lượt");rolled=0;sixChain=0;nextTurn(true);return};if(movablePieces(turn,rolled).isEmpty()){val extra=rolled==6;rolled=0;if(!extra)nextTurn(true)else bump("Không có quân hợp lệ; được tung lại vì ra 6")}}
 private fun movePiece(si:Int,pi:Int){val arr=pieces.getValue(seats[si].id);val before=arr[pi];val dice=rolled;val target=if(before==HOME)0 else before+dice;arr[pi]=target;if(target==FINISH_PROGRESS)arr[pi]=FINISHED;val landed=arr[pi];if(landed in 0..51)captureAt(si,globalSquare(si,landed));bump("${seats[si].name} đi quân ${pi+1}: ${display(before)} → ${display(arr[pi])}");if(arr.all{it==FINISHED}){finish("${seats[si].name} về chuồng đủ 4 quân",seats[si].id);return};val extra=dice==6;rolled=0;if(!extra){sixChain=0;nextTurn(true)}else bump("Ra 6: được thêm lượt")}
 private fun captureAt(mover:Int,square:Int){if(square in SAFE)return;seats.forEachIndexed{si,s->if(si!=mover){val arr=pieces.getValue(s.id);arr.indices.forEach{i->val p=arr[i];if(p in 0..51&&globalSquare(si,p)==square){arr[i]=HOME;bump("${seats[mover].name} đá quân ${i+1} của ${s.name} về chuồng")}}}}}
 private fun movablePieces(si:Int,dice:Int):List<Int>{val a=pieces.getValue(seats[si].id);return a.indices.filter{i->val p=a[i];when{p==FINISHED->false;p==HOME->dice==6;else->p+dice<=FINISH_PROGRESS}}}
 private fun runBots(){var g=0;while(!finished&&seats[turn].bot&&g++<24){if(rolled==0)doRoll();if(finished||!seats[turn].bot||rolled==0)continue;val m=movablePieces(turn,rolled);if(m.isEmpty()){rolled=0;nextTurn(true);continue};movePiece(turn,m.maxBy{moveScore(turn,it,rolled)})}}
 private fun moveScore(si:Int,pi:Int,d:Int):Int{val p=pieces.getValue(seats[si].id)[pi];if(p==HOME)return 25;val t=p+d;if(t==FINISH_PROGRESS)return 100;if(t in 0..51){val sq=globalSquare(si,t);var cap=0;if(sq !in SAFE)seats.forEachIndexed{o,s->if(o!=si)cap+=pieces.getValue(s.id).count{it in 0..51&&globalSquare(o,it)==sq}};return t+cap*50};return t}
 private fun nextTurn(force:Boolean){if(!force||finished)return;turn=(turn+1)%seats.size;rolled=0};private fun finish(r:String,w:String?){result=r;winner=w;bump(r)};private fun bump(m:String){revision++;log.add(m);while(log.size>32)log.removeFirst()};private fun globalSquare(si:Int,p:Int)=(STARTS[si]+p)%52;private fun display(p:Int)=when(p){HOME->"chuồng";FINISHED->"đích";else->p.toString()}
 companion object{private const val HOME=-1;private const val FINISHED=58;private const val FINISH_PROGRESS=57;private val STARTS=intArrayOf(0,13,26,39);private val SAFE=setOf(0,8,13,21,26,34,39,47)}
}
