package io.github.aristheg201.svhub.native.game

import com.google.gson.JsonObject
import kotlin.math.abs
import kotlin.random.Random

class TowerDefenseSession(override val seats:List<NativeSeat>,seed:Long=Random.nextLong(),override val sessionId:String=NativeIds.session("td"),private val restoreState:JsonObject?=null):NativeGameSession{
 override val gameId="tower_defense";private val rng=Random(seed);private val towers=linkedMapOf<Int,Tower>();private val enemies=mutableListOf<Enemy>();private var gold=120;private var lives=20;private var wave=0;private var running=false;private var spawnRemaining=0;private var spawnCooldown=0;private var revision=0L;private var result:String?=null;private var winner:String?=null;private var lastStepAt=System.currentTimeMillis();private var nextEnemyId=1;private val log=ArrayDeque<String>()
 init{require(seats.isNotEmpty());restoreState?.let(::restoreSnapshot)};override val finished get()=result!=null;override val winnerSeatId get()=winner
 override fun viewFor(viewerId:String):NativeGameView{val board=MutableList(96){""};PATH.forEachIndexed{i,p->board[p]=if(i==0)"path:start" else if(i==PATH.lastIndex)"path:goal" else "path"};towers.forEach{(s,t)->board[s]="tower:${t.type}:${t.level}"};enemies.sortedBy{it.progress}.forEach{e->val s=PATH[e.progress.toInt().coerceIn(0,PATH.lastIndex)];val tag="enemy:${e.id}:${e.kind}:${e.hp.coerceAtLeast(0)}:${e.maxHp}:${e.progress}";board[s]=if(board[s].startsWith("path"))tag else board[s]+",$tag"};return NativeGameView(sessionId,gameId,"Pokémon Tower Defense",if(finished)"finished" else if(running)"wave" else "prepare","Wave $wave",result?:if(running)"${enemies.size+spawnRemaining} enemies remaining" else "Prepare your defense",12,8,board,TOWER_DEFS.values.map{d->NativeCardView(d.id,d.name,"${d.cost}g • DMG ${d.damage} • Range ${d.range}",d.element.lowercase(),d.cost,mapOf("species" to d.species))},listOf(NativeActionView("start_wave","Bắt đầu wave ${wave+1}",enabled=!finished&&!running),NativeActionView("resign","Kết thúc",enabled=!finished)),linkedMapOf("gold" to gold.toString(),"lives" to lives.toString(),"wave" to wave.toString(),"running" to running.toString(),"towerCount" to towers.size.toString(),"enemyEncoding" to "v2","path" to PATH.joinToString(",")),log.toList().takeLast(14),revision,finished,winner?.let{w->seats.firstOrNull{it.id==w}?.name})}
 override fun act(viewerId:String,action:String,args:Map<String,String>):NativeGameResult{if(viewerId !in seats.map{it.id})return NativeGameResult(false,message="Spectator");if(finished)return NativeGameResult(false,message="Game finished");return when(action){"start_wave"->startWave();"deploy"->deploy(args["type"],args["slot"]?.toIntOrNull());"upgrade"->upgrade(args["slot"]?.toIntOrNull());"sell"->sell(args["slot"]?.toIntOrNull());"resign"->{finish("Defense ended",null);NativeGameResult(true,true,"Ended")};else->NativeGameResult(false,message="Unknown TD action")}}
 override fun tick(nowMillis:Long):Boolean{if(!running||finished){lastStepAt=nowMillis;return false};val elapsed=(nowMillis-lastStepAt).coerceIn(0,1000);if(elapsed<STEP_MS)return false;repeat((elapsed/STEP_MS).toInt().coerceIn(1,4)){step()};lastStepAt=nowMillis;return true}
 override fun snapshotState(nowMillis:Long):JsonObject=NativeGamePersistence.toJson(Snapshot(towers.toMap(),enemies.toList(),gold,lives,wave,running,spawnRemaining,spawnCooldown,revision,result,winner,nextEnemyId,log.toList()))
 private fun restoreSnapshot(state:JsonObject){val s=NativeGamePersistence.fromJson(state,Snapshot::class.java);towers.clear();s.towers.filterKeys{it in 0 until 96&&it !in PATH}.forEach{(slot,tower)->if(tower.type in TOWER_DEFS)towers[slot]=tower.copy(level=tower.level.coerceIn(1,5),cooldown=tower.cooldown.coerceAtLeast(0))};enemies.clear();s.enemies.filter{it.maxHp>0&&it.progress>=0.0}.forEach{enemy->enemies+=enemy.copy(hp=enemy.hp.coerceIn(0,enemy.maxHp),progress=enemy.progress.coerceAtMost(PATH.lastIndex+1.0))};gold=s.gold.coerceIn(0,1_000_000);lives=s.lives.coerceIn(0,1000);wave=s.wave.coerceAtLeast(0);running=s.running&&s.result==null;spawnRemaining=s.spawnRemaining.coerceAtLeast(0);spawnCooldown=s.spawnCooldown.coerceAtLeast(0);revision=s.revision.coerceAtLeast(0L);result=s.result;winner=s.winner?.takeIf{id->seats.any{it.id==id}};nextEnemyId=maxOf(s.nextEnemyId,(enemies.maxOfOrNull{it.id}?:0)+1);log.clear();s.log.takeLast(40).forEach(log::add);lastStepAt=System.currentTimeMillis()}
 private fun startWave():NativeGameResult{if(running)return NativeGameResult(false,message="Wave already running");wave++;running=true;spawnRemaining=5+wave*2+if(wave%5==0)1 else 0;spawnCooldown=0;bump("Wave $wave bắt đầu${if(wave%5==0)" • BOSS" else ""}");return NativeGameResult(true,true,"Wave started")}
 private fun deploy(type:String?,slot:Int?):NativeGameResult{val d=type?.let(TOWER_DEFS::get)?:return NativeGameResult(false,message="Unknown tower");val s=slot?:return NativeGameResult(false,message="Missing slot");if(s !in 0 until 96||s in PATH||s in towers)return NativeGameResult(false,message="Cannot deploy there");if(gold<d.cost)return NativeGameResult(false,message="Not enough gold");gold-=d.cost;towers[s]=Tower(d.id,1,0);bump("Deploy ${d.name} @ $s");return NativeGameResult(true,true,"Deployed")}
 private fun upgrade(slot:Int?):NativeGameResult{val s=slot?:return NativeGameResult(false,message="Missing slot");val t=towers[s]?:return NativeGameResult(false,message="Tower not found");if(t.level>=5)return NativeGameResult(false,message="Max level");val cost=TOWER_DEFS.getValue(t.type).cost*t.level;if(gold<cost)return NativeGameResult(false,message="Not enough gold");gold-=cost;t.level++;bump("Upgrade ${TOWER_DEFS.getValue(t.type).name} → Lv.${t.level}");return NativeGameResult(true,true,"Upgraded")}
 private fun sell(slot:Int?):NativeGameResult{val s=slot?:return NativeGameResult(false,message="Missing slot");val t=towers.remove(s)?:return NativeGameResult(false,message="Tower not found");val base=TOWER_DEFS.getValue(t.type).cost;val invested=base+(1 until t.level).sumOf{base*it};val refund=(invested*.7).toInt();gold+=refund;bump("Sell ${TOWER_DEFS.getValue(t.type).name} +${refund}g");return NativeGameResult(true,true,"Sold")}
 private fun step(){if(!running||finished)return;if(spawnRemaining>0){if(spawnCooldown<=0){val boss=wave%5==0&&spawnRemaining==1;spawnEnemy(boss);spawnRemaining--;spawnCooldown=if(boss)7 else 3}else spawnCooldown--};towers.forEach{(slot,t)->if(t.cooldown>0){t.cooldown--;return@forEach};val d=TOWER_DEFS.getValue(t.type);val range=d.range+(t.level-1)*.35;val target=enemies.filter{it.hp>0&&distanceToPath(slot,it.progress)<=range}.maxByOrNull{it.progress};if(target!=null){var damage=(d.damage*(1.0+(t.level-1)*.55)).toInt();if(d.element==target.weakness)damage=(damage*1.5).toInt();target.hp-=damage;t.cooldown=(d.cooldown-t.level/2).coerceAtLeast(1)}};val dead=enemies.filter{it.hp<=0};dead.forEach{gold+=it.reward};enemies.removeAll(dead.toSet());val it=enemies.iterator();while(it.hasNext()){val e=it.next();e.progress+=e.speed;if(e.progress>=PATH.lastIndex+.95){lives-=if(e.kind=="boss")5 else 1;it.remove();bump("${e.kind} lọt qua • lives=$lives");if(lives<=0){finish("Thất thủ ở wave $wave",null);return}}};if(spawnRemaining==0&&enemies.isEmpty()){running=false;val bonus=15+wave*2;gold+=bonus;bump("Clear wave $wave • +${bonus}g");if(wave>=20)finish("Victory • clear 20 waves",seats.first().id)};revision++}
 private fun spawnEnemy(boss:Boolean){val scale=1.0+wave*.16;val kind:String;val hp:Int;val speed:Double;val reward:Int;val weakness:String;if(boss){kind=BOSS_NAMES[(wave/5-1).coerceIn(0,BOSS_NAMES.lastIndex)];hp=(1600*scale).toInt();speed=.16;reward=55+wave*2;weakness=listOf("Electric","Water","Fire","Grass").random(rng)}else{val a=rng.nextInt(4);kind=when(a){0->"rattata";1->"zubat";2->"geodude";else->"gastly"};hp=((90+a*25)*scale).toInt();speed=.28+a*.02+wave.coerceAtMost(15)*.006;reward=4+wave/3;weakness=when(a){0->"Fighting";1->"Electric";2->"Water";else->"Psychic"}};enemies+=Enemy(nextEnemyId++,kind,hp,hp,speed,reward,weakness,0.0)}
 private fun distanceToPath(slot:Int,progress:Double):Double{val p=PATH[progress.toInt().coerceIn(0,PATH.lastIndex)];return abs(slot%12-p%12).toDouble()+abs(slot/12-p/12).toDouble()};private fun finish(r:String,w:String?){result=r;winner=w;running=false;bump(r)};private fun bump(m:String){revision++;log.add(m);while(log.size>40)log.removeFirst()}
 private data class Snapshot(val towers:Map<Int,Tower>,val enemies:List<Enemy>,val gold:Int,val lives:Int,val wave:Int,val running:Boolean,val spawnRemaining:Int,val spawnCooldown:Int,val revision:Long,val result:String?,val winner:String?,val nextEnemyId:Int,val log:List<String>)
 private data class Tower(var type:String,var level:Int,var cooldown:Int);private data class Enemy(val id:Int,val kind:String,var hp:Int,val maxHp:Int,val speed:Double,val reward:Int,val weakness:String,var progress:Double);private data class TowerDef(val id:String,val name:String,val species:String,val element:String,val cost:Int,val damage:Int,val range:Double,val cooldown:Int)
 companion object{private const val STEP_MS=200L;private val PATH=intArrayOf(12,13,14,15,16,17,18,19,20,21,22,23,35,47,59,71,83,82,81,80,79,78,77,76,64,52,40,41,42,43,44,45,46);private val TOWER_DEFS=listOf(TowerDef("pikachu","Pikachu","cobblemon:pikachu","Electric",35,28,3.2,4),TowerDef("charmander","Charmander","cobblemon:charmander","Fire",30,34,2.5,5),TowerDef("squirtle","Squirtle","cobblemon:squirtle","Water",32,22,3.0,3),TowerDef("bulbasaur","Bulbasaur","cobblemon:bulbasaur","Grass",34,20,3.6,4),TowerDef("lucario","Lucario","cobblemon:lucario","Fighting",65,58,2.2,3),TowerDef("gardevoir","Gardevoir","cobblemon:gardevoir","Psychic",72,64,4.0,5)).associateBy{it.id};private val BOSS_NAMES=listOf("snorlax_boss","tyranitar_boss","metagross_boss","rayquaza_boss")}
}
