package io.github.aristheg201.svhub.native.game

import com.google.gson.JsonObject
import io.github.aristheg201.svhub.engine.BattleEvent
import kotlin.math.abs
import kotlin.random.Random

/** Deterministic TD simulation over a virtual route; all content and cadence comes from the pinned definition. */
class TowerDefenseSession(
    override val seats:List<NativeSeat>, seed:Long=Random.nextLong(), override val sessionId:String=NativeIds.session("td"),
    private val restoreState:JsonObject?=null, private val definition:TowerDefenseDefinition=TowerDefenseDefinitions.active()
):NativeGameSession {
    override val gameId="tower_defense"
    private val towersById=definition.towers.associateBy{it.id};private val enemiesById=(definition.enemies+definition.bosses.map{TdEnemyDefinition(it.id,it.hp,it.speed,it.reward,it.leakDamage,it.tags,it.resistances)}).associateBy{it.id}
    private val rng=NativeStatefulRandom(seed);private val towers=linkedMapOf<Int,Tower>();private val enemies=mutableListOf<Enemy>();private val spawnQueue=ArrayDeque<PendingSpawn>();private val triggerRuntime=RouteTriggerRuntime()
    private var gold=definition.startingGold;private var lives=definition.startingLives;private var wave=0;private var running=false;private var spawnCooldown=0;private var revision=0L;private var result:String?=null;private var winner:String?=null;private var lastStepAt=System.currentTimeMillis();private var logicalTick=0L;private var nextEnemyId=1;private val log=ArrayDeque<String>()
    init{require(seats.isNotEmpty());TowerDefenseDefinitions.validate(definition);restoreState?.let(::restoreSnapshot)}
    override val finished get()=result!=null;override val winnerSeatId get()=winner
    override fun viewFor(viewerId:String):NativeGameView{val board=MutableList(definition.width*definition.height){""};definition.path.forEachIndexed{i,p->board[p]=when(i){0->"path:start";definition.path.lastIndex->"path:goal";else->"path"}};towers.forEach{(s,t)->val d=towersById[t.type];board[s]="tower:${t.type}:${t.level}:${t.fireSerial}:${t.targetEnemyId?:-1}:${d?.moveId.orEmpty()}:${d?.animationSemantic.orEmpty()}"};enemies.sortedBy{it.progress}.forEach{e->val s=definition.path[e.progress.toInt().coerceIn(0,definition.path.lastIndex)];board[s]="enemy:${e.id}:${e.kind}:${e.hp.coerceAtLeast(0)}:${e.maxHp}:${e.progress}"};return NativeGameView(sessionId,gameId,"Pokémon Tower Defense",if(finished)"finished" else if(running)"wave" else "prepare","Wave $wave",result?:if(running)"${enemies.size+spawnQueue.size} enemies remaining" else "Prepare your defense",definition.width,definition.height,board,towersById.values.map{d->NativeCardView(d.id,d.name,"${d.cost}g • DMG ${d.damage} • Range ${d.range}",d.element.lowercase(),d.cost,mapOf("species" to d.species,"targetMode" to d.targetMode))},listOf(NativeActionView("start_wave","Bắt đầu wave ${wave+1}",enabled=!finished&&!running),NativeActionView("resign","Kết thúc",enabled=!finished)),linkedMapOf("gold" to "$gold","lives" to "$lives","wave" to "$wave","running" to "$running","path" to definition.path.joinToString(","),"definition" to definition.id,"enemyEncoding" to "v2","towerEncoding" to "v2"),log.toList().takeLast(14),revision,finished,winner?.let{w->seats.firstOrNull{it.id==w}?.name})}
    override fun act(viewerId:String,action:String,args:Map<String,String>):NativeGameResult{if(viewerId !in seats.map{it.id})return NativeGameResult(false,message="Spectator");if(finished)return NativeGameResult(false,message="Game finished");return when(action){"start_wave"->startWave();"deploy"->deploy(args["type"],args["slot"]?.toIntOrNull());"upgrade"->upgrade(args["slot"]?.toIntOrNull());"sell"->sell(args["slot"]?.toIntOrNull());"resign"->{finish("Defense ended",null);NativeGameResult(true,true,"Ended")};else->NativeGameResult(false,message="Unknown TD action")}}
    override fun tick(nowMillis:Long):Boolean{if(!running||finished){lastStepAt=nowMillis;return false};val elapsed=(nowMillis-lastStepAt).coerceIn(0,1000);if(elapsed<definition.simulationStepMs)return false;repeat((elapsed/definition.simulationStepMs).toInt().coerceIn(1,4)){step()};lastStepAt=nowMillis;return true}
    override fun snapshotState(nowMillis:Long)=NativeGamePersistence.toJson(Snapshot(towers.toMap(),enemies.toList(),spawnQueue.toList(),gold,lives,wave,running,spawnCooldown,revision,result,winner,nextEnemyId,log.toList(),rng.state,logicalTick,triggerRuntime.snapshot()))
    private fun restoreSnapshot(state:JsonObject){val s=NativeGamePersistence.fromJson(state,Snapshot::class.java);towers.clear();s.towers.filterKeys{it in definition.buildZones}.forEach{(slot,t)->if(t.type in towersById)towers[slot]=t};enemies.clear();enemies+=s.enemies.filter{it.kind in enemiesById&&it.hp>0};spawnQueue.clear();spawnQueue+=s.spawnQueue.orEmpty().filter{it.enemy in enemiesById};gold=s.gold.coerceAtLeast(0);lives=s.lives.coerceAtLeast(0);wave=s.wave.coerceIn(0,definition.waves.size);running=s.running&&s.result==null;spawnCooldown=s.spawnCooldown.coerceAtLeast(0);revision=s.revision.coerceAtLeast(0);result=s.result;winner=s.winner;nextEnemyId=maxOf(s.nextEnemyId,(enemies.maxOfOrNull{it.id}?:0)+1);log+=s.log.takeLast(40);rng.restore(s.rngState);logicalTick=s.logicalTick;triggerRuntime.restore(s.triggerState?:RouteTriggerRuntime.State());lastStepAt=System.currentTimeMillis()}
    private fun startWave():NativeGameResult{if(running)return NativeGameResult(false,message="Wave already running");val w=definition.waves.getOrNull(wave)?:return NativeGameResult(false,message="No configured wave");wave=w.number;spawnQueue.clear();w.groups.forEach{g->repeat(g.count){i->spawnQueue+=PendingSpawn(g.enemy,if(i==0)g.initialDelayTicks else g.intervalTicks)}};spawnCooldown=spawnQueue.firstOrNull()?.delay?:0;running=true;bump("Wave $wave bắt đầu");return NativeGameResult(true,true,"Wave started")}
    private fun deploy(type:String?,slot:Int?):NativeGameResult{val d=type?.let(towersById::get)?:return NativeGameResult(false,message="Unknown tower");val s=slot?:return NativeGameResult(false,message="Missing slot");if(s !in definition.buildZones||s in towers)return NativeGameResult(false,message="Cannot deploy there");if(gold<d.cost)return NativeGameResult(false,message="Not enough gold");gold-=d.cost;towers[s]=Tower(d.id,1,0);bump("Deploy ${d.name}");return NativeGameResult(true,true,"Deployed")}
    private fun upgrade(slot:Int?):NativeGameResult{val t=towers[slot?:-1]?:return NativeGameResult(false,message="Tower not found");val d=towersById.getValue(t.type);val next=d.upgrades.firstOrNull{it.level==t.level+1}?:return NativeGameResult(false,message="Max level");if(gold<next.cost)return NativeGameResult(false,message="Not enough gold");gold-=next.cost;t.level=next.level;bump("Upgrade ${d.name}");return NativeGameResult(true,true,"Upgraded")}
    private fun sell(slot:Int?):NativeGameResult{val t=towers.remove(slot?:-1)?:return NativeGameResult(false,message="Tower not found");val d=towersById.getValue(t.type);val invested=d.cost+d.upgrades.filter{it.level in 2..t.level}.sumOf{it.cost};val refund=(invested*definition.sellRatio).toInt();gold+=refund;bump("Sell ${d.name} +${refund}g");return NativeGameResult(true,true,"Sold")}
    private fun step(){
        logicalTick++
        if(spawnQueue.isNotEmpty()){if(spawnCooldown<=0){val pending=spawnQueue.removeFirst();spawn(pending.enemy);spawnCooldown=spawnQueue.firstOrNull()?.delay?:0}else spawnCooldown--}
        val progressIndex=enemies.filter{it.hp>0}.groupBy{it.progress.toInt()}
        towers.forEach{(slot,tower)->
            if(tower.cooldown>0){tower.cooldown--;return@forEach}
            val definition=towersById.getValue(tower.type);val upgrade=definition.upgrades.firstOrNull{it.level==tower.level}?:TdUpgradeLevel()
            val radius=definition.range+upgrade.rangeBonus;val candidates=progressIndex.values.flatten().map{enemy->RouteTargetSelectors.Candidate(enemy,enemy.progress,enemy.hp.toDouble(),enemy.maxHp.toDouble(),distance(slot,enemy.progress),enemy.tags,enemy.id.toString())}.filter{it.distance<=radius}
            val target=RouteTargetSelectors.select(definition.targetMode,candidates,definition.targetFilters)
            if(target!=null){RouteEffectRuntime.apply(definition.effects+upgrade.effects,target,definition.element,definition.damage*upgrade.damageMultiplier);triggerRuntime.fire(definition.triggers,BattleEvent.ON_ATTACK,target,definition.element,definition.damage*upgrade.damageMultiplier,logicalTick){rng.nextDouble()};tower.fireSerial++;tower.targetEnemyId=target.id;tower.cooldown=upgrade.cooldown?:definition.cooldown}
        }
        enemies.forEach{enemy->enemy.statuses.replaceAll{_,status->status.copy(remainingTicks=status.remainingTicks-1)};enemy.statuses.entries.removeIf{it.value.remainingTicks<=0};applyBossPhases(enemy)}
        enemies.filter{it.hp<=0}.toList().forEach{gold+=it.reward;enemies.remove(it)}
        enemies.toList().forEach{enemy->val stunned="stun" in enemy.statuses;val slow=enemy.statuses["slow"]?.intensity?.coerceIn(0.0,1.0)?:0.0;if(!stunned)enemy.progress+=enemy.speed*(1.0-slow);if(enemy.progress>=definition.path.lastIndex+.95){lives-=enemy.leakDamage;enemies.remove(enemy);if(lives<=0){finish("Defeat",null);return}}}
        if(spawnQueue.isEmpty()&&enemies.isEmpty()){running=false;val configured=definition.waves.first{it.number==wave};gold+=configured.clearGold;bump("Clear wave $wave");if(wave>=definition.victoryWave)finish("Victory",seats.first().id)};revision++
    }
    private fun applyBossPhases(enemy:Enemy){val boss=definition.bosses.firstOrNull{it.id==enemy.kind}?:return;boss.phases.sortedByDescending{it.hpRatio}.forEachIndexed{index,phase->if(enemy.hp.toDouble()/enemy.maxHp<=phase.hpRatio&&enemy.phases.add(index)){RouteEffectRuntime.apply(phase.effects,enemy,"",0.0);phase.adds.forEach(::spawn);enemy.speed*=phase.enrageMultiplier}}}

    private fun spawn(kind:String){val d=enemiesById.getValue(kind);enemies+=Enemy(nextEnemyId++,d.id,d.hp,d.hp,d.speed,d.reward,d.leakDamage,d.tags,d.resistances,0.0)}
    private fun distance(slot:Int,progress:Double):Double{val p=definition.path[progress.toInt().coerceIn(0,definition.path.lastIndex)];return abs(slot%definition.width-p%definition.width)+abs(slot/definition.width-p/definition.width).toDouble()}
    private fun finish(r:String,w:String?){result=r;winner=w;running=false;bump(r)};private fun bump(m:String){revision++;log+=m;while(log.size>40)log.removeFirst()}
    private data class PendingSpawn(val enemy:String,val delay:Int)
    private data class Tower(var type:String,var level:Int,var cooldown:Int,var fireSerial:Long=0,var targetEnemyId:Int?=null)
    private data class Enemy(val id:Int,val kind:String,override var hp:Int,val maxHp:Int,var speed:Double,val reward:Int,val leakDamage:Int,val tags:Set<String>,override val resistances:List<TdResistance>,var progress:Double,override var shield:Int=0,override val statuses:MutableMap<String,RouteEffectRuntime.Status> = linkedMapOf(),val phases:MutableSet<Int> = linkedSetOf()):RouteEffectRuntime.Target
    private data class Snapshot(val towers:Map<Int,Tower>,val enemies:List<Enemy>,val spawnQueue:List<PendingSpawn>?,val gold:Int,val lives:Int,val wave:Int,val running:Boolean,val spawnCooldown:Int,val revision:Long,val result:String?,val winner:String?,val nextEnemyId:Int,val log:List<String>,val rngState:Long,val logicalTick:Long=0,val triggerState:RouteTriggerRuntime.State?=RouteTriggerRuntime.State())
}
