package io.github.aristheg201.svhub.native.game

import com.google.gson.JsonObject
import kotlin.math.abs
import kotlin.random.Random

class TowerDefenseSession(override val seats:List<NativeSeat>,seed:Long=Random.nextLong(),override val sessionId:String=NativeIds.session("td"),private val restoreState:JsonObject?=null):NativeGameSession{
 override val gameId="tower_defense";private val definition=TowerDefenseDefinitions.bundled;private val PATH get()=definition.path;private val TOWER_DEFS get()=definition.towers.associateBy{it.id};private val rng=NativeStatefulRandom(seed);private val towers=linkedMapOf<Int,Tower>();private val enemies=mutableListOf<Enemy>();private var gold=definition.startingGold;private var lives=definition.startingLives;private var wave=0;private var running=false;private var spawnRemaining=0;private var spawnCooldown=0;private var revision=0L;private var result:String?=null;private var winner:String?=null;private var lastStepAt=System.currentTimeMillis();private var nextEnemyId=1;private val log=ArrayDeque<String>()
 init{require(seats.isNotEmpty());restoreState?.let(::restoreSnapshot)};override val finished get()=result!=null;override val winnerSeatId get()=winner
 override fun viewFor(viewerId:String):NativeGameView{val board=MutableList(definition.width*definition.height){""};PATH.forEachIndexed{i,p->board[p]=if(i==0)"path:start" else if(i==PATH.lastIndex)"path:goal" else "path"};towers.forEach{(s,t)->val d=TOWER_DEFS[t.type];board[s]="tower:${t.type}:${t.level}:${t.fireSerial}:${t.targetEnemyId ?: -1}:${d?.moveId.orEmpty()}"};enemies.sortedBy{it.progress}.forEach{e->val s=PATH[e.progress.toInt().coerceIn(0,PATH.lastIndex)];val tag="enemy:${e.id}:${e.kind}:${e.hp.coerceAtLeast(0)}:${e.maxHp}:${e.progress}";board[s]=if(board[s].startsWith("path"))tag else board[s]+",$tag"};return NativeGameView(sessionId,gameId,"Pokémon Tower Defense",if(finished)"finished" else if(running)"wave" else "prepare","Wave $wave",result?:if(running)"${enemies.size+spawnRemaining} enemies remaining" else "Prepare your defense",definition.width,definition.height,board,TOWER_DEFS.values.map{d->NativeCardView(d.id,d.name,"${d.cost}g • DMG ${d.damage} • Range ${d.range}",d.element.lowercase(),d.cost,mapOf("species" to d.species,"damage" to d.damage.toString(),"range" to d.range.toString()))},listOf(NativeActionView("start_wave","Bắt đầu wave ${wave+1}",enabled=!finished&&!running),NativeActionView("resign","Kết thúc",enabled=!finished)),linkedMapOf("gold" to gold.toString(),"lives" to lives.toString(),"wave" to wave.toString(),"running" to running.toString(),"towerCount" to towers.size.toString(),"enemyEncoding" to "v2","towerEncoding" to "v2","path" to PATH.joinToString(",")),log.toList().takeLast(14),revision,finished,winner?.let{w->seats.firstOrNull{it.id==w}?.name})}
 override fun act(viewerId:String,action:String,args:Map<String,String>):NativeGameResult{if(viewerId !in seats.map{it.id})return NativeGameResult(false,message="Spectator");if(finished)return NativeGameResult(false,message="Game finished");return when(action){"start_wave"->startWave();"deploy"->deploy(args["type"],args["slot"]?.toIntOrNull());"upgrade"->upgrade(args["slot"]?.toIntOrNull());"sell"->sell(args["slot"]?.toIntOrNull());"resign"->{finish("Defense ended",null);NativeGameResult(true,true,"Ended")};else->NativeGameResult(false,message="Unknown TD action")}}
 override fun tick(nowMillis:Long):Boolean{if(!running||finished){lastStepAt=nowMillis;return false};val elapsed=(nowMillis-lastStepAt).coerceIn(0,1000);if(elapsed<definition.simulationStepMs)return false;repeat((elapsed/definition.simulationStepMs).toInt().coerceIn(1,4)){step()};lastStepAt=nowMillis;return true}
 override fun snapshotState(nowMillis:Long):JsonObject=NativeGamePersistence.toJson(Snapshot(towers.toMap(),enemies.toList(),gold,lives,wave,running,spawnRemaining,spawnCooldown,revision,result,winner,nextEnemyId,log.toList(),rng.state))
 private fun restoreSnapshot(state:JsonObject){val s=NativeGamePersistence.fromJson(state,Snapshot::class.java);towers.clear();s.towers.filterKeys{it in definition.buildZones}.forEach{(slot,tower)->if(tower.type in TOWER_DEFS)towers[slot]=tower.copy(level=tower.level.coerceIn(1,definition.upgrades.maxLevel),cooldown=tower.cooldown.coerceAtLeast(0))};enemies.clear();s.enemies.filter{it.maxHp>0&&it.progress>=0.0}.forEach{enemy->enemies+=enemy.copy(hp=enemy.hp.coerceIn(0,enemy.maxHp),progress=enemy.progress.coerceAtMost(PATH.lastIndex+1.0))};gold=s.gold.coerceIn(0,1_000_000);lives=s.lives.coerceIn(0,1000);wave=s.wave.coerceAtLeast(0);running=s.running&&s.result==null;spawnRemaining=s.spawnRemaining.coerceAtLeast(0);spawnCooldown=s.spawnCooldown.coerceAtLeast(0);revision=s.revision.coerceAtLeast(0L);result=s.result;winner=s.winner?.takeIf{id->seats.any{it.id==id}};nextEnemyId=maxOf(s.nextEnemyId,(enemies.maxOfOrNull{it.id}?:0)+1);log.clear();s.log.takeLast(40).forEach(log::add);rng.restore(s.rngState);lastStepAt=System.currentTimeMillis()}
 private fun startWave():NativeGameResult{if(running)return NativeGameResult(false,message="Wave already running");wave++;running=true;spawnRemaining=definition.wave.baseEnemies+wave*definition.wave.enemiesPerWave+if(wave%definition.wave.bossEvery==0)1 else 0;spawnCooldown=0;bump("Wave $wave bắt đầu${if(wave%definition.wave.bossEvery==0)" • BOSS" else ""}");return NativeGameResult(true,true,"Wave started")}
 private fun deploy(type:String?,slot:Int?):NativeGameResult{val d=type?.let(TOWER_DEFS::get)?:return NativeGameResult(false,message="Unknown tower");val s=slot?:return NativeGameResult(false,message="Missing slot");if(s !in definition.buildZones||s in towers)return NativeGameResult(false,message="Cannot deploy there");if(gold<d.cost)return NativeGameResult(false,message="Not enough gold");gold-=d.cost;towers[s]=Tower(d.id,1,0);bump("Deploy ${d.name} @ $s");return NativeGameResult(true,true,"Deployed")}
 private fun upgrade(slot:Int?):NativeGameResult{val s=slot?:return NativeGameResult(false,message="Missing slot");val t=towers[s]?:return NativeGameResult(false,message="Tower not found");if(t.level>=definition.upgrades.maxLevel)return NativeGameResult(false,message="Max level");val cost=TOWER_DEFS.getValue(t.type).cost*t.level;if(gold<cost)return NativeGameResult(false,message="Not enough gold");gold-=cost;t.level++;bump("Upgrade ${TOWER_DEFS.getValue(t.type).name} → Lv.${t.level}");return NativeGameResult(true,true,"Upgraded")}
 private fun sell(slot:Int?):NativeGameResult{val s=slot?:return NativeGameResult(false,message="Missing slot");val t=towers.remove(s)?:return NativeGameResult(false,message="Tower not found");val base=TOWER_DEFS.getValue(t.type).cost;val invested=base+(1 until t.level).sumOf{base*it};val refund=(invested*definition.upgrades.sellRatio).toInt();gold+=refund;bump("Sell ${TOWER_DEFS.getValue(t.type).name} +${refund}g");return NativeGameResult(true,true,"Sold")}
 private fun step(){if(!running||finished)return;if(spawnRemaining>0){if(spawnCooldown<=0){val boss=wave%definition.wave.bossEvery==0&&spawnRemaining==1;spawnEnemy(boss);spawnRemaining--;spawnCooldown=if(boss)definition.wave.bossSpawnCooldown else definition.wave.normalSpawnCooldown}else spawnCooldown--};towers.forEach{(slot,t)->if(t.cooldown>0){t.cooldown--;return@forEach};val d=TOWER_DEFS.getValue(t.type);val range=d.range+(t.level-1)*definition.upgrades.rangePerLevel;val target=enemies.filter{it.hp>0&&distanceToPath(slot,it.progress)<=range}.maxByOrNull{it.progress};if(target!=null){var damage=(d.damage*(1.0+(t.level-1)*definition.upgrades.damagePerLevel)).toInt();if(d.element==target.weakness)damage=(damage*definition.upgrades.weaknessMultiplier).toInt();target.hp-=damage;t.fireSerial++;t.targetEnemyId=target.id;t.cooldown=(d.cooldown-t.level/definition.upgrades.cooldownReductionEveryLevels).coerceAtLeast(1)}};val dead=enemies.filter{it.hp<=0};dead.forEach{gold+=it.reward};enemies.removeAll(dead.toSet());val it=enemies.iterator();while(it.hasNext()){val e=it.next();e.progress+=e.speed;if(e.progress>=PATH.lastIndex+.95){lives-=e.leakDamage;it.remove();bump("${e.kind} lọt qua • lives=$lives");if(lives<=0){finish("Thất thủ ở wave $wave",null);return}}};if(spawnRemaining==0&&enemies.isEmpty()){running=false;val bonus=definition.wave.clearGold+wave*definition.wave.clearGoldPerWave;gold+=bonus;bump("Clear wave $wave • +${bonus}g");if(wave>=definition.victoryWave)finish("Victory • clear ${definition.victoryWave} waves",seats.first().id)};revision++}
 private fun spawnEnemy(boss:Boolean){val scale=1.0+wave*definition.wave.hpScalePerWave;if(boss){val d=definition.bosses[((wave/definition.wave.bossEvery)-1).coerceIn(0,definition.bosses.lastIndex)];val hp=(d.hp*scale).toInt();enemies+=Enemy(nextEnemyId++,d.id,hp,hp,d.speed,d.reward,d.weaknesses.random(rng),d.leakDamage,0.0)}else{val d=definition.enemies.random(rng);val hp=(d.hp*scale).toInt();enemies+=Enemy(nextEnemyId++,d.id,hp,hp,d.speed+wave.coerceAtMost(definition.wave.speedScaleWaveCap)*definition.wave.speedPerWave,d.reward+wave/3,d.weakness,d.leakDamage,0.0)}}
 private fun distanceToPath(slot:Int,progress:Double):Double{val p=PATH[progress.toInt().coerceIn(0,PATH.lastIndex)];return abs(slot%definition.width-p%definition.width).toDouble()+abs(slot/definition.width-p/definition.width).toDouble()};private fun finish(r:String,w:String?){result=r;winner=w;running=false;bump(r)};private fun bump(m:String){revision++;log.add(m);while(log.size>40)log.removeFirst()}
 private data class Snapshot(val towers:Map<Int,Tower>,val enemies:List<Enemy>,val gold:Int,val lives:Int,val wave:Int,val running:Boolean,val spawnRemaining:Int,val spawnCooldown:Int,val revision:Long,val result:String?,val winner:String?,val nextEnemyId:Int,val log:List<String>,val rngState:Long)
 private data class Tower(var type:String,var level:Int,var cooldown:Int,var fireSerial:Long=0L,var targetEnemyId:Int?=null);private data class Enemy(val id:Int,val kind:String,var hp:Int,val maxHp:Int,val speed:Double,val reward:Int,val weakness:String,val leakDamage:Int,var progress:Double);private data class TowerDef(val id:String,val name:String,val species:String,val element:String,val cost:Int,val damage:Int,val range:Double,val cooldown:Int,val moveId:String)
}
