package io.github.aristheg201.svhub.native.game

import kotlin.random.Random

class UnoSession(override val seats:List<NativeSeat>,seed:Long=Random.nextLong(),override val sessionId:String=NativeIds.session("uno")):NativeGameSession{
 override val gameId="uno";private val rng=Random(seed);private val drawPile=ArrayDeque<Card>();private val discard=ArrayDeque<Card>();private val hands=seats.associate{it.id to mutableListOf<Card>()}.toMutableMap();private var turnIndex=0;private var direction=1;private var activeColor=Color.RED;private var revision=0L;private var winner:String?=null;private var result:String?=null;private val log=ArrayDeque<String>()
 init{require(seats.size in 2..4);buildDeck().shuffled(rng).forEach(drawPile::add);repeat(7){seats.forEach{hands.getValue(it.id).add(drawOne())}};var first=drawOne();while(first.kind==Kind.WILD4){drawPile.add(first);first=drawOne()};discard.add(first);activeColor=if(first.color==Color.WILD)Color.entries.filter{it!=Color.WILD}.random(rng)else first.color;applyOpening(first)}
 override val finished get()=result!=null;override val winnerSeatId get()=winner
 override fun viewFor(viewerId:String):NativeGameView{val vi=seats.indexOfFirst{it.id==viewerId};val top=discard.last();val hand=hands[viewerId].orEmpty();return NativeGameView(sessionId,gameId,"UNO",if(finished)"finished" else "playing",seats[turnIndex].name,result?:"${activeColor.name} • ${top.label()}",cards=hand.mapIndexed{i,c->NativeCardView(i.toString(),c.label(),if(isPlayable(c))"Có thể đánh" else "",c.color.name.lowercase(),c.score,mapOf("kind" to c.kind.name.lowercase(),"color" to c.color.name.lowercase()))},actions=listOf(NativeActionView("draw","Rút bài","Rút 1 lá và hết lượt",!finished&&vi==turnIndex),NativeActionView("resign","Rời ván",enabled=!finished&&vi>=0)),fields=linkedMapOf("top" to top.label(),"activeColor" to activeColor.name.lowercase(),"direction" to if(direction>0)"clockwise" else "counterclockwise","hands" to seats.joinToString(" • "){"${it.name}: ${hands.getValue(it.id).size}"},"drawPile" to drawPile.size.toString()),log=log.toList().takeLast(12),revision=revision,finished=finished,winner=winner?.let{id->seats.firstOrNull{it.id==id}?.name})}
 override fun act(viewerId:String,action:String,args:Map<String,String>):NativeGameResult{if(finished)return NativeGameResult(false,message="Game finished");val seat=seats.indexOfFirst{it.id==viewerId};if(seat<0)return NativeGameResult(false,message="Spectator");if(action=="resign"){finish("${seats[seat].name} left the game",seats.firstOrNull{it.id!=viewerId}?.id);return NativeGameResult(true,true,result.orEmpty())};if(seat!=turnIndex)return NativeGameResult(false,message="Not your turn");return when(action){"draw"->{hands.getValue(viewerId).add(drawOne());bump("${seats[seat].name} drew a card");advance();runBots();NativeGameResult(true,true,"Card drawn")};"play"->{val index=args["index"]?.toIntOrNull()?:return NativeGameResult(false,message="Missing card index");val hand=hands.getValue(viewerId);val card=hand.getOrNull(index)?:return NativeGameResult(false,message="Card not found");if(!isPlayable(card))return NativeGameResult(false,message="Card cannot be played");if(card.kind==Kind.WILD4&&hand.any{it!==card&&it.color==activeColor})return NativeGameResult(false,message="Wild +4 chỉ được đánh khi không có lá cùng màu đang active");val color=args["color"]?.uppercase()?.let{runCatching{Color.valueOf(it)}.getOrNull()};playCard(viewerId,index,color);runBots();NativeGameResult(true,true,result?:"Card played")};else->NativeGameResult(false,message="Unknown UNO action")}}
 override fun tick(nowMillis:Long):Boolean{if(!finished&&seats[turnIndex].bot){runBots();return true};return false}
 private fun playCard(id:String,index:Int,requested:Color?){val hand=hands.getValue(id);val c=hand.removeAt(index);discard.add(c);activeColor=when{c.color!=Color.WILD->c.color;requested!=null&&requested!=Color.WILD->requested;else->bestColor(hand)};bump("${seat(id).name} played ${c.label()}${if(c.color==Color.WILD)" → ${activeColor.name}" else ""}");if(hand.isEmpty()){finish("UNO! ${seat(id).name} wins",id);return};when(c.kind){Kind.SKIP->{advance();advance()};Kind.REVERSE->{direction*=-1;if(seats.size==2){advance();advance()}else advance()};Kind.DRAW2->{advance();repeat(2){hands.getValue(seats[turnIndex].id).add(drawOne())};bump("${seats[turnIndex].name} draws 2");advance()};Kind.WILD4->{advance();repeat(4){hands.getValue(seats[turnIndex].id).add(drawOne())};bump("${seats[turnIndex].name} draws 4");advance()};else->advance()}}
 private fun runBots(){var guard=0;while(!finished&&seats[turnIndex].bot&&guard++<8){val b=seats[turnIndex];val h=hands.getValue(b.id);val cs=h.withIndex().filter{x->isPlayable(x.value)&&!(x.value.kind==Kind.WILD4&&h.any{it!==x.value&&it.color==activeColor})};if(cs.isEmpty()){h.add(drawOne());bump("${b.name} drew a card");advance()}else{val p=cs.maxBy{x->when(x.value.kind){Kind.WILD4->12;Kind.DRAW2->10;Kind.SKIP,Kind.REVERSE->8;Kind.WILD->6;else->x.value.score}};playCard(b.id,p.index,bestColor(h.filterIndexed{i,_->i!=p.index}))}}}
 private fun isPlayable(c:Card):Boolean{val t=discard.last();return c.color==Color.WILD||c.color==activeColor||(c.kind==t.kind&&c.number==t.number)}
 private fun bestColor(cards:List<Card>)=Color.entries.filter{it!=Color.WILD}.maxByOrNull{c->cards.count{it.color==c}}?:Color.RED
 private fun drawOne():Card{if(drawPile.isEmpty())reshuffle();return drawPile.removeLast()};private fun reshuffle(){if(discard.size<=1)error("UNO deck exhausted");val top=discard.removeLast();val r=discard.toMutableList().shuffled(rng);discard.clear();discard.add(top);r.forEach(drawPile::add)};private fun advance(){turnIndex=(turnIndex+direction+seats.size)%seats.size}
 private fun applyOpening(c:Card){when(c.kind){Kind.SKIP->advance();Kind.REVERSE->direction=-1;Kind.DRAW2->{repeat(2){hands.getValue(seats[0].id).add(drawOne())};advance()};Kind.WILD->activeColor=Color.entries.filter{it!=Color.WILD}.random(rng);else->Unit}}
 private fun seat(id:String)=seats.first{it.id==id};private fun finish(reason:String,id:String?){result=reason;winner=id;bump(reason)};private fun bump(s:String){revision++;log.add(s);while(log.size>32)log.removeFirst()}
 private enum class Color{RED,YELLOW,GREEN,BLUE,WILD};private enum class Kind{NUMBER,SKIP,REVERSE,DRAW2,WILD,WILD4};private data class Card(val color:Color,val kind:Kind,val number:Int=-1,val serial:Int){val score:Int get()=when(kind){Kind.NUMBER->number;Kind.WILD,Kind.WILD4->50;else->20};fun label()=when(kind){Kind.NUMBER->"${color.name.lowercase().replaceFirstChar{it.uppercase()}} $number";Kind.SKIP->"${color.name} Skip";Kind.REVERSE->"${color.name} Reverse";Kind.DRAW2->"${color.name} +2";Kind.WILD->"Wild";Kind.WILD4->"Wild +4"}}
 private fun buildDeck():List<Card>{val cards=mutableListOf<Card>();var s=0;for(c in listOf(Color.RED,Color.YELLOW,Color.GREEN,Color.BLUE)){cards+=Card(c,Kind.NUMBER,0,s++);for(n in 1..9)repeat(2){cards+=Card(c,Kind.NUMBER,n,s++)};repeat(2){cards+=Card(c,Kind.SKIP,serial=s++);cards+=Card(c,Kind.REVERSE,serial=s++);cards+=Card(c,Kind.DRAW2,serial=s++)}};repeat(4){cards+=Card(Color.WILD,Kind.WILD,serial=s++);cards+=Card(Color.WILD,Kind.WILD4,serial=s++)};return cards}
}
