package io.github.aristheg201.svhub.native.game

import com.google.gson.JsonObject
import kotlin.random.Random

class XiangqiSession(override val seats:List<NativeSeat>,private val initialClockMillis:Long=600_000L,private val incrementMillis:Long=3_000L,override val sessionId:String=NativeIds.session("xiangqi"),private val restoreState:JsonObject?=null,seed:Long=Random.nextLong()):NativeGameSession{
 override val gameId="xiangqi";private val rng=NativeStatefulRandom(seed);private var board=initialBoard();private var redTurn=true;private var revision=0L;private var result:String?=null;private var winner:String?=null;private val log=ArrayDeque<String>();private var redClock=initialClockMillis;private var blackClock=initialClockMillis;private var lastClockAt=System.currentTimeMillis();private var lastMoveFrom=-1;private var lastMoveTo=-1;private var moveSerial=0L
 init{require(seats.size==2);restoreState?.let(::restoreSnapshot)};override val finished get()=result!=null;override val winnerSeatId get()=winner
 override fun viewFor(viewerId:String):NativeGameView{val i=seats.indexOfFirst{it.id==viewerId};val viewerRed=when(i){0->true;1->false;else->null};val legal=if(!finished&&viewerRed==redTurn)legalMoves(redTurn)else emptyList();return NativeGameView(sessionId,gameId,"Cờ Tướng",if(finished)"finished" else "playing",if(redTurn)seats[0].name else seats[1].name,result?:if(isInCheck(redTurn))"Chiếu tướng" else if(redTurn)"Đỏ đi" else "Đen đi",9,10,board.map{if(it=='.')"" else it.toString()},actions=listOf(NativeActionView("resign","Nhận thua",enabled=!finished&&i in 0..1)),fields=linkedMapOf("you" to when(i){0->"red";1->"black";else->"spectator"},"red" to seats[0].name,"black" to seats[1].name,"redClockMs" to redClock.toString(),"blackClockMs" to blackClock.toString(),"legalMoves" to legal.joinToString(";"){coord(it.from)+":"+coord(it.to)},"lastMoveFrom" to if(lastMoveFrom>=0)coord(lastMoveFrom)else "","lastMoveTo" to if(lastMoveTo>=0)coord(lastMoveTo)else "","moveSerial" to moveSerial.toString()),log=log.toList().takeLast(12),revision=revision,finished=finished,winner=winner?.let{w->seats.firstOrNull{it.id==w}?.name})}
 override fun act(viewerId:String,action:String,args:Map<String,String>):NativeGameResult{if(finished)return NativeGameResult(false,message="Game already finished");val seat=seats.indexOfFirst{it.id==viewerId};if(seat !in 0..1)return NativeGameResult(false,message="Spectator");if(action=="resign"){finish("${seats[seat].name} nhận thua",seats[1-seat].id);return NativeGameResult(true,true,result.orEmpty())};if(action!="move")return NativeGameResult(false,message="Unknown Xiangqi action");if((redTurn&&seat!=0)||(!redTurn&&seat!=1))return NativeGameResult(false,message="Chưa tới lượt");val from=parse(args["from"])?:return NativeGameResult(false,message="Ô bắt đầu không hợp lệ");val to=parse(args["to"])?:return NativeGameResult(false,message="Ô đích không hợp lệ");val m=legalMoves(redTurn).firstOrNull{it.from==from&&it.to==to}?:return NativeGameResult(false,message="Nước đi không hợp lệ");applyMove(m);maybeRunBot();return NativeGameResult(true,true,result?:"Đã đi")}
 override fun tick(nowMillis:Long):Boolean{if(finished)return false;val d=(nowMillis-lastClockAt).coerceIn(0L,2000L);lastClockAt=nowMillis;if(redTurn)redClock-=d else blackClock-=d;if(redClock<=0){redClock=0;finish("Đỏ hết giờ",seats[1].id);return true};if(blackClock<=0){blackClock=0;finish("Đen hết giờ",seats[0].id);return true};if(currentSeat().bot){maybeRunBot();return true};return false}
 override fun snapshotState(nowMillis:Long):JsonObject=NativeGamePersistence.toJson(Snapshot(String(board),redTurn,revision,result,winner,log.toList(),redClock.coerceAtLeast(0L),blackClock.coerceAtLeast(0L),lastMoveFrom,lastMoveTo,moveSerial,rng.state))
 private fun restoreSnapshot(state:JsonObject){val s=NativeGamePersistence.fromJson(state,Snapshot::class.java);require(s.board.length==90){"Invalid Xiangqi recovery board"};board=s.board.toCharArray();redTurn=s.redTurn;revision=s.revision.coerceAtLeast(0L);result=s.result;winner=s.winner?.takeIf{id->seats.any{it.id==id}};log.clear();s.log.takeLast(32).forEach(log::add);redClock=s.redClock.coerceAtLeast(0L);blackClock=s.blackClock.coerceAtLeast(0L);lastMoveFrom=s.lastMoveFrom.takeIf{it in -1..89}?:-1;lastMoveTo=s.lastMoveTo.takeIf{it in -1..89}?:-1;moveSerial=s.moveSerial.coerceAtLeast(0L);rng.restore(s.rngState);lastClockAt=System.currentTimeMillis()}
 private fun maybeRunBot(){var g=0;while(!finished&&currentSeat().bot&&g++<2){val ms=legalMoves(redTurn);if(ms.isEmpty()){noMoves();return};applyMove(ms.maxBy{value(board[it.to])*20+rng.nextInt(12)})}}
 private fun applyMove(m:Move){val p=board[m.from];val c=board[m.to];board[m.from]='.';board[m.to]=p;val note="${coord(m.from)}-${coord(m.to)}${if(c!='.')"x$c" else ""}";if(redTurn)redClock+=incrementMillis else blackClock+=incrementMillis;lastMoveFrom=m.from;lastMoveTo=m.to;moveSerial++;redTurn=!redTurn;lastClockAt=System.currentTimeMillis();bump(note);if(board.none{it=='K'}){finish("Tướng đỏ bị bắt",seats[1].id);return};if(board.none{it=='k'}){finish("Tướng đen bị bắt",seats[0].id);return};if(legalMoves(redTurn).isEmpty())noMoves()}
 private fun noMoves(){val loser=if(redTurn)0 else 1;finish(if(isInCheck(redTurn))"Chiếu bí" else "Hết nước đi",seats[1-loser].id)}
 private fun legalMoves(red:Boolean)=pseudoMoves(red).filter{m->val snap=board.copyOf();board[m.to]=board[m.from];board[m.from]='.';val ok=!isInCheck(red);board=snap;ok}
 private fun pseudoMoves(red:Boolean):List<Move>{val out=ArrayList<Move>(64);for(from in board.indices){val p=board[from];if(p=='.'||isRed(p)!=red)continue;when(p.lowercaseChar()){'k'->generalMoves(from,red,out);'a'->advisorMoves(from,red,out);'e'->elephantMoves(from,red,out);'h'->horseMoves(from,red,out);'r'->sliding(from,red,false,out);'c'->sliding(from,red,true,out);'p'->pawnMoves(from,red,out)}};return out}
 private fun generalMoves(from:Int,red:Boolean,out:MutableList<Move>){val f=file(from);val r=row(from);for((df,dr) in ORTHO)addIf(from,f+df,r+dr,red,out){nf,nr->inPalace(nf,nr,red)};val step=if(red)-1 else 1;var rr=r+step;while(rr in 0..9){val p=board[idx(f,rr)];if(p!='.'){if(p==if(red)'k' else 'K')out+=Move(from,idx(f,rr));break};rr+=step}}
 private fun advisorMoves(from:Int,red:Boolean,out:MutableList<Move>){val f=file(from);val r=row(from);for((df,dr) in DIAG)addIf(from,f+df,r+dr,red,out){nf,nr->inPalace(nf,nr,red)}}
 private fun elephantMoves(from:Int,red:Boolean,out:MutableList<Move>){val f=file(from);val r=row(from);for((df,dr) in ELEPHANT){val nf=f+df;val nr=r+dr;if(nf !in 0..8||nr !in 0..9)continue;if(red&&nr<5||!red&&nr>4)continue;if(board[idx(f+df/2,r+dr/2)]!='.')continue;addTarget(from,nf,nr,red,out)}}
 private fun horseMoves(from:Int,red:Boolean,out:MutableList<Move>){val f=file(from);val r=row(from);val specs=arrayOf((1 to 0) to (2 to 1),(1 to 0) to (2 to -1),(-1 to 0) to (-2 to 1),(-1 to 0) to (-2 to -1),(0 to 1) to (1 to 2),(0 to 1) to (-1 to 2),(0 to -1) to (1 to -2),(0 to -1) to (-1 to -2));for((leg,dest) in specs){val lf=f+leg.first;val lr=r+leg.second;val nf=f+dest.first;val nr=r+dest.second;if(lf !in 0..8||lr !in 0..9||board[idx(lf,lr)]!='.')continue;if(nf in 0..8&&nr in 0..9)addTarget(from,nf,nr,red,out)}}
 private fun sliding(from:Int,red:Boolean,cannon:Boolean,out:MutableList<Move>){val f=file(from);val r=row(from);for((df,dr) in ORTHO){var nf=f+df;var nr=r+dr;var screen=false;while(nf in 0..8&&nr in 0..9){val to=idx(nf,nr);val p=board[to];if(!cannon){if(p=='.')out+=Move(from,to)else{if(isRed(p)!=red)out+=Move(from,to);break}}else if(!screen){if(p=='.')out+=Move(from,to)else screen=true}else if(p!='.'){if(isRed(p)!=red)out+=Move(from,to);break};nf+=df;nr+=dr}}}
 private fun pawnMoves(from:Int,red:Boolean,out:MutableList<Move>){val f=file(from);val r=row(from);addTarget(from,f,r+if(red)-1 else 1,red,out);val crossed=if(red)r<=4 else r>=5;if(crossed){addTarget(from,f-1,r,red,out);addTarget(from,f+1,r,red,out)}}
 private fun addIf(from:Int,nf:Int,nr:Int,red:Boolean,out:MutableList<Move>,predicate:(Int,Int)->Boolean){if(nf in 0..8&&nr in 0..9&&predicate(nf,nr))addTarget(from,nf,nr,red,out)}
 private fun addTarget(from:Int,nf:Int,nr:Int,red:Boolean,out:MutableList<Move>){if(nf !in 0..8||nr !in 0..9)return;val p=board[idx(nf,nr)];if(p=='.'||isRed(p)!=red)out+=Move(from,idx(nf,nr))}
 private fun isInCheck(red:Boolean):Boolean{val k=board.indexOf(if(red)'K' else 'k');if(k<0)return true;return pseudoMoves(!red).any{it.to==k}}
 private fun currentSeat()=seats[if(redTurn)0 else 1];private fun finish(r:String,w:String?){result=r;winner=w;revision++;log.add(r);while(log.size>32)log.removeFirst()};private fun bump(m:String){revision++;log.add(m);while(log.size>32)log.removeFirst()};private data class Move(val from:Int,val to:Int)
 private data class Snapshot(val board:String,val redTurn:Boolean,val revision:Long,val result:String?,val winner:String?,val log:List<String>,val redClock:Long,val blackClock:Long,val lastMoveFrom:Int,val lastMoveTo:Int,val moveSerial:Long,val rngState:Long)
 companion object{private val ORTHO=arrayOf(1 to 0,-1 to 0,0 to 1,0 to -1);private val DIAG=arrayOf(1 to 1,1 to -1,-1 to 1,-1 to -1);private val ELEPHANT=arrayOf(2 to 2,2 to -2,-2 to 2,-2 to -2);private fun initialBoard():CharArray{val b=CharArray(90){'.'};fun rr(r:Int,s:String){for(f in 0..8)b[idx(f,r)]=s[f]};rr(0,"rheakaehr");b[idx(1,2)]='c';b[idx(7,2)]='c';for(f in intArrayOf(0,2,4,6,8))b[idx(f,3)]='p';for(f in intArrayOf(0,2,4,6,8))b[idx(f,6)]='P';b[idx(1,7)]='C';b[idx(7,7)]='C';rr(9,"RHEAKAEHR");return b};private fun idx(f:Int,r:Int)=r*9+f;private fun file(i:Int)=i%9;private fun row(i:Int)=i/9;private fun isRed(p:Char)=p.isUpperCase();private fun inPalace(f:Int,r:Int,red:Boolean)=f in 3..5&&if(red)r in 7..9 else r in 0..2;private fun coord(i:Int)="${('a'.code+file(i)).toChar()}${row(i)}";private fun parse(v:String?):Int?{if(v==null||v.length !in 2..3)return null;val f=v[0].lowercaseChar()-'a';val r=v.substring(1).toIntOrNull()?:return null;return if(f in 0..8&&r in 0..9)idx(f,r)else null};private fun value(p:Char)=when(p.lowercaseChar()){'k'->100;'r'->9;'c'->5;'h'->4;'e','a'->2;'p'->1;else->0}}
}
