package vn.svframe.lively.dialogue;

import java.text.Normalizer;import java.util.HashMap;import java.util.Locale;import java.util.Map;import java.util.regex.Matcher;import java.util.regex.Pattern;
/** Generic offline intent/entity parser. Domain integrations can enrich facts without replacing the core NLU. */
public final class NluEngine {public enum Intent{ASSERT_INFORMATION,ASK_INFORMATION,OFFER_HELP,CHALLENGE,TRADE,GREETING,GOODBYE,GOSSIP,ACCUSE,APOLOGIZE,AFFECTION,THREAT,UNKNOWN}public record Meaning(Intent intent,Map<String,String> slots,double confidence){public Meaning{slots=Map.copyOf(slots);}}
 private static final Pattern QUOTED=Pattern.compile("[\\\"“”']([^\\\"“”']{2,80})[\\\"“”']");private static final Pattern ABOUT=Pattern.compile("(?i)(?:về|about)\\s+([\\p{L}0-9 _:-]{2,80})");private static final Pattern LOCATION=Pattern.compile("(?i)(?:ở|tại|gần|near|at|in)\\s+([\\p{L}0-9 _:-]{2,80})");
 public Meaning parse(String raw){String text=raw==null?"":raw.trim();String s=fold(text);Map<String,String> slots=new HashMap<>();capture(QUOTED,text).ifPresent(v->slots.put("subject",clean(v)));capture(ABOUT,text).ifPresent(v->slots.putIfAbsent("subject",clean(v)));capture(LOCATION,text).ifPresent(v->slots.put("location",clean(v)));
  if(any(s,"xin chao","chao","hello","hey"," hi "))return new Meaning(Intent.GREETING,slots,.88D);if(any(s,"tam biet","goodbye","bye","hen gap"))return new Meaning(Intent.GOODBYE,slots,.92D);
  if(any(s,"xin loi","sorry","toi sai","tha loi"))return new Meaning(Intent.APOLOGIZE,slots,.88D);if(any(s,"toi thich","toi yeu","i like you","i love you","hen ho"))return new Meaning(Intent.AFFECTION,slots,.82D);
  if(any(s,"tao se giet","toi se giet","de doa","threat","se danh may","se xu may"))return new Meaning(Intent.THREAT,slots,.86D);if(any(s,"chinh ong","chinh ba","chinh may","thu pham","toi cao","accuse","nghi pham"))return new Meaning(Intent.ACCUSE,slots,.76D);
  if(any(s,"tin don","nghe noi","gossip","rumor","chuyen gi dang lan"))return new Meaning(Intent.GOSSIP,slots,.84D);if(any(s,"toi thay","minh thay","toi biet rang","i saw","i found","i know that"))return new Meaning(Intent.ASSERT_INFORMATION,slots,.84D);
  if(any(s,"o dau","where","biet gi","what do you know","ai la","who is","tai sao","why"))return new Meaning(Intent.ASK_INFORMATION,slots,.80D);if(any(s,"giup","help","toi co the lam gi"))return new Meaning(Intent.OFFER_HELP,slots,.78D);
  if(any(s,"thach dau","dau voi","battle","challenge"))return new Meaning(Intent.CHALLENGE,slots,.82D);if(any(s,"mua","ban","giao dich","trade","shop","gia bao nhieu"))return new Meaning(Intent.TRADE,slots,.80D);
  slots.put("text",text);return new Meaning(Intent.UNKNOWN,slots,.20D);}
 private static boolean any(String text,String...needles){String padded=" "+text+" ";for(String n:needles)if(padded.contains(n))return true;return false;}private static java.util.Optional<String> capture(Pattern p,String input){Matcher m=p.matcher(input);return m.find()?java.util.Optional.of(m.group(1)):java.util.Optional.empty();}private static String clean(String s){return s.trim().replaceAll("[?.!,;]+$","");}private static String fold(String value){String n=Normalizer.normalize(value.toLowerCase(Locale.ROOT),Normalizer.Form.NFD).replaceAll("\\p{M}+","");return n.replace('đ','d').replaceAll("\\s+"," ").trim();}}
