package vn.worldcomesalive;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import vn.worldcomesalive.model.LivingWorld;
import vn.worldcomesalive.model.LivingWorld.*;
import vn.worldcomesalive.civilization.*;
import vn.worldcomesalive.data.WorldContent;
import vn.worldcomesalive.world.SettlementBootstrap;
import vn.worldcomesalive.server.WorldStore;
import java.util.*;
class CivilizationTest {
    private LivingWorld world(){var w=new LivingWorld();var d=WorldContent.defaults();var s=SettlementBootstrap.create(414212,new Pos(0,70,0),"plains",d,"village");w.settlements.put(s.id,s);SettlementBootstrap.populate(w,s,d,List.of());CivilizationRules.initialize(w,s);return w;}
    @Test void leadershipIsARealResidentAndSucceedsAfterDeath(){var w=world();var s=w.settlements.values().iterator().next();var g=w.civilization.governments.get(s.id);assertTrue(s.residents.contains(g.leader));var former=w.npcs.get(g.leader);assertTrue(former.roles.contains("Leader"));UUID deputy=g.deputy;former.lifeStage="deceased";CivilizationRules.succession(w,s,g);assertEquals(deputy,g.leader);assertFalse(former.roles.contains("Leader"));assertTrue(w.npcs.get(g.leader).roles.contains("Leader"));assertNotEquals(g.leader,g.deputy);}
    @Test void aRequestNeedsAnActualShortageAndEscrowsExistingFunds(){var w=world();var s=w.settlements.values().iterator().next();var bakery=s.service("bakery");var baker=w.npcs.values().stream().filter(n->n.profession.equals("baker")).findFirst().orElseThrow();bakery.stock.put("minecraft:wheat",100);assertNull(CivilizationRules.shortage(w,s,bakery,baker));bakery.stock.put("minecraft:wheat",1);long money=bakery.money;var c=CivilizationRules.shortage(w,s,bakery,baker);assertNotNull(c);assertEquals(money-c.reward,bakery.money);assertEquals(12,c.required);assertTrue(baker.memories.stream().anyMatch(m->m.source().equals("inspected workplace")));assertNull(CivilizationRules.shortage(w,s,bakery,baker));}
    @Test void deliveringActualGoodsUpdatesEconomyAndPaysOnlyOnce(){var w=world();var s=w.settlements.values().iterator().next();var bakery=s.service("bakery");bakery.stock.put("minecraft:wheat",0);var baker=w.npcs.values().stream().filter(n->n.profession.equals("baker")).findFirst().orElseThrow();var c=CivilizationRules.shortage(w,s,bakery,baker);UUID p=UUID.randomUUID();assertTrue(CivilizationRules.accept(c,p,w.clock));assertFalse(CivilizationRules.accept(c,UUID.randomUUID(),w.clock));assertEquals(0,CivilizationRules.deliver(w,c,UUID.randomUUID(),c.required));assertEquals(0,CivilizationRules.deliver(w,c,p,c.required-1));assertEquals(c.reward,CivilizationRules.deliver(w,c,p,c.required));assertEquals(c.required,bakery.stock.get(c.item));assertEquals(60+c.reward,w.players.get(p).money);assertEquals("COMPLETED",c.status);assertEquals(0,CivilizationRules.deliver(w,c,p,c.required));}
    @Test void metricsReadProductionAndHousingRatherThanUnrelatedCounters(){var w=world();var s=w.settlements.values().iterator().next();var g=w.civilization.governments.get(s.id);double before=g.metrics.get("Food portions");s.service("bakery").stock.merge("minecraft:bread",7,Integer::sum);CivilizationRules.metrics(w,s,g);assertEquals(before+7,g.metrics.get("Food portions"));assertEquals((double)s.residents.size(),g.metrics.get("Population"));assertEquals((double)s.buildings.values().stream().mapToInt(b->b.beds).sum(),g.metrics.get("Housing"));}
    @Test void tradeRoutesPersistRealEconomicImbalanceAndShipmentState(){var w=new LivingWorld();var a=new Settlement();a.id="oakridge";a.name="Oakridge";a.ready=true;a.center=new Pos(0,70,0);var b=new Settlement();b.id="westhaven";b.name="Westhaven";b.ready=true;b.center=new Pos(420,70,0);a.routes.add(b.id);b.routes.add(a.id);var af=new Building();af.id="oakridge_store";af.type="trading_post";af.stock.put("minecraft:wheat",80);a.buildings.put(af.id,af);var bf=new Building();bf.id="westhaven_store";bf.type="trading_post";bf.stock.put("minecraft:wheat",4);b.buildings.put(bf.id,bf);w.settlements.put(a.id,a);w.settlements.put(b.id,b);var ga=new CivilizationState.Government();ga.metrics.put("Security",80.0);var gb=new CivilizationState.Government();gb.metrics.put("Security",70.0);w.civilization.governments.put(a.id,ga);w.civilization.governments.put(b.id,gb);TradeNetwork.initialize(w,a);TradeNetwork.initialize(w,b);TradeNetwork.refresh(w);var route=w.civilization.tradeRoutes.get(TradeNetwork.id(a.id,b.id));assertNotNull(route);assertFalse(route.blocked);assertTrue(route.distance>400);var transfer=TradeNetwork.opportunity(w,route).orElseThrow();assertEquals(a.id,transfer.origin());assertEquals(b.id,transfer.destination());assertEquals("minecraft:wheat",transfer.item());var shipment=TradeNetwork.createShipment(w,transfer,UUID.randomUUID());assertEquals("PREPARING",shipment.status);assertTrue(shipment.eta>shipment.depart);assertSame(shipment,w.civilization.shipments.get(shipment.id));var loaded=WorldStore.JSON.fromJson(WorldStore.JSON.toJson(w),LivingWorld.class);assertEquals(w.civilization.tradeRoutes.keySet(),loaded.civilization.tradeRoutes.keySet());assertEquals(w.civilization.shipments.keySet(),loaded.civilization.shipments.keySet());}
    @Test void regionalSupplyRequestComesFromRealStockImbalance(){var w=new LivingWorld();w.clock=1200;var a=new Settlement();a.id="grain";a.name="Grainford";a.ready=true;a.center=new Pos(0,70,0);var b=new Settlement();b.id="keep";b.name="Kingskeep";b.ready=true;b.center=new Pos(360,70,0);a.routes.add(b.id);b.routes.add(a.id);var source=new Building();source.id="grain_post";source.type="trading_post";source.stock.put("minecraft:wheat",90);a.buildings.put(source.id,source);var dest=new Building();dest.id="keep_post";dest.type="trading_post";dest.money=200;dest.stock.put("minecraft:wheat",2);dest.origin=new Pos(360,70,0);dest.mark(Marker.CUSTOMER_POINT,new Pos(361,71,0));b.buildings.put(dest.id,dest);var merchant=new Npc();merchant.id=UUID.randomUUID();merchant.name="Mara";merchant.profession="merchant";merchant.workplace=dest.id;merchant.settlement=b.id;merchant.location=b.center;b.residents.add(merchant.id);w.npcs.put(merchant.id,merchant);w.settlements.put(a.id,a);w.settlements.put(b.id,b);ContractDirector.tick(w);var c=w.civilization.contracts.values().stream().findFirst().orElseThrow();assertEquals("INTERSETTLEMENT_SUPPLY",c.type);assertEquals(a.id,c.origin);assertEquals(b.id,c.destination);assertEquals("minecraft:wheat",c.item);assertTrue(c.required>=6);assertTrue(c.knownInformation.contains("Grainford"));assertTrue(c.knownInformation.contains("Trading Post stock records"));assertTrue(merchant.memories.stream().anyMatch(m->m.type().equals("regional_supply_shortage")));assertEquals(200-c.reward,dest.money);}
    @Test void witnessedCrimeCreatesPersistentJurisdictionalBounty(){var w=world();var s=w.settlements.values().iterator().next();var victim=w.npcs.values().iterator().next();UUID offender=UUID.randomUUID();w.players.put(offender,new PlayerLife());var crime=BountySystem.report(w,s.id,offender,victim.id,"ASSAULT",.65,victim.id,victim.location);assertNotNull(crime);var bounty=w.civilization.bounties.values().stream().findFirst().orElseThrow();assertEquals(offender,bounty.target);assertEquals(s.id,bounty.jurisdiction);assertEquals("ALIVE_ONLY",bounty.requirement);assertEquals(victim.location,bounty.lastKnown);assertTrue(w.players.get(offender).bounty.get(s.id)>0);UUID hunter=UUID.randomUUID();long reward=BountySystem.captured(w,bounty.id,hunter);assertEquals(bounty.reward,reward);assertEquals("CAPTURED",bounty.status);assertEquals(reward,w.players.get(hunter).money-60);var loaded=WorldStore.JSON.fromJson(WorldStore.JSON.toJson(w),LivingWorld.class);assertEquals("CAPTURED",loaded.civilization.bounties.get(bounty.id).status);}
    @Test void caravanShipmentMovesRealStockAndCompletes(){var w=new LivingWorld();var a=new Settlement();a.id="a";a.name="A";a.ready=true;a.center=new Pos(0,70,0);var b=new Settlement();b.id="b";b.name="B";b.ready=true;b.center=new Pos(100,70,0);a.routes.add("b");b.routes.add("a");var origin=new Building();origin.id="a_post";origin.type="trading_post";origin.stock.put("minecraft:wheat",40);a.buildings.put(origin.id,origin);var dest=new Building();dest.id="b_post";dest.type="trading_post";dest.origin=b.center;dest.mark(Marker.CUSTOMER_POINT,b.center);b.buildings.put(dest.id,dest);w.settlements.put("a",a);w.settlements.put("b",b);TradeNetwork.initialize(w,a);TradeNetwork.initialize(w,b);var route=w.civilization.tradeRoutes.get(TradeNetwork.id("a","b"));var shipment=TradeNetwork.dispatch(w,new TradeNetwork.Transfer(route.id,"a","b","minecraft:wheat",12,100),null);assertNotNull(shipment);assertEquals(28,origin.stock.get("minecraft:wheat"));w.clock=shipment.eta;TradeNetwork.tick(w);assertEquals("DELIVERED",shipment.status);assertEquals(12,dest.stock.get("minecraft:wheat"));assertEquals(12,route.moved.get("minecraft:wheat"));}
    @Test void predatorIncidentCreatesLastKnownHuntingContract(){var w=world();var s=w.settlements.values().iterator().next();var farmer=w.npcs.values().stream().filter(n->n.profession.equals("farmer")).findFirst().orElseGet(()->w.npcs.values().iterator().next());UUID wolf=UUID.randomUUID();var t=HuntingSystem.reportPredation(w,s.id,wolf,"minecraft:wolf",new Pos(12,70,12));assertNotNull(t);var c=HuntingSystem.ensureContract(w,t);assertNotNull(c);assertEquals("PREDATOR_CONTROL",c.type);assertEquals("LAST_KNOWN",c.locationQuality);assertEquals(t.id,c.targetEntity);UUID hunter=UUID.randomUUID();assertTrue(CivilizationRules.accept(c,hunter,w.clock));long paid=HuntingSystem.killed(w,wolf,hunter);assertEquals(c.reward,paid);assertEquals("COMPLETED",c.status);assertEquals("KILLED",t.status);}
    @Test void rolesContractsAndPropertyIdentitiesSurviveReload(){var w=world();var loaded=WorldStore.JSON.fromJson(WorldStore.JSON.toJson(w),LivingWorld.class);assertEquals(w.civilization.properties.keySet(),loaded.civilization.properties.keySet());var s=w.settlements.values().iterator().next();assertEquals(w.civilization.governments.get(s.id).leader,loaded.civilization.governments.get(s.id).leader);w.npcs.forEach((id,n)->assertEquals(n.roles,loaded.npcs.get(id).roles));}
}
