package vn.worldcomesalive;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import vn.worldcomesalive.model.LivingWorld;
import vn.worldcomesalive.model.LivingWorld.*;
import vn.worldcomesalive.civilization.*;
import vn.worldcomesalive.data.WorldContent;
import vn.worldcomesalive.world.SettlementBootstrap;
import vn.worldcomesalive.server.WorldStore;
import java.util.*;
class CivilizationTest {
    private LivingWorld world(){var w=new LivingWorld();var d=WorldContent.defaults();var s=SettlementBootstrap.create(414212,new Pos(0,70,0),"plains",d,"village");w.settlements.put(s.id,s);SettlementBootstrap.populate(w,s,d,List.of());CivilizationRules.initialize(w,s);return w;}
    @Test void leadershipIsARealResidentAndSucceedsAfterDeath(){var w=world();var s=w.settlements.values().iterator().next();var g=w.civilization.governments.get(s.id);assertTrue(s.residents.contains(g.leader));var former=w.npcs.get(g.leader);assertTrue(former.roles.contains("Leader"));UUID deputy=g.deputy;former.lifeStage="deceased";CivilizationRules.succession(w,s,g);assertEquals(deputy,g.leader);assertFalse(former.roles.contains("Leader"));assertTrue(w.npcs.get(g.leader).roles.contains("Leader"));assertNotEquals(g.leader,g.deputy);}
    @Test void aRequestNeedsAnActualShortageAndEscrowsExistingFunds(){var w=world();var s=w.settlements.values().iterator().next();var bakery=s.service("bakery");var baker=w.npcs.values().stream().filter(n->n.profession.equals("baker")).findFirst().orElseThrow();bakery.stock.put("minecraft:wheat",100);assertNull(CivilizationRules.shortage(w,s,bakery,baker));bakery.stock.put("minecraft:wheat",1);long money=bakery.money;var c=CivilizationRules.shortage(w,s,bakery,baker);assertNotNull(c);assertEquals(money-c.reward,bakery.money);assertEquals(12,c.required);assertTrue(baker.memories.stream().anyMatch(m->m.source().equals("inspected workplace")));assertNull(CivilizationRules.shortage(w,s,bakery,baker));}
    @Test void deliveringActualGoodsUpdatesEconomyAndPaysOnlyOnce(){var w=world();var s=w.settlements.values().iterator().next();var bakery=s.service("bakery");bakery.stock.put("minecraft:wheat",0);var baker=w.npcs.values().stream().filter(n->n.profession.equals("baker")).findFirst().orElseThrow();var c=CivilizationRules.shortage(w,s,bakery,baker);UUID p=UUID.randomUUID();assertTrue(CivilizationRules.accept(c,p,w.clock));assertFalse(CivilizationRules.accept(c,UUID.randomUUID(),w.clock));assertEquals(0,CivilizationRules.deliver(w,c,UUID.randomUUID(),c.required));assertEquals(0,CivilizationRules.deliver(w,c,p,c.required-1));assertEquals(c.reward,CivilizationRules.deliver(w,c,p,c.required));assertEquals(c.required,bakery.stock.get(c.item));assertEquals(60+c.reward,w.players.get(p).money);assertEquals("COMPLETED",c.status);assertEquals(0,CivilizationRules.deliver(w,c,p,c.required));}
    @Test void metricsReadProductionAndHousingRatherThanUnrelatedCounters(){var w=world();var s=w.settlements.values().iterator().next();var g=w.civilization.governments.get(s.id);double before=g.metrics.get("Food portions");s.service("bakery").stock.merge("minecraft:bread",7,Integer::sum);CivilizationRules.metrics(w,s,g);assertEquals(before+7,g.metrics.get("Food portions"));assertEquals((double)s.residents.size(),g.metrics.get("Population"));assertEquals((double)s.buildings.values().stream().mapToInt(b->b.beds).sum(),g.metrics.get("Housing"));}
    @Test void rolesContractsAndPropertyIdentitiesSurviveReload(){var w=world();var loaded=WorldStore.JSON.fromJson(WorldStore.JSON.toJson(w),LivingWorld.class);assertEquals(w.civilization.properties.keySet(),loaded.civilization.properties.keySet());var s=w.settlements.values().iterator().next();assertEquals(w.civilization.governments.get(s.id).leader,loaded.civilization.governments.get(s.id).leader);w.npcs.forEach((id,n)->assertEquals(n.roles,loaded.npcs.get(id).roles));}
}
