package vn.worldcomesalive;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import vn.worldcomesalive.domestic.*;
import vn.worldcomesalive.model.LivingWorld;
import vn.worldcomesalive.model.LivingWorld.*;
import vn.worldcomesalive.server.WorldStore;
import java.util.*;

class DomesticTest {
    @Test void productionReservesRealIngredientsAndNeverInventsEarlyOutput(){var c=DomesticContent.defaults();var r=c.recipes.stream().filter(x->x.id().equals("ale")).findFirst().orElseThrow();var s=new Settlement();s.id="town";var b=new Building();b.id="tavern";b.stock.put("worldcomesalive:wort",2);var state=new DomesticState();var batch=Production.reserve(state,s,b,r,1000,.2);assertNotNull(batch);assertEquals(1,b.stock.get("worldcomesalive:wort"));assertFalse(b.stock.containsKey(r.output()));assertEquals(1300,batch.due);assertNull(Production.reserve(state,s,b,r,1000,.2));assertEquals(1,b.stock.get("worldcomesalive:wort"));}
    @Test void insufficientIngredientsAreAtomic(){var r=DomesticContent.defaults().recipes.stream().filter(x->x.id().equals("beef_stew")).findFirst().orElseThrow();var b=new Building();b.id="kitchen";b.stock.put("minecraft:beef",5);var original=Map.copyOf(b.stock);var s=new Settlement();s.id="town";assertNull(Production.reserve(new DomesticState(),s,b,r,0,.8));assertEquals(original,b.stock);}
    @Test void mealsAndPendingFermentationSurviveSerializationAtEveryLod(){LivingWorld w=new LivingWorld();var m=new DomesticState.Meal();m.id=UUID.randomUUID();m.actor=UUID.randomUUID();m.state="Served";m.table=new Pos(10,70,20);m.drink="worldcomesalive:ale";m.due=500;w.domestic.meals.put(m.id,m);var b=new DomesticState.Batch();b.id=UUID.randomUUID();b.due=1000;b.output="worldcomesalive:red_wine";w.domestic.batches.put(b.id,b);var restored=WorldStore.JSON.fromJson(WorldStore.JSON.toJson(w),LivingWorld.class);assertEquals(m.actor,restored.domestic.meals.get(m.id).actor);assertEquals("Served",restored.domestic.meals.get(m.id).state);assertEquals(m.table,restored.domestic.meals.get(m.id).table);assertEquals(1000,restored.domestic.batches.get(b.id).due);}
    @Test void purchaseConservesMoneyAndStockAndRejectsOverdraw(){var p=new PlayerLife();p.money=10;var b=new Building();b.money=100;b.stock.put("worldcomesalive:ale",1);assertTrue(DomesticManager.purchase(p,b,"worldcomesalive:ale",3));assertEquals(7,p.money);assertEquals(103,b.money);assertEquals(0,b.stock.get("worldcomesalive:ale"));assertFalse(DomesticManager.purchase(p,b,"worldcomesalive:ale",3));assertEquals(7,p.money);b.stock.put("worldcomesalive:red_wine",1);assertFalse(DomesticManager.purchase(p,b,"worldcomesalive:red_wine",8));assertEquals(1,b.stock.get("worldcomesalive:red_wine"));}
    @Test void intoxicationDecaysByElapsedTimeWithoutPermanentPenalty(){var c=DomesticContent.defaults();assertEquals("Sober",c.stage(0));assertEquals("Tipsy",c.stage(2));assertEquals("Very Drunk",c.stage(6));assertEquals(0,c.sober(2,100,10000));assertEquals(2,c.sober(2,100,50));assertTrue(c.alcohol.maxCardPenalty()<=.2);}
    @Test void seededPreferencesDifferAndRespectChildAndHealerAbstinence(){var s=new Settlement();s.region="nordic";var a=new Npc();a.id=UUID.randomUUID();a.age=12;var b=new Npc();b.id=UUID.randomUUID();b.age=30;b.profession="healer";DomesticManager.preferences(a,s);DomesticManager.preferences(b,s);assertEquals(-1,a.preferences.get("worldcomesalive:ale"));assertEquals(-1,b.preferences.get("worldcomesalive:red_wine"));assertNotEquals(a.preferences.get("worldcomesalive:beef_stew"),b.preferences.get("worldcomesalive:beef_stew"));}
    @Test void regionalMenuPricesAndRelationshipDiscountsUseCatalog(){var c=DomesticContent.defaults();assertTrue(c.price("worldcomesalive:ale","nordic",0)<c.price("worldcomesalive:ale","coastal",0));assertTrue(c.price("worldcomesalive:feast_platter","coastal",50)<=c.price("worldcomesalive:feast_platter","coastal",0));assertTrue(c.goods.size()>=60);assertTrue(c.recipes.size()>=60);}
    @Test void invalidNegativeRecipeAndMissingFieldsFailGracefully(){assertThrows(RuntimeException.class,()->DomesticContent.read(new java.io.StringReader("{}")));var c=DomesticContent.defaults();var r=c.recipes.getFirst();c.recipes.set(0,new DomesticContent.Recipe(r.id(),r.output(),Map.of("minecraft:wheat",-1),r.station(),r.ticks(),r.count(),r.roles(),r.quality()));assertThrows(IllegalArgumentException.class,c::validate);}
}
