package vn.worldcomesalive;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import vn.worldcomesalive.generation.v2.*;
import vn.worldcomesalive.generation.v2.Spatial.*;
import java.util.*;
import com.google.gson.Gson;
class GenerationV2Test {
    @Test void economicProgramPrecedesGeometryAndRetainsFiveResidentialSilhouettes(){var d=GenerationCatalog.defaults();for(String archetype:List.of("farming_village","market_town")){var p=SettlementProgram.create(4112,archetype,"temperate",d);assertTrue(p.homes().stream().distinct().count()>=5);assertTrue(p.foodCapacity()>=p.populationTarget()*24);assertTrue(p.services().containsKey("barn"));}}
    @Test void deterministicConnectedNonOverlappingPlansForMultipleSeeds(){var d=GenerationCatalog.defaults();Gson gson=new Gson();for(long seed:List.of(12L,414212L,78119L)){var program=SettlementProgram.create(seed,"farming_village","temperate",d);var first=SettlementPlanner.plan(program,new Point(0,0),TerrainSnapshot.flat(190,72),d);var second=SettlementPlanner.plan(program,new Point(0,0),TerrainSnapshot.flat(190,72),d);assertEquals(gson.toJson(first),gson.toJson(second));assertTrue(first.failures.isEmpty());assertTrue(first.quality.get("roadClasses")>=5);assertTrue(first.quality.get("foodCapacity")>=program.foodCapacity());assertTrue(first.fields.size()>=6);assertTrue(first.quality.get("agriculturalArea")>first.quality.get("buildingArea"),"Economic footprint: "+first.quality);}}
    @Test void routerAvoidsRiverRatherThanDrawingRoadThroughWater(){int size=41;List<TerrainSnapshot.Sample> cells=new ArrayList<>();for(int z=0;z<size;z++)for(int x=0;x<size;x++)cells.add(new TerrainSnapshot.Sample(72,x==20&&z>8&&z<32,0));var t=new TerrainSnapshot(-60,-60,size,3,cells);var path=TerrainRouter.route(new Point(-35,0),new Point(35,0),t,GenerationCatalog.defaults().roads.get("MAIN_STREET"));assertTrue(path.stream().allMatch(p->!t.at(p.x(),p.z()).water()));assertTrue(path.stream().anyMatch(p->Math.abs(p.z())>=36));}
    @Test void invalidGenerationNeverSilentlyAcceptsMissingAgriculture(){var d=GenerationCatalog.defaults();var program=SettlementProgram.create(12,"farming_village","temperate",d);var p=SettlementPlanner.plan(program,new Point(0,0),TerrainSnapshot.flat(190,72),d);p.fields.clear();GenerationValidation.validate(p,d);assertTrue(p.failures.contains("Insufficient agriculture"));}
    @Test void planSurvivesSerializationWithAuthoredRoomPrograms(){var d=GenerationCatalog.defaults();var program=SettlementProgram.create(42,"market_town","temperate",d);var plan=SettlementPlanner.plan(program,new Point(0,0),TerrainSnapshot.flat(190,72),d);Gson gson=new Gson();var copy=gson.fromJson(gson.toJson(plan),SettlementPlan.class);assertEquals(2,copy.generationVersion);assertEquals(plan.buildings,copy.buildings);assertEquals(plan.roads,copy.roads);assertTrue(copy.buildings.stream().anyMatch(b->b.rooms().stream().anyMatch(r->r.type().equals("INN_PREMIUM_ROOM"))));}
}
